Repository terrapkg/packages, pull requests merged in 2023-12, with the labels that each got.

#832 add: alsa-ucm-cros
  anda/others/alsa-ucm-cros/alsa-ucm-cros.spec
  anda/others/alsa-ucm-cros/anda.hcl
  anda/others/alsa-ucm-cros/update.rhai
Labels: enhancement, new

#833 fix(deps): ouch
  anda/rust/ouch/rust-ouch.spec
Labels: bug

#836 fix: zellij
  anda/rust/zellij/rust-zellij.spec
Labels: bug, update

#847 fix(ci): apply mock configs and stuff correctly
  .github/workflows/autobuild.yml
  .github/workflows/bootstrap.yml
  .github/workflows/build.yml
  .github/workflows/json-build.yml
Labels: bug, Urgent

#850 fix(ci): mock configs again
  .github/workflows/autobuild.yml
Labels: bug, Urgent

#846 fix: ouch
  anda/langs/rust/ouch/ouch-fix-metadata-auto.diff
  anda/langs/rust/ouch/rust-ouch.spec
Labels: bug, update

#857 add: libplacebo
  anda/lib/placebo/anda.hcl
  anda/lib/placebo/terra-libplacebo.spec
  anda/lib/placebo/update.rhai
Labels: enhancement, new

#782 add: nvidia-patch
  anda/others/nvidia-patch/anda.hcl
  anda/others/nvidia-patch/nvidia-patch.spec
Labels: enhancement, new

#851 add: submarine
  anda/system/submarine/anda.hcl
  anda/system/submarine/submarine.spec
  anda/system/submarine/update.rhai
Labels: enhancement, new
