Repository terrapkg/packages, pull requests merged in 2023-02, with the labels that each got.

#170 Add gradle gendesk golang-xyproto-env golang-xyproto-textoutput golang-xyproto-vt100 golang-yhat-scrape
  anda/go/gendesk/anda.hcl
  anda/go/gendesk/golang-github-xyproto-gendesk.spec
  anda/go/gendesk/update.rhai
  anda/go/xyproto-env/anda.hcl
  anda/go/xyproto-env/golang-github-xyproto-env.spec
  anda/go/xyproto-env/update.rhai
  anda/go/xyproto-textoutput/anda.hcl
  anda/go/xyproto-textoutput/golang-github-xyproto-textoutput.spec
  anda/go/xyproto-textoutput/update.rhai
  anda/go/xyproto-vt100/anda.hcl
  anda/go/xyproto-vt100/golang-github-xyproto-vt100.spec
  anda/go/xyproto-vt100/update.rhai
  anda/go/yhat-scrape/anda.hcl
  anda/go/yhat-scrape/golang-github-yhat-scrape.spec
  anda/go/yhat-scrape/update.rhai
  anda/tools/gradle/anda.hcl
  anda/tools/gradle/gradle.spec
  anda/tools/gradle/update.rhai
Labels: enhancement

#169 Add opsu
  anda/games/opsu/anda.hcl
  anda/games/opsu/opsu.spec
  anda/games/opsu/update.rhai
Labels: enhancement

#171 Add groovy groovy-docs
  anda/groovy/anda.hcl
  anda/groovy/groovy-docs/anda.hcl
  anda/groovy/groovy-docs/groovy-docs.spec
  anda/groovy/groovy.spec
  anda/groovy/update.rhai
Labels: enhancement

#172 Fix groovy groovy-docs
  anda/groovy/groovy-docs/groovy-docs.spec
  anda/groovy/groovy.spec
Labels: bug

#177 Fix gradle
  anda/games/opsu/opsu.spec
  anda/games/prismlauncher-nightly/prismlauncher-nightly.spec
  anda/games/prismlauncher-qt5-nightly/prismlauncher-qt5-nightly.spec
  anda/games/prismlauncher-qt5/prismlauncher-qt5.spec
  anda/games/prismlauncher/prismlauncher.spec
  anda/go/xyproto-env/golang-github-xyproto-env.spec
  anda/go/yhat-scrape/golang-github-yhat-scrape.spec
  anda/tools/gradle/gradle.spec
Labels: bug

#181 Add hyperfine
  anda/rust/hyperfine/anda.hcl
  anda/rust/hyperfine/hyperfine-fix-metadata-auto.diff
  anda/rust/hyperfine/rust-hyperfine.spec
  anda/rust/hyperfine/update.rhai
Labels: enhancement, new

#182 Add gping
  anda/rust/gping/anda.hcl
  anda/rust/gping/rust-gping.spec
  anda/rust/gping/update.rhai
Labels: enhancement, new

#180 Add ouch
  anda/rust/ouch/anda.hcl
  anda/rust/ouch/ouch-fix-metadata-auto.diff
  anda/rust/ouch/rust-ouch.spec
  anda/rust/ouch/update.rhai
Labels: enhancement, new

#183 Add gitoxide
  anda/rust/gitoxide/anda.hcl
  anda/rust/gitoxide/rust-gitoxide.spec
  anda/rust/gitoxide/update.rhai
Labels: enhancement, new

#184 Add typeracer
  anda/rust/typeracer/anda.hcl
  anda/rust/typeracer/rust-typeracer.spec
  anda/rust/typeracer/update.rhai
Labels: enhancement, new

#179 Add graalvm
  anda/tools/graalvm/anda.hcl
  anda/tools/graalvm/graalvm.spec
  anda/tools/graalvm/update.rhai
Labels: enhancement, new

#187 fix(update): groovy groovy-docs
  anda/groovy/groovy-docs/update.rhai
  anda/groovy/update.rhai
Labels: bug, update

#188 fix(update): groovy groovy-docs
  anda/groovy/groovy-docs/update.rhai
  anda/groovy/update.rhai
Labels: bug, update

#191 fix(deps): nerd-fonts
  anda/fonts/nerd-fonts/nerd-fonts.spec
Labels: bug

#198 fix(dbgpkg): pop-launcher
  anda/rust/pop-launcher/pop-launcher.spec
Labels: bug

#199 fix: protobuf
  anda/python/protobuf/python3-protobuf.spec
Labels: bug

#200 fix(dbgpkg): pop-launcher
  anda/rust/pop-launcher/pop-launcher.spec
Labels: bug

#201 feat(gha): update workflow show full backtrace
  .github/workflows/update.yml
Labels: enhancement

#196 feat: add compiz9
  CODEOWNERS
  anda/desktops/compiz9/anda.hcl
  anda/desktops/compiz9/compiz9.spec
Labels: enhancement, new

#204 fix: gcm-core
  anda/tools/gcm-core/gcm-core.spec
Labels: bug

#206 fix: protobuf
  anda/python/protobuf/python3-protobuf.spec
Labels: bug, update

#207 fix: protobuf
  anda/python/protobuf/python3-protobuf.spec
Labels: bug

#208 fix: protobuf
  anda/python/protobuf/python3-protobuf.spec
Labels: bug

#213 add: oxipng
  anda/rust/oxipng/anda.hcl
  anda/rust/oxipng/rust-oxipng.spec
  anda/rust/oxipng/update.rhai
Labels: enhancement, new

#214 add: felix
  anda/rust/felix/anda.hcl
  anda/rust/felix/rust-felix.spec
  anda/rust/felix/update.rhai
Labels: enhancement, new

#215 add: bandwhich
  anda/rust/bandwhich/anda.hcl
  anda/rust/bandwhich/bandwhich-fix-metadata-auto.diff
  anda/rust/bandwhich/rust-bandwhich.spec
Labels: enhancement, new

#216 add: detox
  anda/rust/detox/anda.hcl
  anda/rust/detox/rust-detox.spec
  anda/rust/detox/update.rhai
Labels: enhancement, new

#217 add: kondo kondo-ui
  anda/rust/kondo-ui/anda.hcl
  anda/rust/kondo-ui/rust-kondo-ui.spec
  anda/rust/kondo-ui/update.rhai
  anda/rust/kondo/anda.hcl
  anda/rust/kondo/rust-kondo.spec
  anda/rust/kondo/update.rhai
Labels: enhancement, new

#218 fix: kondo-ui bandwhich
  anda/rust/bandwhich/rust-bandwhich.spec
  anda/rust/kondo-ui/rust-kondo-ui.spec
Labels: bug

#219 fix: kondo
  anda/rust/kondo/rust-kondo.spec
  anda/rust/kondo/update.rhai
Labels: bug

#220 fix(checks): kondo-ui
  anda/rust/kondo-ui/rust-kondo-ui.spec
Labels: bug

#221 fix(deps): kondo-ui
  anda/rust/kondo-ui/rust-kondo-ui.spec
Labels: bug

#223 add: 2048-rs
  anda/rust/2048-rs/anda.hcl
  anda/rust/2048-rs/rust-game-2048.spec
  anda/rust/2048-rs/update.rhai
Labels: enhancement, new

#222 fix(deps): kondo-ui
  anda/rust/kondo-ui/rust-kondo-ui.spec
Labels: bug

#232 add: marble-gtk
  anda/lib/marble-gtk/anda.hcl
  anda/lib/marble-gtk/marble-gtk.spec
  anda/lib/marble-gtk/update.rhai
Labels: enhancement

#233 fix: tectonic
  anda/apps/tectonic/anda.hcl
  anda/apps/tectonic/tectonic.spec
  anda/apps/tectonic/update.rhai
  anda/rust/tectonic/anda.hcl
  anda/rust/tectonic/rust-tectonic.spec
  anda/rust/tectonic/update.rhai
Labels: bug

#242 fix: starship
  anda/rust/starship/rust-starship.spec
  anda/rust/starship/starship-fix-metadata-auto.diff
  anda/rust/starship/update.rhai
Labels: bug

#244 fix(update): graalvm marble-gtk
  anda/lib/marble-gtk/marble-gtk.spec
  anda/tools/graalvm/update.rhai
Labels: bug, update
