Repository terrapkg/packages, pull requests merged in 2023-03, with the labels that each got.

#277 fix: hyperfine
  anda/rust/hyperfine/hyperfine-fix-metadata-auto.diff
  anda/rust/hyperfine/rust-hyperfine.spec
Labels: update

#294 fix: libappimage
  anda/lib/libappimage/libappimage.spec
  anda/lib/libappimage/update.rhai
  anda/lib/libappimage/update.rhai.bak
Labels: bug

#297 fix: marble-gtk
  anda/lib/marble-gtk/marble-gtk.spec
Labels: bug

#298 bump: libappimageupdate
  anda/lib/libappimageupdate/libappimageupdate.spec
Labels: bug, update

#289 fix: iosevka-fusion-fonts blackbox-terminal
  anda/fonts/iosevka-fusion/iosevka-fusion-fonts.spec
  anda/fonts/iosevka-fusion/iosevka-fusion.toml
  anda/others/blackbox-terminal/blackbox-terminal.spec
Labels: bug

#308 fix: lomiri-schema lomiri-url-dispatcher
  anda/lib/lomiri-url-dispatcher/lomiri-url-dispatcher.spec
  anda/lib/lomiri-url-dispatcher/update.rhai
  anda/others/lomiri-schemas/lomiri-schemas.spec
  anda/others/lomiri-schemas/update.rhai
Labels: bug

#313 feat: add suru-icon-theme
  anda/themes/suru-icon-theme/anda.hcl
  anda/themes/suru-icon-theme/suru-icon-theme.spec
Labels: enhancement, new

#309 feat(update): automatic update scripts
  anda/lib/apparmor/update.rhai
  anda/lib/cmake-extras/update.rhai
  anda/lib/dbus-test-runner/update.rhai
  anda/lib/frame/frame.spec
  anda/lib/frame/update.rhai
  anda/lib/geis/update.rhai
  anda/lib/geonames/update.rhai
  anda/lib/glewmx/update.rhai
  anda/lib/grail/grail.spec
  anda/lib/grail/update.rhai
  anda/lib/lomiri-app-launch/update.rhai
  anda/lib/lomiri-ui-toolkit/lomiri-ui-toolkit.spec
  anda/lib/lomiri-ui-toolkit/update.rhai
  anda/lib/nlohmann-json/update.rhai
  anda/others/click/update.rhai
  anda/others/gsettings-ubuntu-touch-schemas/update.rhai
  anda/others/unity-greeter/unity-greeter.spec
  anda/others/unity-greeter/update.rhai
Labels: enhancement, update

#317 add: xdg-desktop-portal-pantheon
  anda/desktops/elementary/xdg-desktop-portal-pantheon/anda.hcl
  anda/desktops/elementary/xdg-desktop-portal-pantheon/update.rhai
  anda/desktops/elementary/xdg-desktop-portal-pantheon/xdg-desktop-portal-pantheon.spec
Labels: enhancement, new

#307 fix: bat-extras
  anda/rust/bat-extras/bat-extras.spec
Labels: bug

#320 fix(ci): sync
  .github/workflows/sync.yml
Labels: bug

#322 fix(files): libappimageupdate
  anda/lib/libappimageupdate/libappimageupdate.spec
Labels: bug

#321 fix(update): apparmor dbus-test-runner frame geis grail libappimage
  anda/lib/apparmor/update.rhai
  anda/lib/dbus-test-runner/update.rhai
  anda/lib/frame/update.rhai
  anda/lib/geis/update.rhai
  anda/lib/grail/update.rhai
  anda/lib/libappimage/update.rhai
Labels: bug, update

#331 feat: add lomiri-settings-components
  anda/lib/lomiri-settings-components/anda.hcl
  anda/lib/lomiri-settings-components/lomiri-settings-components.spec
Labels: enhancement, new

#306 fix: rust-sccache
  anda/rust/sccache/rust-sccache.spec
  anda/rust/sccache/sccache-fix-metadata-auto.diff
Labels: bug, help wanted
