Repository terrapkg/packages, pull requests merged in 2024-10, with the labels that each got.

#2120 fix: ruffle
  anda/apps/ruffle/ruffle-nightly.spec
Labels: bug, sync-f39, sync-f40, sync-f41

#2127 add: pet
  anda/tools/pet/anda.hcl
  anda/tools/pet/pet.spec
  anda/tools/pet/update.rhai
Labels: sync-f39, sync-f40, sync-frawhide, sync-f41, sync-el10

#2145 fix: mesa-freeworld
  anda/system/mesa-freeworld/mesa-freeworld.spec
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el10

#2143 fix: zed
  anda/devs/zed/stable/zed.spec
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el10

#2142 fix: zed-preview
  anda/devs/zed/preview/zed-preview.spec
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el10

#2139 fix: sccache
  anda/apps/sccache/sccache-fix-metadata-auto.diff
  anda/tools/buildsys/sccache/anda.hcl
  anda/tools/buildsys/sccache/rust-sccache.spec
  anda/tools/buildsys/sccache/sccache-0.8.2.crate
  anda/tools/buildsys/sccache/sccache-fix-metadata-auto.diff
  anda/tools/buildsys/sccache/update.rhai
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el10

#2140 bump: muon
  anda/tools/buildsys/muon/muon.spec
  anda/tools/buildsys/muon/update.rhai
Labels: update, sync-f39, sync-f40, sync-f41, sync-el10

#2138 fix: uxplay
  anda/misc/uxplay/uxplay.spec
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el10

#2137 fix: onefetch
  anda/langs/rust/onefetch/rust-onefetch.spec
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el10

#2141 fix: nushell
  anda/langs/rust/nushell/nushell.spec
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el10

#2185 moby-addons: do not hard-depend on Docker
  anda/docker/moby-buildx/moby-buildx.spec
  anda/docker/moby-compose/moby-compose.spec
Labels: sync-f39, sync-f40, sync-frawhide, sync-f41, sync-el10

#2194 fix(nim): actually copy dist folder to the goddamn %buildroot
  anda/langs/nim/nim-nightly/nim-nightly.spec
  anda/langs/nim/nim/nim.spec
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el10

#2198 fix(nim): symlink /usr/lib/nim/dist to %_datadir
  anda/langs/nim/nim-nightly/nim-nightly.spec
  anda/langs/nim/nim/nim.spec
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el10

#2202 Add: surface-dtx-daemon
  anda/system/surface-dtx-daemon/anda.hcl
  anda/system/surface-dtx-daemon/surface-dtx-daemon.spec
  anda/system/surface-dtx-daemon/update.rhai
Labels: sync-f39, sync-f40, sync-frawhide, sync-f41, sync-el10

#2235 Add swayfx package
  anda/desktops/swayfx/anda.hcl
  anda/desktops/swayfx/swayfx.spec
  anda/desktops/swayfx/update.rhai
Labels: new, sync-f39, sync-f40, sync-f41, sync-el10

#2232 add: x265
  anda/fusion/x265/anda.hcl
  anda/fusion/x265/update.rhai
  anda/fusion/x265/x265.spec
Labels: new

#2234 add: x264-bootstrap
  anda/fusion/x264-bootstrap/anda.hcl
  anda/fusion/x264-bootstrap/x264-bootstrap.spec
Labels: new

#2241 fix: gcm-core
  anda/tools/gcm-core/gcm-core.spec
Labels: sync-f39, sync-f40, sync-f41, sync-el10

#2251 add: opengamepadui
  anda/games/opengamepadui/anda.hcl
  anda/games/opengamepadui/opengamepadui.spec
  anda/games/opengamepadui/update.rhai
Labels: sync-f39, sync-f40, sync-frawhide, sync-f41

#2256 feat(armcord): rename to legcord
  anda/apps/armcord-bin/anda.hcl
  anda/apps/armcord-bin/armcord-bin.spec
  anda/apps/armcord-bin/update.rhai
  anda/apps/armcord/update.rhai
  anda/apps/legcord-bin/anda.hcl
  anda/apps/legcord-bin/legcord-bin.spec
  anda/apps/legcord-bin/legcord.png
  anda/apps/legcord-bin/update.rhai
  anda/apps/legcord/anda.hcl
  anda/apps/legcord/launch.sh
  anda/apps/legcord/legcord.spec
  anda/apps/legcord/update.rhai
Labels: sync-f39, sync-f40, sync-f41, sync-el10

#2257 fix: klassy
  anda/themes/klassy/klassy.spec
Labels: bug, update, sync-f39, sync-f40, sync-f41, sync-el10

#2258 add: inputplumber
  anda/games/inputplumber/anda.hcl
  anda/games/inputplumber/inputplumber.spec
  anda/games/inputplumber/update.rhai
Labels: new, sync-f39, sync-f40, sync-f41, sync-el10

#2259 add: joycond
  anda/games/joycond/anda.hcl
  anda/games/joycond/joycond.spec
  anda/games/joycond/update.rhai
Labels: new, sync-f39, sync-f40, sync-f41, sync-el10

#2260 fix(x264-bootstrap): add x264 provides
  anda/fusion/x264-bootstrap/x264-bootstrap.spec
Labels: bug

#2261 add: mate-dock-applet
  anda/desktops/mate/dock-applet/anda.hcl
  anda/desktops/mate/dock-applet/mate-dock-applet.spec
  anda/desktops/mate/dock-applet/update.rhai
Labels: new, sync-f39, sync-f40, sync-f41, sync-el10

#2225 add: ffmpeg
  anda/fusion/ffmpeg/anda.hcl
  anda/fusion/ffmpeg/ffmpeg.spec
  anda/fusion/ffmpeg/update.rhai
Labels: new

#2286 add: faad2
  anda/fusion/faad2/anda.hcl
  anda/fusion/faad2/faad2.spec
  anda/fusion/faad2/update.rhai
Labels: new

#2287 fix: mate-dock-applet
  anda/desktops/mate/dock-applet/mate-dock-applet.spec
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el10

#2293 rebuild: terra-mesa
  anda/lib/mesa/terra-mesa.spec
Labels: sync-f39, sync-f40, sync-f41, sync-el10

#2296 Switch joycond to git snapshot, pull in some patches
  anda/games/joycond/joycond.spec
  anda/games/joycond/update.rhai
Labels: sync-f39, sync-f40, sync-frawhide, sync-f41

#2294 fix: muon
  anda/tools/buildsys/muon/muon.spec
  anda/tools/buildsys/muon/update.rhai
Labels: bug, update, sync-f39, sync-f40, sync-f41, sync-el10

#2301 fix: stardust-flatland
  anda/stardust/flatland/stardust-flatland.spec
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el10

#2048 add: stardust-server
  anda/stardust/server/anda.hcl
  anda/stardust/server/stardust-server.spec
  anda/stardust/server/update.rhai
Labels: sync-f39, sync-f40, sync-f41, sync-el10

#2310 fix(update): stardust-server
  anda/stardust/server/stardust-server.spec
  anda/stardust/server/update.rhai
Labels: update, sync-f39, sync-f40, sync-f41, sync-el10

#2285 fix: prismlauncher
  anda/games/prismlauncher/prismlauncher.spec
Labels: sync-f39, sync-f40, sync-f41, sync-el10

#2319 add: stardust-telescope
  anda/stardust/server/stardust-server.spec
  anda/stardust/telescope/anda.hcl
  anda/stardust/telescope/stardust-telescope.spec
  anda/stardust/telescope/update.rhai
Labels: new, sync-f39, sync-f40, sync-f41, sync-el10

#2318 add: xwayland-satellite
  anda/langs/rust/xwayland-satellite/anda.hcl
  anda/langs/rust/xwayland-satellite/update.rhai
  anda/langs/rust/xwayland-satellite/xwayland-satellite.spec
Labels: new, sync-f39, sync-f40, sync-f41, sync-el10

#2329 fix: stardust-black-hole
  anda/stardust/black-hole/stardust-black-hole.spec
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el10

#2333 fix(update): stardust-telescope
  anda/stardust/telescope/anda.hcl
Labels: sync-f39, sync-f40, sync-f41, sync-el10

#2340 fix: gitoxide
  anda/langs/rust/gitoxide/rust-gitoxide.spec
Labels: bug, update, sync-f39, sync-f40, sync-f41, sync-el10

#2342 fix: typeracer
  anda/games/typeracer/rust-typeracer.spec
Labels: bug, update, sync-f39, sync-f40, sync-f41, sync-el10

#2343 fix: voicevox
  anda/apps/voicevox/voicevox.spec
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el10

#2339 fix: bandwhich
  anda/langs/rust/bandwhich/bandwhich-fix-metadata-auto.diff
Labels: bug, update, sync-f39, sync-f40, sync-f41, sync-el10

#2341 bump: rust-jellyfin-rpc-cli
  anda/langs/rust/jellyfin-rpc/rust-jellyfin-rpc-cli.spec
  anda/langs/rust/jellyfin-rpc/update.rhai
Labels: update, sync-f39, sync-f40, sync-f41, sync-el10

#2365 Update: telescope
  anda/stardust/telescope/stardust-telescope.spec
Labels: bug, enhancement, sync-f39, sync-f40, sync-frawhide, sync-f41, sync-el10

#2363 Fix: Protostar
  anda/stardust/protostar/stardust-protostar.spec
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el10

#2364 Fix: black-hole
  anda/stardust/black-hole/stardust-black-hole.spec
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el10

#2378 fix(update): stardust-protostar
  anda/stardust/protostar/update.rhai
Labels: bug, update, sync-f39, sync-f40, sync-f41, sync-el10

#2375 fix(yt-dlp): use new nightly versioning scheme
  anda/tools/yt-dlp/yt-dlp-nightly.spec
Labels: sync-f39, sync-f40, sync-f41, sync-el10

#2390 Fix: stardust package names and provides
  anda/stardust/armillary/stardust-armillary.spec
  anda/stardust/atmosphere/stardust-atmosphere.spec
  anda/stardust/black-hole/stardust-black-hole.spec
  anda/stardust/comet/stardust-comet.spec
  anda/stardust/flatland/stardust-flatland.spec
  anda/stardust/gravity/stardust-gravity.spec
  anda/stardust/magnetar/stardust-magnetar.spec
  anda/stardust/non-spatial-input/stardust-non-spatial-input.spec
  anda/stardust/protostar/stardust-protostar.spec
  anda/stardust/server/stardust-server.spec
  anda/stardust/telescope/stardust-telescope.spec
Labels: Improvement, sync-f39, sync-f40, sync-frawhide, sync-f41, sync-el10

#2391 Add: Stardust XR group
  comps.xml
Labels: Improvement, sync-f39, sync-f40, sync-frawhide, sync-f41, sync-el10

#2402 Fix: comps.xml I can't spell
  comps.xml
Labels: sync-f39, sync-f40, sync-frawhide, sync-f41, sync-el10

#2401 fix(stardust-telescope): stardust XR deps
  anda/stardust/telescope/stardust-telescope.spec
Labels: sync-f39, sync-f40, sync-frawhide, sync-f41, sync-el10

#2288 add: kmod-v4l2loopback
  anda/fusion/kmod-v4l2loopback/anda.hcl
  anda/fusion/kmod-v4l2loopback/kmod-v4l2loopback.spec
  anda/fusion/kmod-v4l2loopback/update.rhai
  anda/fusion/kmod-v4l2loopback/v4l2loopback-kmod.spec
Labels: new

#2233 add: x264
  anda/fusion/x264/anda.hcl
  anda/fusion/x264/x264.spec
Labels: new

#2414 docs(readme): add repology 41, remove 39
  README.md
Labels: documentation, sync-f41

#2135 fix: apparmor
  anda/lib/apparmor/apparmor.spec
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el10

#2420 fix: libusermetrics
  anda/lib/libusermetrics/libusermetrics.spec
Labels: sync-f39, sync-f40, sync-f41, sync-el10

#2416 add: umu-launcher
  anda/games/umu/anda.hcl
  anda/games/umu/umu-launcher.spec
  anda/games/umu/update.rhai
Labels: new, sync-f39, sync-f40, sync-f41, sync-el10

#2434 fix(update): apparmor
  anda/lib/apparmor/update.rhai
Labels: bug, update, sync-f39, sync-f40, sync-f41, sync-el10

#2400 feat(terra-release): add extra repo
  anda/terra/release/terra-extra.repo
  anda/terra/release/terra-release.spec
Labels: enhancement, sync-f41

#2418 add: crossystem
  anda/tools/crossystem/anda.hcl
  anda/tools/crossystem/crossystem.spec
  anda/tools/crossystem/disable-werror.patch
  anda/tools/crossystem/use-flashrom-cros.patch
Labels: new, sync-f39, sync-f40, sync-f41, sync-el10

#2417 add: flashrom-cros
  anda/tools/flashrom-cros/anda.hcl
  anda/tools/flashrom-cros/flashrom-cros.spec
Labels: new, sync-f40, sync-frawhide, sync-f41, sync-el10

#2419 add: msm-cros-efs-loader
  anda/system/msm-cros-efs-loader/anda.hcl
  anda/system/msm-cros-efs-loader/msm-cros-efs-loader.service
  anda/system/msm-cros-efs-loader/msm-cros-efs-loader.spec
Labels: new, sync-f40, sync-frawhide, sync-f41, sync-el10

#2452 fix: mesa-freeworld
  anda/system/mesa-freeworld/anda.hcl
  anda/system/mesa-freeworld/mesa-freeworld.spec
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el10
