Repository terrapkg/packages, pull requests merged in 2024-05, with the labels that each got.

#1153 fix(elementary-appcenter): add patch for appstream 1.0
  anda/desktops/elementary/appcenter/elementary-appcenter.spec
  anda/desktops/elementary/appcenter/pr2099.patch
Labels: sync-f40

#1155 fix(switchboard-plug-about): pull in various patches
  anda/desktops/elementary/switchboard-plug-about/switchboard-plug-about.spec
Labels: sync-f40

#1158 fix: make gala depend on libs with same epoch
  anda/desktops/elementary/gala/gala.spec
Labels: bug, sync-f38, sync-f39, sync-f40

#1172 chore(rebuild): libappimage
  anda/lib/libappimage/libappimage.spec
Labels: sync-f38, sync-f39, sync-f40

#1152 fix: nushell
  anda/langs/rust/nushell/nushell.spec
Labels: bug, update, sync-f38, sync-f40, sync-frawhide

#1167 fix(maturin): rust2rpm
  anda/langs/rust/maturin/rust-terra-maturin.spec
Labels: bug, update, sync-f38, sync-f39, sync-f40

#1175 fix: apparmor
  anda/lib/apparmor/apparmor.spec
Labels: bug, sync-f38, sync-f39, sync-f40

#1204 add: terra-sddm
  anda/desktops/sddm/0001-Delay-for-logind-and-fallback-to-seat0.patch
  anda/desktops/sddm/README.scripts
  anda/desktops/sddm/anda.hcl
  anda/desktops/sddm/sddm-0.18.0-environment_file.patch
  anda/desktops/sddm/sddm-0.20.0-fedora_config.patch
  anda/desktops/sddm/sddm-0.21.0-qt6greeter.patch
  anda/desktops/sddm/sddm-PR1876.patch
  anda/desktops/sddm/sddm-autologin.pam
  anda/desktops/sddm/sddm-greeter.pam
  anda/desktops/sddm/sddm-rpmostree-tmpfiles-hack.patch
  anda/desktops/sddm/sddm-systemd-sysusers.conf
  anda/desktops/sddm/sddm-x11.conf
  anda/desktops/sddm/sddm.conf
  anda/desktops/sddm/sddm.pam
  anda/desktops/sddm/sddm.sysconfig
  anda/desktops/sddm/terra-sddm.spec
  anda/desktops/sddm/update.rhai
Labels: new, sync-f38, sync-f39, sync-f40

#1203 add: openbangla-keyboard
  anda/misc/openbangla-keyboard/anda.hcl
  anda/misc/openbangla-keyboard/openbangla-keyboard-nightly.spec
  anda/misc/openbangla-keyboard/update.rhai
Labels: new, sync-f38, sync-f39, sync-f40

#1211 fix: vala-panel
  anda/langs/vala/vala-panel/vala-panel.spec
Labels: bug, update, sync-f38, sync-f39, sync-f40

#1216 fix: granite-7
  anda/desktops/elementary/granite-7/granite-7.spec
Labels: bug, update, sync-f38, sync-f39, sync-f40

#1220 fix: click
  anda/misc/click/click.spec
Labels: bug, update, sync-f38, sync-f39, sync-f40

#1170 fix: zsync2
  anda/lib/zsync2/update.rhai
  anda/lib/zsync2/zsync2.spec
Labels: bug, sync-f38, sync-f39, sync-frawhide

#1174 chore(rebuild): lomiri-url-dispatcher
  anda/desktops/lomiri-unity/lomiri-url-dispatcher/lomiri-url-dispatcher.spec
Labels: sync-f40

#1237 feat: use mirror network for Terra
  anda/terra/release/terra-release.spec
  anda/terra/release/terra.repo
Labels: sync-f40

#1240 fix: terra source mirror
  anda/terra/release/terra-release.spec
  anda/terra/release/terra.repo
Labels: bug, sync-f40

#1254 add: tuxclocker
  anda/apps/tuxclocker/anda.hcl
  anda/apps/tuxclocker/tuxclocker.spec
  anda/apps/tuxclocker/update.rhai
Labels: new, sync-f38, sync-f39, sync-f40

#1263 add: albius
  anda/langs/go/albius/albius.spec
  anda/langs/go/albius/anda.hcl
  anda/langs/go/albius/update.rhai
Labels: enhancement, new, sync-f38, sync-f39, sync-f40

#1252 fix: starship
  anda/langs/rust/starship/rust-starship.spec
  anda/langs/rust/starship/starship-fix-metadata-auto.diff
Labels: bug, update, sync-f38, sync-f39, sync-f40

#1270 add hard dependency on Qt 4 CLI tools
  anda/misc/kwin-system76-scheduler-integration/kwin-system76-scheduler-integration.spec
Labels: sync-f38, sync-f39, sync-f40, sync-frawhide

#1275 fix: kotlin-native
  anda/langs/kotlin/kotlin-native/kotlin-native.spec
Labels: bug, sync-f38, sync-f39, sync-f40

#1280 feat(comps): add `helium` group
  comps.xml
Labels: enhancement

#1285 fix: nim-nightly
  anda/langs/nim/nim-nightly/nim-nightly.spec
Labels: bug, sync-f38, sync-f39, sync-f40

#1303 add: mkfstab
  anda/langs/nim/mkfstab/anda.hcl
  anda/langs/nim/mkfstab/mkfstab.spec
  anda/langs/nim/mkfstab/update.rhai
Labels: new, sync-f38, sync-f39, sync-f40
