Repository terrapkg/packages, pull requests merged in 2024-06, with the labels that each got.

#1313 fix(update): lomiri-download-manager
  anda/desktops/lomiri-unity/lomiri-download-manager/lomiri-download-manager.spec
  anda/desktops/lomiri-unity/lomiri-download-manager/update.rhai
Labels: bug, update, sync-f38, sync-f39, sync-f40

#1311 fix: armcord
  anda/apps/armcord/armcord.spec
Labels: bug, sync-f38, sync-f39, sync-f40

#1314 fix: nushell
  anda/langs/rust/nushell/nushell.spec
Labels: bug, sync-f38, sync-f39, sync-f40

#1328 Add metainfo for xpadneo driver
  anda/system/xpadneo/io.github.xpadneo.metainfo.xml
  anda/system/xpadneo/xpadneo.spec
Labels: sync-f39, sync-f40, sync-frawhide

#1337 fix: pantheon-agent-polkit
  anda/desktops/elementary/pantheon-agent-polkit/pantheon-agent-polkit.spec
Labels: bug, sync-f39, sync-f40

#1302 add: umdive
  anda/langs/nim/dive/anda.hcl
  anda/langs/nim/dive/umdive.spec
  anda/langs/nim/dive/update.rhai
Labels: new, sync-f39, sync-f40

#1349 fix: elementary-photos
  anda/desktops/elementary/elementary-photos/elementary-photos.spec
Labels: bug, sync-f39, sync-f40

#1353 fix: don't delete lock file in cargo_prep_online
  anda/terra/srpm-macros/anda-srpm-macros.spec
  anda/terra/srpm-macros/macros.cargo_extra
Labels: bug, sync-f39, sync-f40

#1315 add: envision
  anda/apps/envision/anda.hcl
  anda/apps/envision/envision.spec
  anda/apps/envision/update.rhai
Labels: new, sync-f39, sync-f40

#1361 fix: elementary-shortcut-overlay
  anda/desktops/elementary/elementary-shortcut-overlay/elementary-shortcut-overlay.spec
Labels: bug, sync-f39, sync-f40

#1360 fix: elementary-capnet-assist
  anda/desktops/elementary/elementary-capnet-assist/elementary-capnet-assist.spec
Labels: bug, sync-f39, sync-f40

#1359 fix: vala-panel-appmenu
  anda/langs/vala/vala-panel-appmenu/vala-panel-appmenu.spec
Labels: bug, sync-f39, sync-f40

#1356 fix: prismlauncher-nightly
  anda/games/prismlauncher-nightly/prismlauncher-nightly.spec
Labels: bug, sync-f39, sync-f40

#1373 fix: albius
  anda/langs/go/albius/albius.spec
Labels: bug, sync-f39, sync-f40

#1376 [prismlauncher-nightly] Use system libs
  anda/games/prismlauncher-nightly/prismlauncher-nightly.spec
Labels: sync-f39, sync-f40

#1387 ci: if package is labelled as large, use lg runners for x86
  .github/workflows/autobuild.yml
Labels: sync-f39, sync-f40

#1386 fix(anki-qt5,libindicator): fix usage of %patch
  anda/apps/anki-qt5/anki-qt5.spec
  anda/langs/python/protobuf/python3-protobuf.spec
  anda/lib/libindicator/terra-libindicator.spec
Labels: bug, update, sync-f39, sync-f40

#1385 fix: openh264
  anda/lib/openh264/anda.hcl
  anda/lib/openh264/gst-p-bad-cleanup.sh
  anda/lib/openh264/hardcode-openh264-dep.patch
  anda/lib/openh264/openh264.spec
  anda/lib/openh264/pre.rhai
  anda/lib/openh264/update.rhai
Labels: bug, update, sync-f39, sync-f40

#1377 add: zed-nightly
  anda/devs/zed/nightly/anda.hcl
  anda/devs/zed/nightly/update.rhai
  anda/devs/zed/nightly/zed-nightly.spec
Labels: sync-f39, sync-frawhide

#1397 add zed-preview
  anda/devs/zed/preview/anda.hcl
  anda/devs/zed/preview/update.rhai
  anda/devs/zed/preview/zed-preview.spec
Labels: sync-f39, sync-f40

#1404 fix: gendesk
  anda/langs/go/gendesk/golang-github-xyproto-gendesk.spec
Labels: bug, sync-f39, sync-f40
