Repository terrapkg/packages, pull requests merged in 2024-11, with the labels that each got.

#2457 Add conf file to fix portals for SwayFX
  anda/desktops/swayfx/sway-portals.conf
  anda/desktops/swayfx/swayfx.spec
Labels: sync-f39, sync-f40, sync-f41

#2458 fix: update legcord provides excludes
  anda/apps/legcord-bin/legcord-bin.spec
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el10

#2464 fix(pop-shell): require GNOME 47
  anda/desktops/gnome/gnome-shell-extension-pop-shell/terra-gnome-shell-extension-pop-shell.spec
Labels: sync-f41

#2469 fix: zellij
  anda/langs/rust/zellij/rust-zellij.spec
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el10

#2468 fix: gtk4-layer-shell
  anda/lib/gtk4-layer-shell/gtk4-layer-shell.spec
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el10

#2466 fix: mpv
  anda/apps/mpv/mpv-nightly.spec
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el10

#2483 fix(katsu): buildrequires mold
  anda/tools/buildsys/katsu/katsu.spec
Labels: sync-f39, sync-f40, sync-f41, sync-el10

#2489 add: umu-wrapper
  anda/games/umu-wrapper/anda.hcl
  anda/games/umu-wrapper/rust-umu-wrapper.spec
  anda/games/umu-wrapper/update.rhai
Labels: sync-f39, sync-f40, sync-frawhide, sync-f41

#2499 Add: rpi-utils
  anda/tools/rpi-utils/anda.hcl
  anda/tools/rpi-utils/rpi-utils.spec
  anda/tools/rpi-utils/update.rhai
Labels: sync-f39, sync-f40, sync-frawhide, sync-f41, sync-el10

#2498 Add: Polycrystal
  anda/system/polycrystal/anda.hcl
  anda/system/polycrystal/polycrystal.spec
  anda/system/polycrystal/update.rhai
Labels: sync-frawhide, sync-f41, sync-el10

#2512 Add: Legcord-nightly, and organize Legcord packages into folder
  anda/apps/legcord/legcord-bin/anda.hcl
  anda/apps/legcord/legcord-bin/legcord-bin.spec
  anda/apps/legcord/legcord-bin/legcord.png
  anda/apps/legcord/legcord-bin/update.rhai
  anda/apps/legcord/nightly/anda.hcl
  anda/apps/legcord/nightly/launch.sh
  anda/apps/legcord/nightly/legcord-nightly.spec
  anda/apps/legcord/nightly/update.rhai
  anda/apps/legcord/stable/anda.hcl
  anda/apps/legcord/stable/launch.sh
  anda/apps/legcord/stable/legcord.spec
  anda/apps/legcord/stable/update.rhai
Labels: enhancement, sync-f39, sync-f40, sync-frawhide, sync-f41, sync-el10

#2516 Fix: legcord-nightly date
  anda/apps/legcord/nightly/legcord-nightly.spec
Labels: sync-f39, sync-f40, sync-frawhide, sync-f41, sync-el10

#2535 fix(mesa-freeworld): better update script that tracks bodhi
  anda/system/mesa-freeworld/update.rhai
Labels: bug, sync-f40, sync-f41

#2520 fix: picotool
  anda/tools/picotool/picotool.spec
Labels: sync-f40, sync-f41, sync-el10

#2519 fix: legcord
  anda/apps/legcord/stable/legcord.spec
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el10
