Repository terrapkg/packages, pull requests merged in 2024-07, with the labels that each got.

#1411 fix: terra-libplacebo
  anda/lib/placebo/terra-libplacebo.spec
Labels: bug, sync-f39, sync-f40

#1410 add: codium-marketplace
  anda/devs/codium-marketplace/anda.hcl
  anda/devs/codium-marketplace/codium-marketplace.spec
Labels: enhancement, new, sync-f39, sync-f40

#1422 fix: codium-marketplace
  anda/devs/codium-marketplace/codium-marketplace.spec
Labels: bug, sync-f39, sync-f40

#1425 chore: update README.md
  README.md
Labels: documentation

#1419 Add custom builder option for manual build flow
  .github/workflows/build.yml
Labels: sync-f39, sync-f40, sync-frawhide

#1428 fix: submarine builds
  anda/system/submarine/submarine.spec
Labels: sync-f39, sync-frawhide

#1442 fix: specify bootstrap image for mock configs
  anda/terra/mock-configs/terra-mock-configs.spec
  anda/terra/mock-configs/terra.tpl
Labels: sync-f39, sync-f40

#1446 bump: submarine
  anda/system/submarine/submarine.spec
Labels: sync-f39, sync-f40, sync-frawhide

#1451 fix: submarine git pull
  anda/system/submarine/submarine.spec
Labels: sync-f39, sync-f40, sync-frawhide

#1455 fix: ruff
  anda/langs/python/ruff/python3-ruff.spec
Labels: bug, sync-f39, sync-f40

#1464 [rawhide] add: python3-pillow-heif
  anda/langs/python/pillow-heif/anda.hcl
  anda/langs/python/pillow-heif/python3-pillow-heif.spec
  anda/langs/python/pillow-heif/test.py
  anda/langs/python/pillow-heif/update.rhai
Labels: new, update

#1466 add: mugshot
  anda/apps/mugshot/anda.hcl
  anda/apps/mugshot/mugshot.spec
  anda/apps/mugshot/update.rhai
Labels: new, sync-f39, sync-f40

#1468 fix(update): authy lomiri-ui-toolkit zed-* manrope albius stellar
  anda/apps/authy/update.rhai.bak
  anda/desktops/lomiri-unity/lomiri-ui-toolkit/update.rhai
  anda/devs/zed/nightly/update.rhai
  anda/devs/zed/preview/update.rhai
  anda/fonts/manrope/update.rhai.bak
  anda/langs/go/albius/anda.hcl
  anda/langs/go/albius/update.rhai
  anda/tools/umstellar/update.rhai
Labels: bug, update, sync-f39, sync-f40

#1471 fix: switchboard-plug-tweaks
  anda/desktops/elementary/pantheon-tweaks/anda.hcl
  anda/desktops/elementary/pantheon-tweaks/pantheon-tweaks.spec
  anda/desktops/elementary/pantheon-tweaks/update.rhai
  anda/desktops/elementary/switchboard-plug-tweaks/switchboard-plug-tweaks.spec
Labels: bug, update, sync-f39, sync-f40

#1472 fix: apparmor
  anda/lib/apparmor/apparmor.spec
  anda/lib/apparmor/update.rhai
Labels: bug, update, sync-f39, sync-f40

#1412 fix: switchboard-plug-wacom
  anda/desktops/elementary/switchboard-plug-wacom/switchboard-plug-wacom.spec
Labels: bug, update, sync-f39, sync-f40

#1485 fix(update): zed-preview
  anda/devs/zed/preview/update.rhai
Labels: bug, update, sync-f39, sync-f40

#1488 fix(update): umstellar
  anda/tools/umstellar/update.rhai
Labels: bug, update

#1496 fix(envision): use better versioning
  anda/apps/envision/envision.spec
Labels: sync-f39, sync-f40

#1501 fix: nvidia-patch
  anda/system/nvidia-patch/anda.hcl
  anda/system/nvidia-patch/nvidia-patch.spec
Labels: bug, update, sync-f39, sync-f40

#1510 fix: avstplg
  anda/system/avstplg/avstplg.spec
Labels: bug, update, sync-f39, sync-f40

#1493 fix: nushell
  anda/langs/rust/nushell/nushell.spec
Labels: bug, update, sync-f39, sync-f40

#1499 fix: envision
  anda/apps/envision/envision.spec
Labels: bug, sync-f39, sync-f40

#1505 fix: anki-qt5
  anda/apps/anki-qt5/anki-qt5.spec
Labels: bug, update, sync-f39, sync-f40

#1350 fix: sccache
  anda/apps/sccache/rust-sccache.spec
  anda/apps/sccache/sccache-fix-metadata-auto.diff
Labels: bug, sync-f39, sync-f40

#1520 fix: oxipng
  anda/langs/rust/oxipng/oxipng-fix-metadata-auto.diff
  anda/langs/rust/oxipng/rust-oxipng.spec
Labels: bug, update, sync-f39, sync-f40

#1522 fix(update): crystal
  anda/langs/crystal/crystal/update.rhai
Labels: bug, update

#1521 fix: anki-bin
  anda/apps/anki-bin/anki-bin.spec
  anda/apps/anki-bin/update.rhai
Labels: bug, update, sync-f39, sync-f40

#1528 add: flow-control-nightly
  anda/devs/flow/anda.hcl
  anda/devs/flow/flow-control-nightly.spec
  anda/devs/flow/update.rhai
Labels: enhancement, new, sync-f39, sync-f40

#1533 fix: anda
  anda/tools/buildsys/anda/rust-anda.spec
Labels: bug, update

#1536 fix(update): crystal
  anda/langs/crystal/crystal/update.rhai
Labels: bug, update

#1537 feat(ci): add commit tracking to mg
  .github/workflows/autobuild.yml
  .github/workflows/build.yml
  .github/workflows/json-build.yml
  .github/workflows/mg.sh
Labels: sync-f39, sync-f40

#1123 add: terra-mesa
  anda/lib/terra-mesa/Mesa-MLAA-License-Clarification-Email.txt
  anda/lib/terra-mesa/anda.hcl
  anda/lib/terra-mesa/terra-mesa.spec
  anda/lib/terra-mesa/update.rhai
Labels: sync-f39, sync-f40, sync-frawhide

#1550 fix: nim
  anda/langs/nim/nim/nim.spec
Labels: bug, update

#1554 add: gamescope-session-steam
  anda/games/gamescope-session-steam/anda.hcl
  anda/games/gamescope-session-steam/gamescope-session-steam.spec
  anda/games/gamescope-session-steam/update.rhai
Labels: new, sync-f39, sync-f40

#1553 add: gamescope
  anda/games/gamescope/1231.patch
  anda/games/gamescope/anda.hcl
  anda/games/gamescope/chimeraos.patch
  anda/games/gamescope/deckhd.patch
  anda/games/gamescope/disable-steam-touch-click-atom.patch
  anda/games/gamescope/drm-Separate-BOE-and-SDC-OLED-Deck-panel-rates.patch
  anda/games/gamescope/revert-299bc34.patch
  anda/games/gamescope/stb.pc
  anda/games/gamescope/terra-gamescope.spec
  anda/games/gamescope/update.rhai
Labels: new, sync-f39, sync-f40

#1551 fix: elementary-terminal
  anda/desktops/elementary/elementary-terminal/elementary-terminal.spec
Labels: bug, update, sync-f39, sync-f40

#1555 add: gamescope-session
  anda/games/gamescope-session/anda.hcl
  anda/games/gamescope-session/gamescope-session.spec
  anda/games/gamescope-session/update.rhai
Labels: new, sync-f39, sync-f40

#1552 fix: nim
  anda/langs/nim/nim/nim.spec
Labels: bug, sync-f39, sync-f40

#1549 feat: multilib for x86
  .github/workflows/autobuild.yml
  anda/terra/mock-configs/terra-39-i386.cfg
  anda/terra/mock-configs/terra-40-i386.cfg
  anda/terra/mock-configs/terra-mock-configs.spec
  anda/terra/mock-configs/terra-rawhide-i386.cfg
Labels: sync-f39, sync-f40, sync-frawhide

#1577 fix: voicevox
  anda/apps/voicevox/0001-feat-add-repository-entry-in-package.json.patch
  anda/apps/voicevox/anda.hcl
  anda/apps/voicevox/update.rhai
  anda/apps/voicevox/voicevox.spec
Labels: bug

#1572 fix: kotlin-native
  anda/langs/kotlin/kotlin-native/kotlin-native.spec
Labels: bug, update, sync-f39, sync-f40

#1568 fix: terra-mesa provides
  anda/lib/terra-mesa/anda.hcl
  anda/lib/terra-mesa/terra-mesa.spec
Labels: sync-f39, sync-f40, sync-frawhide

#1583 [frawhide] fix: terra-mesa provides (#1568)
  anda/lib/terra-mesa/anda.hcl
  anda/lib/terra-mesa/terra-mesa.spec
Labels: Urgent

#1584 feat: require hydrogen icon theme
  anda/lib/libhelium/libhelium.spec
  anda/lib/libhelium/update.rhai
Labels: sync-f39, sync-f40, sync-frawhide

#1587 rm: terra-mesa
  anda/lib/terra-mesa/Mesa-MLAA-License-Clarification-Email.txt
  anda/lib/terra-mesa/anda.hcl
  anda/lib/terra-mesa/terra-mesa.spec
  anda/lib/terra-mesa/update.rhai
Labels: sync-f39, sync-f40

#1593 fix: gamescope package
  anda/games/gamescope/anda.hcl
  anda/games/gamescope/terra-gamescope.spec
Labels: sync-f39, sync-f40, sync-frawhide

#1599 feat: seperate mock configs
  .github/workflows/autobuild.yml
  .github/workflows/build.yml
  .github/workflows/json-build.yml
  anda/terra/mock-configs/terra-39-aarch64.cfg
  anda/terra/mock-configs/terra-39-i386.cfg
  anda/terra/mock-configs/terra-39-x86_64.cfg
  anda/terra/mock-configs/terra-40-aarch64.cfg
  anda/terra/mock-configs/terra-40-i386.cfg
  anda/terra/mock-configs/terra-40-x86_64.cfg
  anda/terra/mock-configs/terra-mock-configs.spec
  anda/terra/mock-configs/terra-rawhide-aarch64.cfg
  anda/terra/mock-configs/terra-rawhide-i386.cfg
  anda/terra/mock-configs/terra-rawhide-x86_64.cfg
  anda/terra/mock-configs/terra.tpl
  anda/terra/mock-configs/update.rhai
Labels: sync-f39, sync-f40

#1603 feat: enable counting
  anda/terra/release/terra-release.spec
  anda/terra/release/terra.repo
Labels: sync-f39, sync-f40

#1606 bump: mpv
  anda/apps/mpv/mpv-nightly.spec
  anda/apps/mpv/update.rhai
Labels: bug

#1621 fix(ci): mg.sh typo
  .github/workflows/mg.sh
Labels: bug, sync-f39, sync-f40

#1624 fix(ci): try $GITHUB_SHA instead
  .github/workflows/autobuild.yml
  .github/workflows/build.yml
  .github/workflows/json-build.yml
Labels: bug, sync-f39, sync-f40

#1628 fix(ci): fix commit param number in mg.sh
  .github/workflows/mg.sh
Labels: bug, sync-f39, sync-f40

#1631 fix: elementary-notifications
  anda/desktops/elementary/elementary-notifications/elementary-notifications.spec
Labels: bug, update, sync-f39, sync-f40

#1433 add: tracy
  anda/devs/tracy/anda.hcl
  anda/devs/tracy/tracy.spec
  anda/devs/tracy/update.rhai
Labels: new, sync-f40

#1627 fix: revert packages that requires openssl-devel-engine
  anda/devs/zed/nightly/zed-nightly.spec
  anda/devs/zed/preview/zed-preview.spec
  anda/devs/zed/stable/zed.spec
  anda/langs/rust/gitoxide/rust-gitoxide.spec
  anda/langs/rust/nushell/nushell.spec
  anda/tools/buildsys/anda/rust-anda.spec
Labels: bug

#1636 fix: elememtary-videos
  anda/desktops/elementary/elementary-videos/elementary-videos.spec
Labels: bug, update, sync-f39, sync-f40

#1634 fix: elementary-settings-daemon
  anda/desktops/elementary/elementary-settings-daemon/elementary-settings-daemon.spec
Labels: bug, update, sync-f39, sync-f40

#1641 fix: elementary-music
  anda/desktops/elementary/elementary-music/elementary-music.spec
Labels: bug, update, sync-f39, sync-f40

#1645 bump: osu-lazer nim-nightly yt-dlp
  anda/games/osu-lazer/osu-lazer.spec
  anda/langs/nim/nim-nightly/nim-nightly.spec
  anda/tools/yt-dlp/yt-dlp-nightly.spec
Labels: update

#1650 chore: remove opentabletdriver (duplicate)
  anda/misc/opentabletdriver/anda.hcl
  anda/misc/opentabletdriver/opentabletdriver.spec
  anda/misc/opentabletdriver/update.rhai
  anda/misc/opentabletdriver/v0.6.3.0.tar.gz
Labels: sync-f39, sync-f40, sync-f41

#1655 add tarballs to .gitignore
  .gitignore
Labels: sync-f39, sync-f40, sync-f41

#1644 bump: zed-nightly
  anda/devs/zed/nightly/zed-nightly.spec
Labels: update

#1646 fix: envision
  anda/apps/envision/envision.spec
Labels: bug, update, sync-f39, sync-f40

#1647 fix: rnote
  anda/langs/rust/rnote/rnote.spec
Labels: bug

#1659 bump: terra-mock-configs
  anda/terra/mock-configs/terra-mock-configs.spec
Labels: update, sync-f39, sync-f40, sync-f41

#1680 fix: switchboard-plug-power
  anda/desktops/elementary/switchboard-plug-power/switchboard-plug-power.spec
Labels: sync-f39, sync-f40, sync-f41, sync-el9

#1679 fix: switchboard-plug-notifications
  anda/desktops/elementary/switchboard-plug-notifications/switchboard-plug-notifications.spec
Labels: sync-f39, sync-f40, sync-f41, sync-el9

#1678 fix: switchboard-plug-mouse-touchpad
  anda/desktops/elementary/switchboard-plug-mouse-touchpad/switchboard-plug-mouse-touchpad.spec
Labels: sync-f39, sync-f40, sync-f41, sync-el9

#1677 fix: switchboard-plug-locale
  anda/desktops/elementary/switchboard-plug-locale/switchboard-plug-locale.spec
Labels: sync-f39, sync-f40, sync-f41, sync-el9

#1675 fix: switchboard-plug-applications
  anda/desktops/elementary/switchboard-plug-applications/switchboard-plug-applications.spec
Labels: sync-f39, sync-f40, sync-f41, sync-el9

#1674 fix: switchboard-plug-about
  anda/desktops/elementary/switchboard-plug-about/switchboard-plug-about.spec
Labels: sync-f39, sync-f40, sync-f41, sync-el9

#1676 fix: switchboard-plug-datetime
  anda/desktops/elementary/switchboard-plug-datetime/switchboard-plug-datetime.spec
Labels: sync-f39, sync-f40, sync-f41, sync-el9

#1673 fix: switchboard-plug-useraccounts
  anda/desktops/elementary/switchboard-plug-useraccounts/switchboard-plug-useraccounts.spec
Labels: sync-f39, sync-f40, sync-f41, sync-el9

#1672 fix: switchboard-plug-sound
  anda/desktops/elementary/switchboard-plug-sound/switchboard-plug-sound.spec
Labels: sync-f39, sync-f40, sync-f41, sync-el9

#1670 fix: switchboard-plug-parental-controls
  anda/desktops/elementary/switchboard-plug-parental-controls/switchboard-plug-parental-controls.spec
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el9

#1668 fix: switchboard-plug-keyboard
  anda/desktops/elementary/switchboard-plug-keyboard/switchboard-plug-keyboard.spec
Labels: sync-f39, sync-f40, sync-f41, sync-el9

#1669 fix: switchboard-plug-networking
  anda/desktops/elementary/switchboard-plug-networking/switchboard-plug-networking.spec
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el9

#1671 fix: switchboard-plug-sharing
  anda/desktops/elementary/switchboard-plug-sharing/switchboard-plug-sharing.spec
Labels: sync-f39, sync-f40, sync-f41, sync-el9

#1667 fix: envision
  anda/apps/envision/envision.spec
Labels: bug, sync-f39, sync-f41, sync-el9

#1741 fix(ci): json-build.yml mock configs
  .github/workflows/build.yml
  .github/workflows/json-build.yml
Labels: bug

#1743 fix: discord*
  anda/apps/discord-canary-openasar/discord-canary-openasar.spec
  anda/apps/discord-canary/discord-canary.spec
  anda/apps/discord-openasar/discord-openasar.spec
  anda/apps/discord-ptb-openasar/discord-ptb-openasar.spec
  anda/apps/discord-ptb/discord-ptb.spec
  anda/apps/discord/discord.spec
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el9

#1748 fix(ci): update.yml
  .github/workflows/update.yml
Labels: update

#1749 bump: anda
  anda/tools/buildsys/anda/rust-anda.spec
Labels: update, sync-f39, sync-f40, sync-f41, sync-el9

#1755 fix: gamescope-session
  anda/games/gamescope-session/gamescope-session.spec
Labels: bug, update

#1753 feat(zed-preview): include releases that are not pre-releases
  anda/devs/zed/preview/update.rhai
Labels: update

#1742 fix: starship
  anda/langs/rust/starship/rust-starship.spec
  anda/langs/rust/starship/starship-fix-metadata-auto.diff
Labels: sync-f39, sync-f40, sync-f41, sync-el9

#1764 feat(envision): update by nightly
  anda/apps/envision/anda.hcl
Labels: update, sync-f39, sync-f40, sync-f41, sync-el9

#1774 fix: switchboard-plug-security-privacy
  anda/desktops/elementary/switchboard-plug-security-privacy/switchboard-plug-security-privacy.spec
Labels: bug, update, sync-f39, sync-f40, sync-f41, sync-el9

#1769 feat(ruffle): add desktop file
  anda/apps/ruffle/ruffle-nightly.spec
Labels: sync-f39, sync-f40, sync-f41, sync-el9

#1775 Fix manual builds
  .github/workflows/build.yml
  .github/workflows/json-build.yml
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el9

#1786 fix: don't run zed tests by default
  anda/devs/zed/nightly/zed-nightly.spec
  anda/devs/zed/preview/zed-preview.spec
  anda/devs/zed/stable/zed.spec
Labels: sync-f39, sync-f40, sync-f41, sync-el9

#1787 fix: gamescope
  anda/games/gamescope/terra-gamescope.spec
Labels: bug, update, sync-f39, sync-f40, sync-f41, sync-el9

#1788 fix: sbctl
  anda/tools/sbctl/sbctl.spec
Labels: bug, update, sync-f39, sync-f40, sync-f41, sync-el9
