Repository terrapkg/packages, pull requests merged in 2024-12, with the labels that each got.

#2548 fix: oxipng
  anda/langs/rust/oxipng/oxipng-fix-metadata-auto.diff
  anda/langs/rust/oxipng/rust-oxipng.spec
Labels: sync-f40, sync-f41, sync-el10

#2552 add provides/conflicts for alsa-ucm-cros
  anda/misc/alsa-ucm-cros/alsa-ucm-cros.spec
Labels: sync-f39, sync-f40, sync-f41

#2557 Fix: msm-cros-efs-loader
  anda/system/msm-cros-efs-loader/msm-cros-efs-loader.service
  anda/system/msm-cros-efs-loader/msm-cros-efs-loader.spec
Labels: sync-f39, sync-f40, sync-frawhide, sync-f41, sync-el10

#2562 fix: maturin
  anda/langs/rust/maturin/rust-terra-maturin.spec
Labels: bug, sync-f40, sync-f41, sync-el10

#2563 add: rtaudio-nightly
  anda/multimedia/rtaudio/anda.hcl
  anda/multimedia/rtaudio/rtaudio-nightly.spec
  anda/multimedia/rtaudio/update.rhai
Labels: new, sync-f41

#2564 add: Carla-nightly
  anda/multimedia/carla/0001-carla_host_control-import-from-pyliblo3-if-available.patch
  anda/multimedia/carla/Carla-0001-fix-prototype.patch
  anda/multimedia/carla/Carla-2.5-libdir.patch
  anda/multimedia/carla/Carla-QT5_LINK_FLAGS-bad-rpath.patch
  anda/multimedia/carla/Carla-nightly.spec
  anda/multimedia/carla/Carla-single-libs-path.patch
  anda/multimedia/carla/anda.hcl
  anda/multimedia/carla/update.rhai
Labels: new, sync-f41

#2565 add: zsh-autocomplete
  anda/devs/zsh-autocomplete/anda.hcl
  anda/devs/zsh-autocomplete/update.rhai
  anda/devs/zsh-autocomplete/zsh-autocomplete.spec
Labels: new, sync-frawhide, sync-f41, sync-el10

#2529 feat(release): terra-extras repo file
  anda/terra/release/terra-extras.repo
  anda/terra/release/terra-release.spec
Labels: enhancement

#2578 fix: libplacebo
  anda/lib/placebo/anda.hcl
  anda/lib/placebo/terra-libplacebo.spec
Labels: bug

#2577 fix: mesa
  anda/lib/mesa/terra-mesa.spec
Labels: sync-f41

#2522 rm: terra-gnome-shell-extension-pop-shell
  anda/desktops/gnome/gnome-shell-extension-pop-shell/0001-Remove-schema-handling-from-transpile.sh.patch
  anda/desktops/gnome/gnome-shell-extension-pop-shell/50_org.gnome.desktop.wm.keybindings.pop-shell.gschema.override
  anda/desktops/gnome/gnome-shell-extension-pop-shell/50_org.gnome.mutter.pop-shell.gschema.override
  anda/desktops/gnome/gnome-shell-extension-pop-shell/50_org.gnome.mutter.wayland.pop-shell.gschema.override
  anda/desktops/gnome/gnome-shell-extension-pop-shell/50_org.gnome.settings-daemon.plugins.media-keys.pop-shell.gschema.override
  anda/desktops/gnome/gnome-shell-extension-pop-shell/50_org.gnome.shell.pop-shell.gschema.override
  anda/desktops/gnome/gnome-shell-extension-pop-shell/anda.hcl
  anda/desktops/gnome/gnome-shell-extension-pop-shell/terra-gnome-shell-extension-pop-shell.spec
  anda/desktops/gnome/gnome-shell-extension-pop-shell/update.rhai
Labels: sync-f41, sync-el10

#2456 fix: tdlib
  anda/lib/tdlib/tdlib-nightly.spec
Labels: bug, sync-f40, sync-f41, sync-el10

#2528 feat: rename terra-mesa to mesa because it's literally in terra-extras
  anda/lib/mesa/anda.hcl
  anda/lib/mesa/mesa.spec
Labels: sync-f41

#2590 fix: ruffle
  anda/apps/ruffle/desktop_file_patch.diff
  anda/apps/ruffle/rs.ruffle.Ruffle.desktop
  anda/apps/ruffle/ruffle-nightly.spec
Labels: bug, sync-f40, sync-f41, sync-el10

#2575 add: zrythm
  anda/multimedia/zrythm/anda.hcl
  anda/multimedia/zrythm/update.rhai
  anda/multimedia/zrythm/zrythm.spec
Labels: new, sync-f40, sync-f41, sync-el10

#2604 fix(anda): add dependencies
  anda/tools/buildsys/anda/rust-anda.spec
Labels: bug, sync-f40, sync-f41, sync-el10

#2612 fix(x265): bump properly
  anda/fusion/x265/update.rhai
  anda/fusion/x265/x265.spec
Labels: bug, update, sync-f41, sync-el10

#2613 fix(x265): include .so files properly
  anda/fusion/x265/x265.spec
Labels: sync-f41, sync-el10

#2616 fix: ffmpeg
  anda/fusion/ffmpeg/ffmpeg.spec
Labels: sync-f41, sync-el10

#2617 fix: manrope-fonts
  anda/fonts/manrope/manrope-fonts.spec
Labels: sync-f41, sync-el10

#2629 Add: spotx-bash
  anda/tools/spotx-bash/anda.hcl
  anda/tools/spotx-bash/spotx-bash.spec
  anda/tools/spotx-bash/update.rhai
Labels: sync-f39, sync-f40, sync-frawhide, sync-f41, sync-el10

#2628 add modulo feature to espanso-wayland
  anda/tools/espanso-wayland/espanso-wayland.spec
  anda/tools/espanso-x11/espanso-x11.spec
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el10

#2634 Add: rpi-update
  anda/tools/rpi-update/anda.hcl
  anda/tools/rpi-update/rpi-update.spec
  anda/tools/rpi-update/update.rhai
Labels: sync-f39, sync-f40, sync-frawhide, sync-f41, sync-el10

#2644 bump: espanso
  anda/tools/espanso-wayland/espanso-wayland.spec
  anda/tools/espanso-x11/espanso-x11.spec
Labels: update, sync-f39, sync-f40, sync-f41, sync-el10

#2655 fix: inputplumber
  anda/games/inputplumber/inputplumber.spec
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el10

#2650 fix: rpi-utils
  anda/tools/rpi-utils/dtoverlay-manpage.patch
  anda/tools/rpi-utils/rpi-utils.spec
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el10

#2652 fix(ci): decrease `anda update` verbosity
  .github/workflows/update-branch.yml
  .github/workflows/update-nightly.yml
  .github/workflows/update-weekly.yml
  .github/workflows/update.yml
Labels: sync-f39, sync-f40, sync-f41, sync-el10

#2663 fix: gping
  anda/langs/rust/gping/rust-gping.spec
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el10

#1400 add: ctwm (attempt 2)
  anda/desktops/ctwm/anda.hcl
  anda/desktops/ctwm/ctwm.desktop
  anda/desktops/ctwm/ctwm.spec
  anda/desktops/ctwm/update.rhai
Labels: new, sync-f39, sync-f40, sync-f41, sync-el10

#2675 add: clipse
  anda/desktops/waylands/clipse/anda.hcl
  anda/desktops/waylands/clipse/golang-github-savedra1-clipse.spec
  anda/desktops/waylands/clipse/update.rhai
Labels: new, sync-f39, sync-f40, sync-f41, sync-el10

#2676 add: cliphist
  anda/desktops/waylands/cliphist/anda.hcl
  anda/desktops/waylands/cliphist/golang-github-sentriz-cliphist.spec
  anda/desktops/waylands/cliphist/update.rhai
Labels: new, sync-f39, sync-f40, sync-f41, sync-el10

#2682 add: mpvpaper
  anda/desktops/waylands/mpvpaper/anda.hcl
  anda/desktops/waylands/mpvpaper/mpvpaper.spec
  anda/desktops/waylands/mpvpaper/update.rhai
Labels: new, sync-f39, sync-f40, sync-f41, sync-el10

#2679 add: wpaperd
  anda/desktops/waylands/wpaperd/anda.hcl
  anda/desktops/waylands/wpaperd/update.rhai
  anda/desktops/waylands/wpaperd/wpaperd.spec
Labels: new, sync-f39, sync-f40, sync-f41, sync-el10

#2709 fix(ci): use f41 builders
  .github/workflows/autobuild.yml
Labels: bug

#2711 Add: pbcli
  anda/misc/pbcli/anda.hcl
  anda/misc/pbcli/pbcli.spec
  anda/misc/pbcli/update.rhai
Labels: new, sync-f39, sync-f40, sync-f41, sync-el10

#2742 add: walker
  anda/desktops/waylands/walker/anda.hcl
  anda/desktops/waylands/walker/golang-github-abenz1267-walker.spec
  anda/desktops/waylands/walker/update.rhai
Labels: new, sync-f39, sync-f40, sync-f41, sync-el10

#2730 stop fontviewer from building every single commit
  anda/apps/fontviewer/update.rhai
Labels: sync-f40, sync-f41

#2753 Change to -Dvideo-codecs=all
  anda/lib/mesa/mesa.spec
Labels: sync-f39, sync-f40, sync-f41, sync-el10

#2752 Fix: systemd services
  anda/system/chromebook-usbc-fix/chromebook-usbc-fix.spec
  anda/system/cros-keyboard-map/cros-keyboard-map.spec
  anda/system/msm-cros-efs-loader/msm-cros-efs-loader.spec
  anda/system/surface-dtx-daemon/surface-dtx-daemon.spec
Labels: sync-f39, sync-f40, sync-frawhide, sync-f41, sync-el10

#2763 Add: arduino-fwuploader
  anda/tools/arduino-fwuploader/anda.hcl
  anda/tools/arduino-fwuploader/arduino-fwuploader.spec
  anda/tools/arduino-fwuploader/update.rhai
Labels: sync-f39, sync-f40, sync-frawhide, sync-f41, sync-el10

#2762 Add: arduino-langauge-server
  anda/tools/arduino-language-server/anda.hcl
  anda/tools/arduino-language-server/arduino-language-server.spec
  anda/tools/arduino-language-server/update.rhai
Labels: sync-f39, sync-f40, sync-frawhide, sync-f41, sync-el10

#2779 bump: libhelium to update tau-helium stylesheet
  anda/lib/libhelium/libhelium.spec
Labels: sync-f39, sync-f40, sync-f41, sync-el10

#2793 feat(ci)!: remove lint.yml
  .github/workflows/lint.yml
Labels: sync-f39, sync-f40, sync-f41, sync-el10

#2788 Add: GLFW Builds of Ghostty, Changes to Main Specs For Compatibility
  anda/devs/ghostty/nightly-glfw/anda.hcl
  anda/devs/ghostty/nightly-glfw/ghostty-glfw-nightly.spec
  anda/devs/ghostty/nightly-glfw/no-strip.diff
  anda/devs/ghostty/nightly-glfw/update.rhai
  anda/devs/ghostty/nightly/ghostty-nightly.spec
  anda/devs/ghostty/nightly/pkgconfig-libadwaita-1.diff
  anda/devs/ghostty/nightly/use-pkg-config.diff
  anda/devs/ghostty/stable-glfw/anda.hcl
  anda/devs/ghostty/stable-glfw/ghostty-glfw.spec
  anda/devs/ghostty/stable-glfw/no-strip.diff
  anda/devs/ghostty/stable-glfw/update.rhai
  anda/devs/ghostty/stable/ghostty.spec
  anda/devs/ghostty/stable/pkgconfig-libadwaita-1.diff
  anda/devs/ghostty/stable/use-pkg-config.diff
Labels: sync-f39, sync-f40, sync-f41, sync-el10

#2744 add: swww
  anda/desktops/waylands/swww/anda.hcl
  anda/desktops/waylands/swww/swww.spec
  anda/desktops/waylands/swww/update.rhai
Labels: new, sync-f39, sync-f40, sync-f41, sync-el10

#2734 add: lightdm-kde-greeter
  anda/desktops/kde/lightdm-kde-greeter/anda.hcl
  anda/desktops/kde/lightdm-kde-greeter/lightdm-kde-greeter.spec
  anda/desktops/kde/lightdm-kde-greeter/update.rhai
Labels: new, sync-f41, sync-el10

#2791 feat: rename golang packages to shorter names
  anda/desktops/waylands/cliphist/golang-github-sentriz-cliphist.spec
  anda/desktops/waylands/clipse/golang-github-savedra1-clipse.spec
  anda/desktops/waylands/walker/golang-github-abenz1267-walker.spec
Labels: sync-f39, sync-f40, sync-f41, sync-el10

#2740 fix(update): zrythm
  anda/multimedia/zrythm/update.rhai
Labels: bug, update, sync-f39, sync-f40, sync-f41, sync-el10

#2726 fix: mesa-freeworld
  anda/system/mesa-freeworld/mesa-freeworld.spec
Labels: sync-f41

#2721 feat(ffmpeg): track tesseract and x265 version per branch
  anda/fusion/ffmpeg/VERSION_tesseract.txt
  anda/fusion/ffmpeg/VERSION_x265.txt
  anda/fusion/ffmpeg/anda.hcl
  anda/fusion/ffmpeg/update.rhai
  anda/system/mesa-freeworld/update.rhai
  andax/bump_extras.rhai
Labels: bug, update, sync-f40, sync-f41, sync-el10

#2691 add: mise
  anda/tools/buildsys/mise/anda.hcl
  anda/tools/buildsys/mise/mise-fix-metadata-auto.diff
  anda/tools/buildsys/mise/rust-mise.spec
  anda/tools/buildsys/mise/update.rhai
Labels: new, sync-f39, sync-f40, sync-f41, sync-el10

#2731 fix(ci/{build,json-build}): support the extra label in anda.hcl
  .github/workflows/build.yml
  .github/workflows/json-build.yml
  andax/get_proj_label.rhai
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el10

#2802 Fix: Ghostty Follow packaging guidelines
  anda/devs/ghostty/stable/ghostty.spec
Labels: sync-f39, sync-f40, sync-f41, sync-el10

#2823 Revert "Add: GLFW Builds of Ghostty, Changes to Main Specs For Compatibility"
  anda/devs/ghostty/nightly-glfw/anda.hcl
  anda/devs/ghostty/nightly-glfw/ghostty-glfw-nightly.spec
  anda/devs/ghostty/nightly-glfw/no-strip.diff
  anda/devs/ghostty/nightly-glfw/update.rhai
  anda/devs/ghostty/nightly/ghostty-nightly.spec
  anda/devs/ghostty/nightly/pkgconfig-libadwaita-1.diff
  anda/devs/ghostty/nightly/use-pkg-config.diff
  anda/devs/ghostty/stable-glfw/anda.hcl
  anda/devs/ghostty/stable-glfw/ghostty-glfw.spec
  anda/devs/ghostty/stable-glfw/no-strip.diff
  anda/devs/ghostty/stable-glfw/update.rhai
  anda/devs/ghostty/stable/ghostty.spec
  anda/devs/ghostty/stable/pkgconfig-libadwaita-1.diff
  anda/devs/ghostty/stable/use-pkg-config.diff
Labels: sync-f39, sync-f40, sync-f41, sync-el10

#2792 feat(ci)!: switch to rpmbuild
  .github/workflows/autobuild.yml
  .github/workflows/bootstrap.yml
  .github/workflows/build.yml
  .github/workflows/json-build.yml
  anda/games/prismlauncher-nightly/ci_setup.rhai
  anda/games/prismlauncher/ci_setup.rhai
  andax/ci/extra_repos.rhai
Labels: enhancement, sync-f39, sync-f40, sync-f41, sync-el10

#2828 Fix: Several fixes and additions from now reverted PR
  anda/devs/ghostty/nightly/ghostty-nightly.spec
  anda/devs/ghostty/nightly/pkgconfig-libadwaita-1.diff
  anda/devs/ghostty/nightly/use-pkg-config.diff
  anda/devs/ghostty/stable/ghostty.spec
  anda/devs/ghostty/stable/pkgconfig-libadwaita-1.diff
  anda/devs/ghostty/stable/use-pkg-config.diff
Labels: sync-f39, sync-f40, sync-f41, sync-el10
