Repository terrapkg/packages, pull requests merged in 2024-09, with the labels that each got.

#2036 feat(ci): add support for terra extra
  .github/workflows/autobuild.yml
Labels: enhancement, sync-f41

#2035 fix: envision
  anda/apps/envision/envision.spec
Labels: sync-f39, sync-f40, sync-f41, sync-el9

#1917 add: coolercontrol
  anda/apps/coolercontrol/anda.hcl
  anda/apps/coolercontrol/coolercontrol.spec
  anda/apps/coolercontrol/update.rhai
Labels: new, sync-f39, sync-f40, sync-f41, sync-el9

#2058 Switch Helium and Hydrogen to proper naming
  anda/lib/libhelium/libhelium.spec
  anda/themes/helium-gtk-theme/anda.hcl
  anda/themes/helium-gtk-theme/helium-gtk-theme.spec
  anda/themes/helium-gtk-theme/update.rhai
  anda/themes/hydrogen-icon-theme/anda.hcl
  anda/themes/hydrogen-icon-theme/hydrogen-icon-theme.spec
  anda/themes/hydrogen-icon-theme/update.rhai
  comps.xml
Labels: sync-f39, sync-f40, sync-f41, sync-el9

#2054 fix: youki
  anda/langs/rust/youki/youki.spec
Labels: sync-f39, sync-f40, sync-f41, sync-el9

#2062 Add: stardust magnetar
  anda/stardust/magnetar/anda.hcl
  anda/stardust/magnetar/stardust-magnetar.spec
  anda/stardust/magnetar/update.rhai
Labels: sync-f39, sync-f40, sync-f41, sync-el9

#2056 Add: stardust protostar
  anda/stardust/protostar/anda.hcl
  anda/stardust/protostar/stardust-protostar.spec
  anda/stardust/protostar/update.rhai
Labels: sync-f39, sync-f40, sync-f41, sync-el9

#2061 add: stardust-atmosphere
  anda/stardust/atmosphere/anda.hcl
  anda/stardust/atmosphere/stardust-atmosphere.spec
  anda/stardust/atmosphere/update.rhai
Labels: sync-f39, sync-f40, sync-f41, sync-el9

#2050 add: stardust-armillary
  anda/stardust/armillary/anda.hcl
  anda/stardust/armillary/stardust-armillary.spec
  anda/stardust/armillary/update.rhai
Labels: sync-f39, sync-f40, sync-f41, sync-el9

#2052 add: stardust-black-hole
  anda/stardust/black-hole/anda.hcl
  anda/stardust/black-hole/stardust-black-hole.spec
  anda/stardust/black-hole/update.rhai
Labels: sync-f39, sync-f40, sync-f41, sync-el9

#2051 add: stardust-comet
  anda/stardust/comet/anda.hcl
  anda/stardust/comet/stardust-comet.spec
  anda/stardust/comet/update.rhai
Labels: sync-f39, sync-f40, sync-f41, sync-el9

#2063 add: stardust gravity
  anda/stardust/gravity/anda.hcl
  anda/stardust/gravity/stardust-gravity.spec
  anda/stardust/gravity/update.rhai
Labels: sync-f39, sync-f40, sync-f41, sync-el9

#2112 add: golang-github-zrepl
  anda/langs/go/zrepl/anda.hcl
  anda/langs/go/zrepl/golang-github-zrepl.spec
  anda/langs/go/zrepl/update.rhai
Labels: sync-f39, sync-f40, sync-f41

#2117 fix(update): discord*
  anda/apps/discord-canary-openasar/update.rhai
  anda/apps/discord-canary/update.rhai
  anda/apps/discord-openasar/update.rhai
  anda/apps/discord-ptb-openasar/update.rhai
  anda/apps/discord-ptb/update.rhai
  anda/apps/discord/update.rhai
Labels: update

#2118 fix(update): cbfstool
  anda/tools/cbfstool/update.rhai
Labels: update

#2119 add: terra-mesa
  anda/lib/mesa/Mesa-MLAA-License-Clarification-Email.txt
  anda/lib/mesa/anda.hcl
  anda/lib/mesa/terra-mesa.spec
  anda/lib/mesa/update.rhai
Labels: new

#2121 fix: mpv
  anda/apps/mpv/mpv-nightly.spec
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el10
