Repository terrapkg/packages, pull requests merged in 2024-04, with the labels that each got.

#1040 prismlauncher: move JREs to weak deps, add java 21 for snapshots
  anda/games/prismlauncher-nightly/prismlauncher-nightly.spec
  anda/games/prismlauncher-qt5-nightly/prismlauncher-qt5-nightly.spec
  anda/games/prismlauncher-qt5/prismlauncher-qt5.spec
  anda/games/prismlauncher/prismlauncher.spec
Labels: sync-f38, sync-f39, sync-f40

#1014 chore(ci): get rid of cache buildroot
  .github/workflows/autobuild.yml
Labels: sync-f38, sync-f40, sync-frawhide

#1049 fix(limine): use gz tarball
  anda/system/limine/limine.spec
Labels: sync-f38, sync-f39, sync-f40

#1066 fix: gendesk
  anda/langs/go/gendesk/golang-github-xyproto-gendesk.spec
Labels: sync-f39, sync-f40

#1074 Add lightly-qt6
  anda/themes/lightly-qt6/VER6.txt
  anda/themes/lightly-qt6/add-missing-files.patch
  anda/themes/lightly-qt6/anda.hcl
  anda/themes/lightly-qt6/lightly-qt6.spec
  anda/themes/lightly-qt6/update.rhai
Labels: enhancement, new, sync-f40

#1084 add: `wineasio`
  anda/system/wineasio/anda.hcl
  anda/system/wineasio/update.rhai
  anda/system/wineasio/wineasio.spec
Labels: sync-f38, sync-f39, sync-f40, sync-frawhide

#1075 add: pip-system-certs
  anda/langs/python/pip-system-certs/anda.hcl
  anda/langs/python/pip-system-certs/python-pip-system-certs.spec
  anda/langs/python/pip-system-certs/update.rhai
Labels: enhancement, new

#1048 chore: erase iosevka-fusion
  anda/fonts/iosevka-fusion/anda.hcl
  anda/fonts/iosevka-fusion/iosevka-fusion-fonts.spec
  anda/fonts/iosevka-fusion/iosevka-fusion.toml
  anda/fonts/iosevka-fusion/update.rhai
  anda/terra/obsolete/terra-obsolete.spec
Labels: bug

#1103 fix(kwin-system76-scheduler-integration): autoupdate + installation
  anda/misc/kwin-system76-scheduler-integration/kwin-system76-scheduler-integration.spec
  anda/misc/kwin-system76-scheduler-integration/update.rhai
Labels: bug

#1104 fix: arrpc
  anda/misc/arrpc/arrpc.spec
Labels: bug

#1082 fix(nim-nightly): fixed package name
  anda/langs/nim/nim-nightly/nim-nightly.spec
Labels: bug, sync-f38, sync-f39, sync-f40

#1116 fix: wingpanel
  anda/desktops/elementary/wingpanel/wingpanel.spec
Labels: bug

#1113 fix: espanso
  anda/tools/espanso-wayland/espanso-wayland.spec
  anda/tools/espanso-x11/espanso-x11.spec
Labels: bug

#1118 fix: gala
  anda/desktops/elementary/gala/gala.spec
Labels: bug

#1119 fix: elementary-greeter
  anda/desktops/elementary/elementary-greeter/elementary-greeter.spec
Labels: bug

#1121 fix: gala
  anda/desktops/elementary/gala/gala.spec
Labels: bug

#1132 fix: espanso
  anda/tools/espanso-wayland/espanso-wayland.spec
  anda/tools/espanso-x11/espanso-x11.spec
Labels: bug

#1131 fix: espanso
  anda/tools/espanso-wayland/espanso-wayland.spec
  anda/tools/espanso-x11/espanso-x11.spec
Labels: bug

#1130 fix: espanso
  anda/tools/espanso-wayland/espanso-wayland.spec
  anda/tools/espanso-x11/espanso-x11.spec
Labels: bug

#1133 chore(gala): bump epoch
  anda/desktops/elementary/gala/gala.spec
Labels: bug

#1137 fix(gala): devel requires correct package with epoch
  anda/desktops/elementary/gala/gala.spec
Labels: bug

#1144 chore(wingpanel): bump epoch to 1
  anda/desktops/elementary/wingpanel/wingpanel.spec
Labels: bug, sync-f38, sync-f39, sync-f40
