Repository terrapkg/packages, pull requests merged in 2024-02, with the labels that each got.

#905 fix: switchboard-plug-networking
  anda/desktops/elementary/switchboard-plug-networking/switchboard-plug-networking.spec
Labels: bug, update

#903 fix: bandwhich
  anda/langs/rust/bandwhich/bandwhich-fix-metadata-auto.diff
Labels: bug, update

#921 add: glow
  anda/langs/go/glow/anda.hcl
  anda/langs/go/glow/golang-github-charmbracelet-glow.spec
  anda/langs/go/glow/update.rhai
Labels: new

#923 add: terra-wl-clipboard
  anda/tools/wl-clipboard/anda.hcl
  anda/tools/wl-clipboard/terra-wl-clipboard.spec
  anda/tools/wl-clipboard/update.rhai
Labels: new

#848 add: mpv-nightly
  anda/apps/mpv/anda.hcl
  anda/apps/mpv/mpv-nightly.spec
  anda/apps/mpv/update.rhai
Labels: enhancement, new

#925 add: feishin
  anda/apps/feishin/anda.hcl
  anda/apps/feishin/feishin.spec
  anda/apps/feishin/update.rhai
Labels: new

#920 add: arrpc
  anda/misc/arrpc/anda.hcl
  anda/misc/arrpc/arrpc.service
  anda/misc/arrpc/arrpc.spec
  anda/misc/arrpc/update.rhai
Labels: new

#936 fix: nim
  anda/langs/nim/nim/nim.spec
Labels: bug

#944 fix(update): better commit versioning
  anda/apps/mpv/mpv-nightly.spec
  anda/apps/mpv/update.rhai
  anda/desktops/elementary/switchboard-plug-wallet/switchboard-plug-wallet.spec
  anda/desktops/elementary/switchboard-plug-wallet/update.rhai
  anda/desktops/gnome/gnome-shell-extension-pop-shell/terra-gnome-shell-extension-pop-shell.spec
  anda/desktops/gnome/gnome-shell-extension-pop-shell/update.rhai
  anda/desktops/lomiri-unity/lomiri-ui-toolkit/update.rhai
  anda/desktops/lomiri-unity/lomiri-url-dispatcher/update.rhai
  anda/desktops/lomiri-unity/lomiri/update.rhai
  anda/games/prismlauncher-nightly/update.rhai
  anda/games/prismlauncher-qt5-nightly/update.rhai
  anda/langs/nim/nim-nightly/nim-nightly.spec
  anda/langs/nim/nim-nightly/update.rhai
  anda/langs/vala/vala-language-server-nightly/update.rhai
  anda/langs/vala/vala-language-server-nightly/vala-language-server-nightly.spec
  anda/langs/vala/vala-lint-nightly/update.rhai
  anda/langs/vala/vala-lint-nightly/vala-lint-nightly.spec
  anda/langs/vala/vala-nightly/update.rhai
  anda/langs/vala/vala-nightly/vala-nightly.spec
  anda/lib/deviceinfo/update.rhai
  anda/lib/geonames/update.rhai
  anda/lib/openh264/update.rhai
  anda/lib/tdlib/tdlib-nightly.spec
  anda/lib/tdlib/update.rhai
  anda/misc/arrpc/update.rhai
  anda/misc/click/update.rhai
  anda/system/avstplg/avstplg.spec
  anda/system/avstplg/update.rhai
  anda/system/nvidia-patch/nvidia-patch.spec
  anda/system/nvidia-patch/update.rhai
  anda/tools/chromium-ectool/chromium-ectool.spec
Labels: enhancement, update

#938 fix: choosenim
  anda/langs/nim/choosenim/anda.hcl
  anda/langs/nim/choosenim/choosenim.spec
Labels: bug

#961 feat: add debuginfod urls to terra-release
  anda/terra/release/terra-release.spec
  anda/terra/release/terra.urls
Labels: enhancement
