Repository terrapkg/packages, pull requests merged in 2024-08, with the labels that each got.

#1800 fix: disable large runners for zed
  anda/devs/zed/nightly/anda.hcl
  anda/devs/zed/preview/anda.hcl
  anda/devs/zed/stable/anda.hcl
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el9

#1805 fix(zed*): add cargo clean to make for more disk space
  anda/devs/zed/nightly/zed-nightly.spec
  anda/devs/zed/preview/zed-preview.spec
  anda/devs/zed/stable/zed.spec
Labels: sync-f39, sync-f40, sync-f41, sync-el9

#1816 fix: update OpenTabletDriver to .NET 8
  anda/system/opentabletdriver/opentabletdriver.spec
  anda/system/opentabletdriver/update.rhai
Labels: sync-f39, sync-f40, sync-frawhide, sync-f41

#1815 bump: keyd
  anda/tools/keyd/keyd.spec
Labels: update, sync-f39, sync-f40, sync-f41, sync-el9

#1834 fix: ruffle
  anda/apps/ruffle/ruffle-nightly.spec
Labels: sync-f39, sync-f40, sync-f41, sync-el9

#1839 fix: keyd
  anda/tools/keyd/keyd.spec
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el9

#1841 fix: keyd (#1839)
  anda/tools/keyd/keyd.spec
Labels: bug

#1852 fix(opentabletdriver): update.rhai comment
  anda/system/opentabletdriver/update.rhai
Labels: bug, update

#1851 fix(codium): remove `--unity-launch` from .desktop
  anda/devs/codium/codium.spec
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el9

#1827 add: youtube-music
  anda/apps/youtube-music/anda.hcl
  anda/apps/youtube-music/update.rhai
  anda/apps/youtube-music/youtube-music.desktop
  anda/apps/youtube-music/youtube-music.spec
Labels: sync-f39, sync-f40, sync-frawhide, sync-f41, sync-el9

#1850 fix: voicevox
  anda/apps/voicevox/voicevox.spec
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el9

#1865 fix(voicevox): do not compress for cpio
  anda/apps/voicevox/voicevox.spec
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el9

#1871 add: lsp-dsp-lib
  anda/lib/lsp-dsp/anda.hcl
  anda/lib/lsp-dsp/liblsp-dsp.spec
  anda/lib/lsp-dsp/update.rhai
Labels: new, sync-f39, sync-f40, sync-f41, sync-el9

#1847 add: mesa-freeworld
  anda/system/mesa-freeworld/Mesa-MLAA-License-Clarification-Email.txt
  anda/system/mesa-freeworld/anda.hcl
  anda/system/mesa-freeworld/mesa-freeworld.spec
  anda/system/mesa-freeworld/org.mesa3d.vaapi.freeworld.metainfo.xml
  anda/system/mesa-freeworld/org.mesa3d.vdpau.freeworld.metainfo.xml
  anda/system/mesa-freeworld/update.rhai
Labels: sync-f39, sync-f40, sync-f41, sync-el9

#1878 fix: uxplay
  anda/misc/uxplay/uxplay.spec
Labels: bug, sync-f39, sync-f40, sync-f41, sync-el9

#1873 add: libaudec
  anda/lib/audec/anda.hcl
  anda/lib/audec/libaudec.patch
  anda/lib/audec/libaudec.spec
Labels: new, sync-f39, sync-f40, sync-f41, sync-el9

#1872 add: libbacktrace
  anda/lib/backtrace/anda.hcl
  anda/lib/backtrace/libbacktrace-nightly.spec
  anda/lib/backtrace/update.rhai
Labels: new, sync-f39, sync-f40, sync-f41, sync-el9

#1896 fix: armcord-bin
  anda/apps/armcord-bin/armcord-bin.spec
Labels: bug

#1895 fix: armcord
  anda/apps/armcord/armcord.spec
Labels: bug

#1912 add: gamescope-legacy
  anda/games/gamescope-legacy/0001-cstdint.patch
  anda/games/gamescope-legacy/anda.hcl
  anda/games/gamescope-legacy/gamescope-legacy.spec
  anda/games/gamescope-legacy/legacy-720p.patch
  anda/games/gamescope-legacy/stb.pc
  anda/games/gamescope-legacy/v2-0001-always-send-ctrl-1-2-to-steam-s-wayland-session.patch
Labels: sync-f39, sync-f40, sync-frawhide, sync-f41, sync-el9

#1908 add: extest
  anda/misc/extest/anda.hcl
  anda/misc/extest/override_steam_desktop_file.sh
  anda/misc/extest/rust-extest.spec
  anda/misc/extest/update.rhai
Labels: new, sync-f39, sync-f40, sync-frawhide, sync-f41, sync-el9

#1932 fix: mesa-freeworld
  anda/system/mesa-freeworld/mesa-freeworld.spec
Labels: bug, update, sync-f39, sync-f40, sync-f41, sync-el9

#1933 fix: elementary-camera
  anda/desktops/elementary/elementary-camera/elementary-camera.spec
Labels: bug, update, sync-f39, sync-f40, sync-f41, sync-el9

#1934 fix: kotlin-native
  anda/langs/kotlin/kotlin-native/kotlin-native.spec
Labels: bug, update, sync-f39, sync-f40, sync-f41, sync-el9

#1905 feat(srpm-macros): move sources outside of this repo
  anda/terra/srpm-macros/anda-srpm-macros.spec
  anda/terra/srpm-macros/macros.anda
  anda/terra/srpm-macros/macros.caching
  anda/terra/srpm-macros/macros.cargo_extra
  anda/terra/srpm-macros/macros.go_extra
  anda/terra/srpm-macros/macros.nim_extra
  anda/terra/srpm-macros/update.rhai
Labels: sync-f39, sync-f40, sync-f41, sync-el9

#1961 add: rust-bottom
  anda/langs/rust/bottom/anda.hcl
  anda/langs/rust/bottom/bottom-fix-metadata-auto.diff
  anda/langs/rust/bottom/rust-bottom.spec
  anda/langs/rust/bottom/update.rhai
Labels: new, sync-f39, sync-f40, sync-f41, sync-el9

#1967 otd: Build using .NET 8, but require .NET 6 at runtime
  anda/system/opentabletdriver/opentabletdriver.spec
Labels: sync-f39, sync-f40, sync-f41, sync-el9

#1976 mesa-freeworld: handle gallium files
  anda/system/mesa-freeworld/mesa-freeworld.spec
Labels: sync-f39, sync-frawhide, sync-f41

#1966 fix: katsu
  anda/tools/buildsys/katsu/katsu.spec
Labels: sync-f39, sync-f40, sync-f41, sync-el9

#1955 fix: bandwhich
  anda/langs/rust/bandwhich/bandwhich-fix-metadata-auto.diff
  anda/langs/rust/bandwhich/rust-bandwhich.spec
Labels: bug, update, sync-f39, sync-f40, sync-f41, sync-el9

#1958 fix: cros-keyboard-map
  anda/system/cros-keyboard-map/cros-keyboard-map.spec
  anda/system/cros-keyboard-map/update.rhai
Labels: sync-f39, sync-f40, sync-f41

#1989 fix version formatting for cros-keyboard-map
  anda/system/cros-keyboard-map/cros-keyboard-map.spec
  anda/system/cros-keyboard-map/update.rhai
Labels: sync-f39, sync-f40

#1996 fix: armcord
  anda/apps/armcord/armcord.spec
Labels: sync-f39, sync-f40, sync-f41, sync-el9

#1995 fix: armcord-bin
  anda/apps/armcord-bin/armcord-bin.spec
Labels: sync-f39, sync-f40, sync-f41, sync-el9

#1997 Add cbfstool
  anda/tools/cbfstool/anda.hcl
  anda/tools/cbfstool/cbfstool.spec
  anda/tools/cbfstool/update.rhai
Labels: sync-f39, sync-f40, sync-frawhide, sync-f41, sync-el9

#2011 fix: gnome-shell-extension-appmenu-is-back
  anda/desktops/gnome/gnome-shell-extension-appmenu-is-back/gnome-shell-extension-appmenu-is-back.spec
Labels: sync-f41

#2014 fix: allow it to require gnome-shell 47
  anda/desktops/gnome/gnome-shell-extension-appmenu-is-back/gnome-shell-extension-appmenu-is-back.spec
Labels: sync-f41

#2018 bump: process-cpp
  anda/lib/process-cpp/process-cpp.spec
Labels: sync-f39, sync-f40, sync-f41, sync-el9

#2019 fix: tracy
  anda/devs/tracy/tracy.spec
Labels: sync-f39, sync-f40, sync-f41, sync-el9
