Repository terrapkg/packages, pull requests merged in 2025-06, with the labels that each got.

#5195 chore: Bump readymade-git and RPCS3 on <= 42
  anda/games/rpcs3/rpcs3.spec
  anda/system/readymade/git/readymade-git.spec
Labels: sync-f40, sync-f41, sync-el10

#5196 fix(rpcs3): yaml-cpp is also vendored
  anda/games/rpcs3/rpcs3.spec
  anda/games/rpcs3/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#4084 fix(ghostty-nightly): Rely on ncurses for terminfo and fix for Zig 0.14.0/>= 42 changes
  anda/devs/ghostty/nightly/ghostty-nightly.spec
Labels: sync-frawhide, sync-f41, sync-el10

#5214 chore: Bump packages on <= 42
  anda/games/rpcs3/rpcs3.spec
  anda/langs/zig/bootstrap/zig-master-bootstrap.spec
  anda/tools/yt-dlp/yt-dlp-git.spec
Labels: sync-f41, sync-el10, sync-f42

#5218 chore: Add ifconds to Zed build deps for better EL compatibility
  anda/devs/zed/nightly/zed-nightly.spec
  anda/devs/zed/preview/zed-preview.spec
  anda/devs/zed/stable/zed.spec
Labels: sync-f41, sync-el10, sync-f42

#5140 f42: Update to Mesa 25.1.1
  anda/lib/mesa/bazzite.patch
  anda/lib/mesa/mesa.spec
Labels: sync-f41, sync-el10, sync-f42

#5228 chore(heroic-games-launcher): Update for 2.17.1
  anda/games/heroic-games-launcher/heroic-games-launcher.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#5234 chore(woeusb-ng): Explicitly build dep on pyproject-rpm-macros
  anda/apps/woeusb-ng/WoeUSB-ng.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#5248 fix(woeusb-ng): I HATE Python
  anda/apps/woeusb-ng/WoeUSB-ng.spec
  anda/apps/woeusb-ng/anda.hcl
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#5260 fix(umstellar): Self provides weirdness
  anda/tools/umstellar/umstellar.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#5265 add: intel-lpmd
  anda/system/intel-lpmd/anda.hcl
  anda/system/intel-lpmd/intel-lpmd.spec
  anda/system/intel-lpmd/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#5277 fix: lovely-injector
  anda/lib/lovely-injector/lovely-injector.spec
Labels: sync-f41, sync-el10, sync-f42

#5286 fix?(legcord): Use Mock
  anda/apps/legcord/nightly/anda.hcl
  anda/apps/legcord/stable/anda.hcl
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#5292 add: libcufile and libcusolver
  anda/lib/nvidia/libcufile/anda.hcl
  anda/lib/nvidia/libcufile/cufile.pc
  anda/lib/nvidia/libcufile/libcufile.spec
  anda/lib/nvidia/libcufile/update.rhai
  anda/lib/nvidia/libcusolver/anda.hcl
  anda/lib/nvidia/libcusolver/cusolver.pc
  anda/lib/nvidia/libcusolver/libcusolver.spec
  anda/lib/nvidia/libcusolver/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#5296 chore: Bump out of sync packages
  anda/games/heroic-games-launcher/heroic-games-launcher.spec
  anda/system/readymade/git/readymade-git.spec
Labels: sync-f41, sync-el10

#5287 add: dracut-strip-trigger
  anda/system/dracut-strip-trigger/LICENSE
  anda/system/dracut-strip-trigger/anda.hcl
  anda/system/dracut-strip-trigger/dracut-strip-trigger.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#5307 chore: Bump lomiri-system-settings on <= 42
  anda/desktops/lomiri-unity/lomiri-system-settings/lomiri-system-settings.spec
Labels: sync-f41, sync-el10

#5310 Remove: flashrom-cros
  anda/tools/flashrom-cros/anda.hcl
  anda/tools/flashrom-cros/flashrom-cros.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#5327 fix(anda): The path solver cannot be used for deps
  anda/tools/buildsys/anda/rust-anda.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#5325 fix(readymade-git): update deps and git clone
  anda/system/readymade/git/readymade-git.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#5336 fix(anda): More things Fedora changed on 42
  anda/tools/buildsys/anda/rust-anda.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#5349 feat(anda-srpm-macros): include required scripts
  anda/terra/srpm-macros/anda-srpm-macros.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#5352 add: logiops
  anda/system/logiops/anda.hcl
  anda/system/logiops/logiops.spec
  anda/system/logiops/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#5351 fix: feishin
  anda/apps/feishin/feishin.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#5369 chore(anda-srpm-macros): Add Zig macro file
  anda/terra/srpm-macros/anda-srpm-macros.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#5377 fix: anda-srpm-macros
  anda/terra/srpm-macros/anda-srpm-macros.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#5370 add: hyprwayland-scanner.nightly
  anda/desktops/waylands/hyprwayland-scanner/anda.hcl
  anda/desktops/waylands/hyprwayland-scanner/hyprwayland-scanner.nightly.spec
  anda/desktops/waylands/hyprwayland-scanner/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#5384 add: hyprland-protocols.nightly
  anda/desktops/waylands/hyprland-protocols/anda.hcl
  anda/desktops/waylands/hyprland-protocols/hyprland-protocols.nightly.spec
  anda/desktops/waylands/hyprland-protocols/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#5386 fix(atac): try --locked
  anda/devs/atac/atac.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#5399 add: sdbus-cpp.terra
  anda/lib/sdbus-cpp/anda.hcl
  anda/lib/sdbus-cpp/sdbus-cpp.terra.spec
  anda/lib/sdbus-cpp/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#5408 fix(flashprog): update urls and license
  anda/tools/flashprog/flashprog.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3960 add: nimble
  anda/langs/nim/nim-nightly/nim-nightly.spec
  anda/langs/nim/nimble/anda.hcl
  anda/langs/nim/nimble/nimble.1
  anda/langs/nim/nimble/nimble.spec
  anda/langs/nim/nimble/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#5130 chore: Deprecate F40
  .backportrc.json
  .github/workflows/update-branch.yml
  .github/workflows/update-comps.yml
  .github/workflows/update-nightly.yml
  .github/workflows/update-weekly.yml
  .github/workflows/update.yml
Labels: sync-f41, sync-el10, sync-f42

#1284 add: vpkedit
  anda/apps/vpkedit/anda.hcl
  anda/apps/vpkedit/update.rhai
  anda/apps/vpkedit/vpkedit.spec
Labels: new, sync-f40, sync-f41, sync-el10, sync-f42

#5378 add: hypridle
  anda/desktops/waylands/hypridle/anda.hcl
  anda/desktops/waylands/hypridle/hypridle.spec
  anda/desktops/waylands/hypridle/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#5341 docs(readme): add instructions for EL, notes for extras
  README.md
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#5453 fix(hypridle): trim the version correctly
  anda/desktops/waylands/hypridle/hypridle.spec
  anda/desktops/waylands/hypridle/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#5411 add: hyprlock
  anda/desktops/waylands/hyprlock/anda.hcl
  anda/desktops/waylands/hyprlock/hyprlock.spec
  anda/desktops/waylands/hyprlock/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3323 add: cbmem
  anda/tools/cbmem/anda.hcl
  anda/tools/cbmem/cbmem.spec
  anda/tools/cbmem/update.rhai
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42

#5464 fix(vpkedit): Don't disable static linking
  anda/apps/vpkedit/vpkedit.spec
Labels: sync-f41, sync-el10, sync-f42

#5465 fix(v4l2-relayd): Change to nightly so commit date is accurate
  anda/system/v4l2-relayd/anda.hcl
Labels: sync-f41, sync-el10, sync-f42

#5485 fix(sdbus-cpp): update.rhai
  anda/lib/sdbus-cpp/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#5413 add: opensnitch
  anda/apps/opensnitch/anda.hcl
  anda/apps/opensnitch/opensnitch.spec
  anda/apps/opensnitch/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#5509 fix(tdlib): set it to nightly
  anda/lib/tdlib/anda.hcl
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42

#5517 fix(zig-master): rebase linker patches
  anda/langs/zig/bootstrap/0005-link.Elf-add-root-directory-of-libraries-to-linker-p.patch
  anda/langs/zig/master/0005-link.Elf-add-root-directory-of-libraries-to-linker-p.patch
Labels: sync-f41, sync-el10, sync-f42

#5533 rm: onefetch
  anda/langs/rust/onefetch/anda.hcl
  anda/langs/rust/onefetch/onefetch-fix-metadata-auto.diff
  anda/langs/rust/onefetch/rust-onefetch.spec
  anda/langs/rust/onefetch/update.rhai
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42

#5538 fix(ffmpeg): see I'm blind
  anda/multimedia/ffmpeg/update.rhai
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42

#5537 add: terra-protontricks
  anda/apps/protontricks/anda.hcl
  anda/apps/protontricks/protontricks.spec
  anda/apps/protontricks/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#5550 fix(intel-lpmd): install files to the correct place
  anda/system/intel-lpmd/intel-lpmd.spec
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42

#5557 fix(ffmpeg): Add $ to update script
  anda/multimedia/ffmpeg/update.rhai
Labels: sync-frawhide, sync-f41, sync-f42

#5561 fix(LCEVEdev): files
  anda/multimedia/lcevcdec/LCEVCdec.spec
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42

#5579 feat(heroic, steam): Recommend falcond OR gamemode
  anda/games/heroic-games-launcher/heroic-games-launcher.spec
  anda/games/steam/steam.spec
Labels: sync-f41, sync-el10, sync-f42

#5584 chore: Update some more Python packages
  anda/desktops/lomiri-unity/unity-shell/unity-shell.spec
  anda/desktops/mate/tweak/mate-tweak.spec
Labels: sync-f41, sync-el10, sync-f42

#5592 fix(kf6-kio): Update for Rawhide and F42
  anda/desktops/kde/kf6-kio/anda.hcl
  anda/desktops/kde/kf6-kio/kf6-kio.spec
Labels: sync-f42

#5601 fix: Update mesa.spec with latest changes from upstream
  anda/lib/mesa/0001-Revert-kopper-Explicitly-choose-zink.patch
  anda/lib/mesa/bazzite.patch
  anda/lib/mesa/mesa.spec
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42

#5605 fix(carla): Update build deps
  anda/multimedia/carla/Carla-nightly.spec
Labels: sync-f41, sync-el10, sync-f42

#5604 fix(legcord-nightly): Disable stripping
  anda/apps/legcord/nightly/legcord-nightly.spec
Labels: sync-f41, sync-el10, sync-f42

#5613 fix(kanata): rust2rpm
  anda/tools/kanata/kanata-fix-metadata-auto.diff
Labels: sync-f41, sync-el10, sync-f42

#5635 add: virtualsmartcard
  anda/tools/virtualsmartcard/anda.hcl
  anda/tools/virtualsmartcard/update.rhai
  anda/tools/virtualsmartcard/virtualsmartcard.spec
Labels: sync-f41, sync-el10, sync-f42

#5644 Fix: virtualsmartcard license install
  anda/tools/virtualsmartcard/virtualsmartcard.spec
Labels: sync-f41, sync-el10, sync-f42

#5650 chore: Backport NVIDIA changes
  anda/lib/nvidia/compat-nvidia-repo/compat-nvidia-repo.spec
  anda/lib/nvidia/nv-codec-headers/nv-codec-headers.spec
  anda/system/nvidia/dkms-nvidia/closed/dkms-nvidia.spec
  anda/system/nvidia/dkms-nvidia/open/dkms-nvidia-open.spec
  anda/system/nvidia/nvidia-driver/nvidia-driver.spec
  anda/system/nvidia/nvidia-kmod-common/nvidia-kmod-common.spec
  anda/system/nvidia/nvidia-kmod/closed/nvidia-kmod.spec
  anda/system/nvidia/nvidia-kmod/open/nvidia-open-kmod.spec
  anda/system/nvidia/nvidia-modprobe/nvidia-modprobe.spec
  anda/system/nvidia/nvidia-persistenced/nvidia-persistenced.spec
  anda/system/nvidia/nvidia-settings/nvidia-settings.spec
  anda/system/nvidia/nvidia-xconfig/nvidia-xconfig.spec
Labels: nosync

#5653 add: deadbeef
  anda/multimedia/deadbeef/anda.hcl
  anda/multimedia/deadbeef/deadbeef.spec
  anda/multimedia/deadbeef/update.rhai
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42

#5655 fix(hyprutils): bump so ver
  anda/desktops/waylands/hyprutils/hyprutils.nightly.spec
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42

#5661 fix(deadbeef): Missing =
  anda/multimedia/deadbeef/deadbeef.spec
Labels: sync-f41, sync-el10, sync-f42

#5648 fix(nvidia): UX improvements
  anda/system/nvidia/dkms-nvidia/closed/dkms-nvidia.spec
  anda/system/nvidia/libva-nvidia-driver/libva-nvidia-driver.spec
  anda/system/nvidia/nvidia-driver/nvidia-driver.spec
  anda/system/nvidia/nvidia-kmod-common/10-nvidia-fallback.rules
  anda/system/nvidia/nvidia-kmod-common/nvidia-fallback.service
  anda/system/nvidia/nvidia-kmod-common/nvidia-kmod-common.spec
  anda/system/nvidia/nvidia-kmod-common/nvidia.conf
Labels: sync-f41, sync-el10, sync-f42

#5673 fix/feat(ghostty): Add new files in Tip, move files that depend on other packages to subpackages
  anda/devs/ghostty/nightly/ghostty-nightly.spec
  anda/devs/ghostty/stable/ghostty.spec
Labels: sync-f41, sync-el10, sync-f42

#5385 fix(chezmoi)?: try using latest go.sum/mod
  anda/langs/go/chezmoi/chezmoi.spec
Labels: sync-f41, sync-el10, sync-f42

#5659 add: lan-mouse
  anda/langs/rust/lan-mouse/anda.hcl
  anda/langs/rust/lan-mouse/lan-mouse.spec
  anda/langs/rust/lan-mouse/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#5686 chore: Bump lomiri-system-settings on <= 42
  anda/desktops/lomiri-unity/lomiri-system-settings/lomiri-system-settings.spec
Labels: sync-f41, sync-el10

#5690 chore: Bump nightly packages on <= 42
  anda/apps/mpv/mpv-nightly.spec
  anda/apps/ruffle/ruffle-nightly.spec
  anda/devs/ghostty/nightly/ghostty-nightly.spec
  anda/devs/zed/nightly/zed-nightly.spec
  anda/langs/nim/grabnim/grabnim.spec
  anda/lib/astal/astal/astal.spec
  anda/multimedia/carla/Carla-nightly.spec
  anda/system/scx-scheds/nightly/scx-scheds-nightly.spec
  anda/tools/spotx-bash/spotx-bash.spec
Labels: sync-f41, sync-el10

#5677 chore(scx-scheds): Add systemd post scripts just in case
  anda/system/scx-scheds/nightly/scx-scheds-nightly.spec
  anda/system/scx-scheds/stable/scx-scheds.spec
Labels: sync-frawhide, sync-f41, sync-el10

#5693 fix(carla): update.rhai
  anda/multimedia/carla/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#5674 add: GoofCord
  anda/apps/goofcord/nightly/anda.hcl
  anda/apps/goofcord/nightly/goofcord-nightly.spec
  anda/apps/goofcord/nightly/update.rhai
  anda/apps/goofcord/stable/anda.hcl
  anda/apps/goofcord/stable/goofcord.spec
  anda/apps/goofcord/stable/update.rhai
Labels: sync-frawhide, sync-f41, sync-el10

#5694 add: micro-default-editor
  anda/tools/micro-default-editor/anda.hcl
  anda/tools/micro-default-editor/micro-default-editor.spec
  anda/tools/micro-default-editor/update.rhai
Labels: sync-frawhide, sync-f41, sync-el10

#5710 fix?(micro-default-editor): Just dep on Micro
  anda/tools/micro-default-editor/micro-default-editor.spec
  anda/tools/micro-default-editor/update.rhai
Labels: sync-f41, sync-el10, sync-f42
