Repository terrapkg/packages, pull requests merged in 2025-05, with the labels that each got.

#4577 fix: nv-codec-headers update.rhai
  anda/lib/nvidia/nv-codec-headers/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#4578 chore: Bump yt-dlp on F40 and EL10
  anda/tools/yt-dlp/yt-dlp-git.spec
Labels: sync-el10

#4568 refactor(ruffle, heroic): Use desktop-file-utils to more safely edit .desktop files
  anda/apps/ruffle/ruffle-nightly.spec
  anda/games/heroic-games-launcher/heroic-games-launcher.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4580 bump: ruffle
  anda/apps/ruffle/ruffle-nightly.spec
Labels: sync-el10

#4579 chore: Remove kmod-nvidia from Fedora branches
  anda/system/nvidia/kmod-nvidia/anda.hcl
  anda/system/nvidia/kmod-nvidia/kmod-nvidia-ldflags.patch
  anda/system/nvidia/kmod-nvidia/kmod-nvidia-no-hostname-whoami.patch
  anda/system/nvidia/kmod-nvidia/kmod-nvidia.spec
  anda/system/nvidia/kmod-nvidia/nvidia-kernel-ccflags-y.patch
  anda/system/nvidia/kmod-nvidia/update.rhai
Labels: sync-f41, sync-f42

#4576 chore(steam): Make release number the same on all branches
  anda/games/steam/steam.spec
Labels: sync-el10, sync-f42

#4605 chore: Move NVIDIA tools to NVIDIA repo
  anda/tools/cuda-gcc/anda.hcl
  anda/tools/cuda-nvcc/anda.hcl
Labels: sync-f41, sync-el10, sync-f42

#4611 add: epsonscan2
  anda/apps/epsonscan2/anda.hcl
  anda/apps/epsonscan2/epsonscan2.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4625 chore: Remove Zig bootstrap
  anda/langs/zig/zig-master.spec
Labels: sync-f42

#4628 fix(ruffle-nightly): Use %cargo_build instead of %cargo_install
  anda/apps/ruffle/ruffle-nightly.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4626 chore: Rename readymade-nightly to readymade-git
  anda/system/readymade/git/anda.hcl
  anda/system/readymade/git/readymade-git.spec
  anda/system/readymade/git/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#4545 fix(rnote): rustflags_debuginfo 1
  anda/langs/rust/rnote/rnote.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4597 feat: zapret
  anda/misc/zapret/anda.hcl
  anda/misc/zapret/build-dont-strip.patch
  anda/misc/zapret/chore-move-to-different-dirs.patch
  anda/misc/zapret/zapret.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4551 fix(gstreamer1*): Update specs
  anda/multimedia/gstreamer1/gstreamer1-plugin-libav/gstreamer1-plugin-libav.spec
  anda/multimedia/gstreamer1/gstreamer1-plugins-bad/gstreamer1-plugins-bad.spec
  anda/multimedia/gstreamer1/gstreamer1-plugins-ugly/gstreamer1-plugins-ugly.spec
Labels: sync-el10, sync-f42

#3276 Add: GStreamer VA-API
  anda/multimedia/gstreamer1/gstreamer1-vaapi/anda.hcl
  anda/multimedia/gstreamer1/gstreamer1-vaapi/gstreamer1-vaapi.spec
  anda/multimedia/gstreamer1/gstreamer1-vaapi/update.rhai
Labels: sync-el10, sync-f42

#4662 feat(gstreamer1-plugins-bad): Provide and obsolete freeworld
  anda/multimedia/gstreamer1/gstreamer1-plugins-bad/gstreamer1-plugins-bad.spec
Labels: sync-el10, sync-f42

#4665 fix?(gstreamer1-plugins-bad): Fully obsolete freeworld
  anda/multimedia/gstreamer1/gstreamer1-plugins-bad/gstreamer1-plugins-bad.spec
Labels: sync-f42

#4644 chore(epsonscan2): Working CMake macro
  anda/system/epsonscan2/anda.hcl
  anda/system/epsonscan2/epsonscan2.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4652 feat: Split Zig package
  anda/langs/zig/bootstrap/0000-remove-native-lib-directories-from-rpath.patch
  anda/langs/zig/bootstrap/0001-increase-upper-bounds-of-main-zig-executable-to-9G.patch
  anda/langs/zig/bootstrap/0002-build-pass-zig-lib-dir-as-directory-instead-of-as-st.patch
  anda/langs/zig/bootstrap/anda.hcl
  anda/langs/zig/bootstrap/update.rhai
  anda/langs/zig/bootstrap/zig-master-bootstrap.spec
  anda/langs/zig/master/0000-remove-native-lib-directories-from-rpath.patch
  anda/langs/zig/master/0001-increase-upper-bounds-of-main-zig-executable-to-9G.patch
  anda/langs/zig/master/0002-build-pass-zig-lib-dir-as-directory-instead-of-as-st.patch
  anda/langs/zig/master/anda.hcl
  anda/langs/zig/master/update.rhai
  anda/langs/zig/master/zig-master.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4674 fix(zig-master): Normalize version
  anda/langs/zig/master/zig-master.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4672 fix(minecraft): allow other kwallets
  anda/games/minecraft-java/minecraft-java.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4682 fix(gstreamer1-vaapi): Properly track Bodhi
  anda/multimedia/gstreamer1/gstreamer1-vaapi/anda.hcl
  anda/multimedia/gstreamer1/gstreamer1-vaapi/update.rhai
Labels: sync-el10, sync-f42

#4681 add: ignis
  anda/langs/python/ignis/anda.hcl
  anda/langs/python/ignis/python-ignis.spec
  anda/langs/python/ignis/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4675 feat(rio): Doc package, use desktop-file-utils, cleanup
  anda/devs/rio/rio.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4683 add: flameshot-nightly
  anda/apps/flameshot/anda.hcl
  anda/apps/flameshot/flameshot-nightly.spec
  anda/apps/flameshot/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4708 fix(ignis): license LGPL-2.1-or-later
  anda/langs/python/ignis/python-ignis.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4715 fix?(gstreamer1-plugins-ugly): Self obsolete to obsolete Fusion
  anda/multimedia/gstreamer1/gstreamer1-plugins-ugly/gstreamer1-plugins-ugly.spec
Labels: sync-el10, sync-f42

#4722 chore: Move nvidia-patch to NVIDIA subrepo
  anda/system/nvidia-patch/anda.hcl
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4733 fix(readymade-git): lock cargo dependencies
  anda/system/readymade/git/readymade-git.spec
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10, sync-f42

#4720 feat(ci): better autoupdate commit messages
  .github/workflows/update-branch.yml
  .github/workflows/update-nightly.yml
  .github/workflows/update-weekly.yml
  .github/workflows/update.yml
  andax/ci/update_commit_message.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4741 fix(komikku): New file
  anda/apps/komikku/komikku.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4746 chore: Bump some out of sync packages on <= 42
  anda/apps/komikku/komikku.spec
  anda/tools/buildsys/mise/rust-mise.spec
  anda/tools/electron/electron.spec
Labels: sync-f40, sync-f41, sync-el10

#4750 chore(lcevdec): Update spec and drop old patches
  anda/multimedia/lcevcdec/LCEVCdec-cstdint.patch
  anda/multimedia/lcevcdec/LCEVCdec-docs.patch
  anda/multimedia/lcevcdec/LCEVCdec.spec
Labels: sync-el10, sync-f42

#4751 chore(libde265): Update spec
  anda/lib/libde265/libde265.spec
Labels: sync-f41, sync-el10, sync-f42

#4757 fix(libva-nvidia-driver): Ifcond for ix86
  anda/system/nvidia/libva-nvidia-driver/anda.hcl
  anda/system/nvidia/libva-nvidia-driver/libva-nvidia-driver.spec
Labels: sync-f41, sync-el10, sync-f42

#4758 fix: Bump LCEVCdec on <= 42
  anda/multimedia/lcevcdec/LCEVCdec.spec
Labels: sync-el10

#4765 chore: Bump vvenc, add update script
  anda/multimedia/vvenc/update.rhai
  anda/multimedia/vvenc/vvenc.spec
Labels: sync-el10, sync-f42

#4769 fix(zig): GCC is a runtime depdendency to determine system information
  anda/langs/zig/bootstrap/zig-master-bootstrap.spec
  anda/langs/zig/master/zig-master.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4772 add: shibuya
  anda/devs/shibuya/anda.hcl
  anda/devs/shibuya/python-shibuya.spec
  anda/devs/shibuya/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4770 fix(vvenc): Add upstreamed patches, disable x86 SIMD for now
  anda/multimedia/vvenc/vvenc.spec
Labels: sync-el10, sync-f42

#4771 add: sphinxcontrib-moderncmakedomain
  anda/langs/python/sphinxcontrib-moderncmakedomain/anda.hcl
  anda/langs/python/sphinxcontrib-moderncmakedomain/python-sphinxcontrib-moderncmakedomain.spec
  anda/langs/python/sphinxcontrib-moderncmakedomain/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4794 chore: Update Bazzite.patch for Mesa 25.1
  anda/lib/mesa/0001-Revert-kopper-Explicitly-choose-zink.patch
  anda/lib/mesa/bazzite.patch
  anda/lib/mesa/doom-dta.patch
  anda/lib/mesa/gnome-shell-glthread-disable.patch
  anda/lib/mesa/mesa.spec
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42

#4763 fix(mesa): Add back epochs, add compat package
  anda/lib/mesa-compat/Mesa-MLAA-License-Clarification-Email.txt
  anda/lib/mesa-compat/anda.hcl
  anda/lib/mesa-compat/bazzite.patch
  anda/lib/mesa-compat/mesa-compat.spec
  anda/lib/mesa/mesa.spec
Labels: sync-f41, sync-el10, sync-f42

#4768 fix(ffmpeg): Track vvenc-libs for rebuilds, workaround for GCC15 update
  anda/multimedia/ffmpeg/VERSION_vvenc.txt
  anda/multimedia/ffmpeg/ffmpeg.spec
  anda/multimedia/ffmpeg/update.rhai
Labels: sync-el10, sync-f42

#4803 feat: set Vendor for packages built on CI
  .github/workflows/autobuild.yml
  .github/workflows/bootstrap.yml
  .github/workflows/build.yml
  .github/workflows/json-build.yml
Labels: enhancement, sync-f40, sync-f41, sync-el10, sync-f42

#4788 add: fast-colorthief
  anda/langs/python/fast-colorthief/anda.hcl
  anda/langs/python/fast-colorthief/python-fast-colorthief.spec
  anda/langs/python/fast-colorthief/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4806 fix: FFmpeg update issues
  anda/lib/nvidia/libnpp/anda.hcl
  anda/multimedia/ffmpeg/ffmpeg.spec
Labels: sync-el10, sync-f42

#4789 fix(dkms-nvidia): Update dkms-nvidia.conf
  anda/system/nvidia/dkms-nvidia/dkms-nvidia.conf
  anda/system/nvidia/dkms-nvidia/dkms-nvidia.spec
Labels: sync-el10, sync-f42

#4815 add: steam_notif_daemon
  anda/games/steam-notif-daemon/anda.hcl
  anda/games/steam-notif-daemon/steam-notif-daemon.spec
  anda/games/steam-notif-daemon/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4816 chore: Update Python packages to the modern RPM Python build system
  anda/desktops/lomiri-unity/lomiri-ui-toolkit/lomiri-ui-toolkit.spec
  anda/devs/shibuya/python-shibuya.spec
  anda/langs/python/pillow-heif/python3-pillow-heif.spec
  anda/langs/python/protobuf/python3-protobuf.spec
  anda/langs/python/sphinxcontrib-moderncmakedomain/python-sphinxcontrib-moderncmakedomain.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4791 feat(nvidia*): Open and closed packages
  anda/system/nvidia/dkms-nvidia/closed/anda.hcl
  anda/system/nvidia/dkms-nvidia/closed/dkms-nvidia.conf
  anda/system/nvidia/dkms-nvidia/closed/dkms-nvidia.spec
  anda/system/nvidia/dkms-nvidia/closed/modules.conf
  anda/system/nvidia/dkms-nvidia/closed/nvidia-kernel-ccflags-y.patch
  anda/system/nvidia/dkms-nvidia/closed/update.rhai
  anda/system/nvidia/dkms-nvidia/open/anda.hcl
  anda/system/nvidia/dkms-nvidia/open/dkms-nvidia-open.conf
  anda/system/nvidia/dkms-nvidia/open/dkms-nvidia-open.spec
  anda/system/nvidia/dkms-nvidia/open/modules.conf
  anda/system/nvidia/dkms-nvidia/open/nvidia-kernel-ccflags-y.patch
  anda/system/nvidia/dkms-nvidia/open/update.rhai
  anda/system/nvidia/nvidia-kmod-common/MODULE_VARIANT.txt
  anda/system/nvidia/nvidia-kmod-common/nvidia-kmod-common.spec
  anda/system/nvidia/nvidia-kmod/closed/anda.hcl
  anda/system/nvidia/nvidia-kmod/closed/nvidia-kernel-ccflags-y.patch
  anda/system/nvidia/nvidia-kmod/closed/nvidia-kmod.spec
  anda/system/nvidia/nvidia-kmod/closed/update.rhai
  anda/system/nvidia/nvidia-kmod/nvidia-kmod.spec
  anda/system/nvidia/nvidia-kmod/open/anda.hcl
  anda/system/nvidia/nvidia-kmod/open/nvidia-kernel-ccflags-y.patch
  anda/system/nvidia/nvidia-kmod/open/nvidia-open-kmod.spec
  anda/system/nvidia/nvidia-kmod/open/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#4829 chore(sphinxcontrib-moderncmakedomain): Add explicit build dep on pyproject-rpm-macros
  anda/langs/python/sphinxcontrib-moderncmakedomain/python-sphinxcontrib-moderncmakedomain.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4830 chore(protobuf): Bump on <= 41
  anda/langs/python/protobuf/python3-protobuf.spec
Labels: sync-f40, sync-el10

#4838 fix(vvenc): Pull in upstreamed patches for i386 builds, re-enable X86 SIMD
  anda/multimedia/vvenc/vvenc.spec
Labels: sync-el10, sync-f42

#4843 chore: Bump packages on <= 41
  anda/apps/discord-canary-openasar/discord-canary-openasar.spec
  anda/apps/discord-canary/discord-canary.spec
  anda/desktops/lomiri-unity/lomiri-system-settings/lomiri-system-settings.spec
  anda/games/inputplumber/inputplumber.spec
  anda/langs/crystal/crystal/crystal.spec
  anda/langs/kotlin/kotlin-native/kotlin-native.spec
  anda/langs/kotlin/kotlin/kotlin.spec
  anda/lib/tdlib/tdlib-nightly.spec
Labels: sync-f40, sync-el10

#4839 chore: Rebuild FFmpeg
  anda/multimedia/ffmpeg/ffmpeg.spec
Labels: sync-el10, sync-f42

#4844 fix(lomiri-system-settings): Update patches
  anda/desktops/lomiri-unity/lomiri-system-settings/lomiri-system-settings.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4793 chore(zig): Backport so it stops breaking updates on <= F41
  anda/langs/zig/bootstrap/0000-remove-native-lib-directories-from-rpath.patch
  anda/langs/zig/bootstrap/0001-increase-upper-bounds-of-main-zig-executable-to-9G.patch
  anda/langs/zig/bootstrap/0002-build-pass-zig-lib-dir-as-directory-instead-of-as-st.patch
  anda/langs/zig/bootstrap/anda.hcl
  anda/langs/zig/bootstrap/update.rhai
  anda/langs/zig/bootstrap/zig-master-bootstrap.spec
  anda/langs/zig/master/0000-remove-native-lib-directories-from-rpath.patch
  anda/langs/zig/master/0001-increase-upper-bounds-of-main-zig-executable-to-9G.patch
  anda/langs/zig/master/0002-build-pass-zig-lib-dir-as-directory-instead-of-as-st.patch
  anda/langs/zig/master/anda.hcl
  anda/langs/zig/master/update.rhai
  anda/langs/zig/master/zig-master.spec
Labels: sync-f40, sync-el10

#4821 add: Modern Colorthief
  anda/tools/modern-colorthief/anda.hcl
  anda/tools/modern-colorthief/modern-colorthief.spec
  anda/tools/modern-colorthief/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4869 chore(zig): Bump so it actually stops causing update issues
  anda/langs/zig/bootstrap/zig-master-bootstrap.spec
  anda/langs/zig/master/zig-master.spec
Labels: sync-f40, sync-el10

#4840 chore: Update spec to automatically handle Dracut, following Negativo
  anda/system/nvidia/nvidia-kmod-common/nvidia-kmod-common.spec
Labels: sync-f41, sync-el10, sync-f42

#4870 fix(zig): Increase memory limit due to aarch64 memory needs
  anda/langs/zig/bootstrap/0001-increase-upper-bounds-of-main-zig-executable-to-10G.patch
  anda/langs/zig/bootstrap/zig-master-bootstrap.spec
  anda/langs/zig/master/0001-increase-upper-bounds-of-main-zig-executable-to-10G.patch
  anda/langs/zig/master/update.rhai
  anda/langs/zig/master/zig-master.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4878 chore: Add more patches for DOOM: The Dark Ages
  anda/lib/mesa/bazzite.patch
  anda/lib/mesa/mesa.spec
  anda/lib/mesa/sparse.patch
Labels: sync-frawhide, sync-f41

#4867 chore(modern-colorthief): pyproject-rpm-macros build dep
  anda/tools/modern-colorthief/modern-colorthief.spec
Labels: sync-f40, sync-f41, sync-f42

#4857 add: Terra WINE
  anda/apps/winetricks/git/anda.hcl
  anda/apps/winetricks/git/update.rhai
  anda/apps/winetricks/git/winetricks-git.spec
  anda/apps/winetricks/stable/anda.hcl
  anda/apps/winetricks/stable/update.rhai
  anda/apps/winetricks/stable/winetricks.spec
  anda/system/wine/dev/anda.hcl
  anda/system/wine/dev/update.rhai
  anda/system/wine/dev/wine-dev.spec
  anda/system/wine/dev/wine.keyring
  anda/system/wine/stable/anda.hcl
  anda/system/wine/stable/update.rhai
  anda/system/wine/stable/wine-stable.spec
  anda/system/wine/stable/wine.keyring
  anda/system/wine/staging/anda.hcl
  anda/system/wine/staging/update.rhai
  anda/system/wine/staging/wine-staging.spec
  anda/system/wine/staging/wine.keyring
Labels: sync-f41, sync-el10, sync-f42

#4893 fix: Zig versions again
  anda/langs/zig/bootstrap/0001-increase-upper-bounds-of-main-zig-executable-to-10G.patch
  anda/langs/zig/bootstrap/zig-master-bootstrap.spec
  anda/langs/zig/master/0001-increase-upper-bounds-of-main-zig-executable-to-10G.patch
  anda/langs/zig/master/update.rhai
  anda/langs/zig/master/zig-master.spec
Labels: sync-f40

#4884 feat(modern-colorthief): Enable tests
  anda/tools/modern-colorthief/modern-colorthief.spec
Labels: sync-f40, sync-f41, sync-el10

#4883 chore(.github/workflows/sync.yaml): Update to latest Action version
  .github/workflows/sync.yml
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4885 feat(modern-colorthief): Enable docs
  anda/tools/modern-colorthief/modern-colorthief.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4904 chore(wine): Switch Mesa repo to releasever on <= 42
  anda/system/wine/dev/anda.hcl
  anda/system/wine/stable/anda.hcl
  anda/system/wine/staging/anda.hcl
Labels: sync-f41, sync-el10

#4889 add: Terra WINE DXVK
  anda/system/wine-dxvk/anda.hcl
  anda/system/wine-dxvk/update.rhai
  anda/system/wine-dxvk/wine-dxvk.spec
Labels: sync-f41, sync-el10, sync-f42

#4917 chore(wine-dxvk): Switch Mesa repo to releasever on <= 42
  anda/system/wine-dxvk/anda.hcl
Labels: sync-f41, sync-el10

#4916 fix(ffmpeg): Move to Extras due to library deps
  anda/multimedia/ffmpeg/anda.hcl
Labels: sync-el10, sync-f42

#4724 fix????(gstreamer1-plugins-bad): Separate libs package
  anda/multimedia/gstreamer1/gstreamer1-plugins-bad/gstreamer1-plugins-bad.spec
Labels: sync-el10, sync-f42

#4918 fix: rpi-utils
  anda/tools/rpi-utils/rpi-utils.spec
Labels: sync-f41, sync-el10, sync-f42

#4930 fix(joshuto): Don't mangle shebangs
  anda/langs/rust/joshuto/rust-joshuto.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4936 chore(zig-master): Update patches
  anda/langs/zig/bootstrap/0001-increase-upper-bounds-of-main-zig-executable-to-10G.patch
  anda/langs/zig/master/0001-increase-upper-bounds-of-main-zig-executable-to-10G.patch
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4938 chore: Bump Mesa on <= 42
  anda/lib/mesa/mesa.spec
Labels: sync-f41, sync-el10, sync-f42

#4861 add: exquisite-linux-templates
  anda/misc/exquisite-linux-templates/anda.hcl
  anda/misc/exquisite-linux-templates/exquisite-linux-templates.spec
  anda/misc/exquisite-linux-templates/update.rhai
  andax/bump_extras.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4906 fix(wine-dev): Handle inconsistent updates
  anda/system/wine/dev/update.rhai
  anda/system/wine/dev/wine-dev.spec
Labels: sync-f41, sync-el10, sync-f42

#4937 fix?????: Bump epoch on GStreamer bad plugins
  anda/multimedia/gstreamer1/gstreamer1-plugins-bad/gstreamer1-plugins-bad.spec
Labels: sync-el10, sync-f42

#4923 feat: Make WINE dep on the compat package
  anda/system/wine/dev/wine-dev.spec
  anda/system/wine/stable/update.rhai
  anda/system/wine/stable/wine-stable.spec
  anda/system/wine/staging/update.rhai
  anda/system/wine/staging/wine-staging.spec
Labels: sync-f41, sync-el10, sync-f42

#4950 add: pbpctrl
  anda/langs/rust/pbpctrl/anda.hcl
  anda/langs/rust/pbpctrl/pbpctrl.spec
  anda/langs/rust/pbpctrl/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4970 add: Colorz
  anda/langs/python/colorz/anda.hcl
  anda/langs/python/colorz/python-colorz.spec
  anda/langs/python/colorz/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4968 add: Haishoku
  anda/langs/python/haishoku/anda.hcl
  anda/langs/python/haishoku/python-haishoku.spec
  anda/langs/python/haishoku/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4967 fix(inputplumber): Makefile patch, update files
  anda/games/inputplumber/inputplumber.spec
  anda/games/inputplumber/make-install-dont-build.patch
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4924 fix(wine-dxvk): Rewrite scriptlets, fix deps
  anda/system/wine-dxvk/wine-dxvk.spec
Labels: sync-f41, sync-el10, sync-f42

#4987 add: usage
  anda/langs/rust/usage/anda.hcl
  anda/langs/rust/usage/rust-usage-cli.spec
  anda/langs/rust/usage/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4988 fix(mise): include `usage` dep for completions subpkgs
  anda/tools/buildsys/mise/rust-mise.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4709 add: btdu
  anda/langs/d/btdu/anda.hcl
  anda/langs/d/btdu/btdu.spec
  anda/langs/d/btdu/update.rhai
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10, sync-f42

#5004 fix: do not run file triggers if installed on an atomic distro
  anda/tools/sbctl/sbctl.spec
Labels: bug, sync-f40, sync-f41, sync-el10, sync-f42

#3877 add: rpcs3
  anda/games/rpcs3/anda.hcl
  anda/games/rpcs3/rpcs3.spec
  anda/games/rpcs3/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#5027 fix(heroic-games-launcher): Electron builder needs NPM now
  anda/games/heroic-games-launcher/heroic-games-launcher.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#5032 fix(steam): Track beta branch
  anda/games/steam/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#5051 add: Colorthief
  anda/langs/python/colorthief/anda.hcl
  anda/langs/python/colorthief/python-colorthief.spec
  anda/langs/python/colorthief/update.rhai
Labels: sync-el10

#5052 add: bash-kernel
  anda/langs/python/bash-kernel/anda.hcl
  anda/langs/python/bash-kernel/python-bash-kernel.spec
  anda/langs/python/bash-kernel/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#5118 add: rtl8821cu driver
  anda/system/rtl8821cu/akmod/anda.hcl
  anda/system/rtl8821cu/akmod/rtl8821cu-kmod.spec
  anda/system/rtl8821cu/akmod/update.rhai
  anda/system/rtl8821cu/dkms/anda.hcl
  anda/system/rtl8821cu/dkms/dkms-rtl8821cu.spec
  anda/system/rtl8821cu/dkms/no-weak-modules.conf
  anda/system/rtl8821cu/dkms/update.rhai
  anda/system/rtl8821cu/kmod-common/anda.hcl
  anda/system/rtl8821cu/kmod-common/rtl8821cu-kmod-common.spec
  anda/system/rtl8821cu/kmod-common/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#4868 chore(terra-mock-configs): Update EL10 to non-dev
  anda/terra/mock-configs/terra-mock-configs.spec
Labels: sync-f40, sync-frawhide, sync-f41, sync-f42

#5127 fix(ci/json-build): invoke mock properly thanks gha
  .github/workflows/json-build.yml
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#5131 fix(anda): Ifcond to build on EL10
  anda/tools/buildsys/anda/rust-anda.spec
Labels: sync-f41, sync-el10, sync-f42

#5152 fix(wine-stable): Turn update variable into string
  anda/system/wine/stable/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#5151 fix(flameshot-nightly): Package libraries and development files
  anda/apps/flameshot/flameshot-nightly.spec
Labels: sync-f41, sync-el10, sync-f42

#5150 fix(wine-dxvk): Call rpm.changed() correctly
  anda/system/wine-dxvk/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#5142 fix(nvidia): Update for 575.57.08
  anda/system/nvidia/dkms-nvidia/closed/dkms-nvidia.spec
  anda/system/nvidia/dkms-nvidia/closed/nvidia-kernel-ccflags-y.patch
  anda/system/nvidia/dkms-nvidia/open/dkms-nvidia-open.spec
  anda/system/nvidia/dkms-nvidia/open/nvidia-kernel-ccflags-y.patch
  anda/system/nvidia/nvidia-driver/nvidia-driver.spec
  anda/system/nvidia/nvidia-kmod/closed/nvidia-kernel-ccflags-y.patch
  anda/system/nvidia/nvidia-kmod/closed/nvidia-kmod.spec
  anda/system/nvidia/nvidia-kmod/open/nvidia-kernel-ccflags-y.patch
  anda/system/nvidia/nvidia-kmod/open/nvidia-open-kmod.spec
Labels: sync-f41, sync-el10, sync-f42

#5165 fix(lovely-injector): Don't update a non-existant global
  anda/lib/lovely-injector/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#5148 fix(mesa): Track download page by description to always return the latest version
  anda/lib/mesa/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#5128 fix(ci/json-build): don't install build deps when mock
  .github/workflows/json-build.yml
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#5172 add: nautilus-open-any-terminal
  anda/desktops/gnome/nautilus-open-any-terminal/anda.hcl
  anda/desktops/gnome/nautilus-open-any-terminal/nautilus-open-any-terminal.spec
  anda/desktops/gnome/nautilus-open-any-terminal/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#5149 chore(rpcs3): Re-enable system cURL on Rawhide, try to enable more system libraries
  anda/games/rpcs3/rpcs3.spec
Labels: sync-f41, sync-el10, sync-f42

#5184 fix(rpcs3): pkgconfig(zlib) typo
  anda/games/rpcs3/rpcs3.spec
Labels: sync-f41, sync-el10, sync-f42

#5188 chore(nautilus-open-any-terminal): Ifconds to fix builds on <= 41
  anda/desktops/gnome/nautilus-open-any-terminal/nautilus-open-any-terminal.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42
