Repository terrapkg/packages, pull requests merged in 2025-07, with the labels that each got.

#5723 fix(zed-nightly): Build wants Rust nightly for now
  anda/devs/zed/nightly/zed-nightly.spec
Labels: sync-frawhide, sync-f41, sync-el10

#5746 fix(nvidia-driver): Deps
  anda/system/nvidia/nvidia-driver/nvidia-driver.spec
Labels: sync-frawhide, sync-f41, sync-el10

#5747 fix(deadbeef): revert "bump" smh rabo
  anda/multimedia/deadbeef/deadbeef.spec
  anda/multimedia/deadbeef/update.rhai.bak
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42

#5754 add: nodejs-backport
  anda/devs/backport/anda.hcl
  anda/devs/backport/nodejs-backport.spec
  anda/devs/backport/post.rhai
  anda/devs/backport/setup.sh
  anda/devs/backport/update.rhai
Labels: sync-frawhide, sync-f41, sync-el10

#5764 Add: flashrom-cros again, add devel subpackage and more needed files
  anda/tools/flashrom-cros/anda.hcl
  anda/tools/flashrom-cros/flashrom-cros.spec
Labels: sync-f41, sync-el10, sync-f42

#5765 Fix: gsctool
  anda/tools/gsctool/gsctool.spec
Labels: sync-f41, sync-el10, sync-f42

#5786 fix(nim,nim-nightly): provides and conflicts and files
  anda/langs/nim/nim-nightly/nim-nightly.spec
  anda/langs/nim/nim/nim.spec
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42

#5793 chore(anda-srpm-macros): Add new files
  anda/terra/srpm-macros/anda-srpm-macros.spec
Labels: sync-f41, sync-el10, sync-f42

#5798 fix(dracut-strip-trigger): support other kernels
  anda/system/dracut-strip-trigger/dracut-strip-trigger.spec
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42

#5809 fix(nekoray): pre script download extra module?
  anda/apps/nekoray/nekoray.spec
  anda/apps/nekoray/pre.sh
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42

#5808 bump(mwc): 0.1.3
  anda/desktops/mwc/mwc.spec
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42

#5803 bump(cbmem): 25.06
  anda/tools/cbmem/cbmem.spec
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42

#5822 bump: yt-dlp-git
  anda/tools/yt-dlp/yt-dlp-git.spec
Labels: nosync

#5824 set up halloy 2025.6
  anda/apps/halloy/halloy.spec
  anda/apps/halloy/update.rhai
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42

#5832 add: netto
  anda/langs/nim/netto/anda.hcl
  anda/langs/nim/netto/netto.spec
  anda/langs/nim/netto/update.rhai
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42

#5836 Revert "bump(branch): micro-default-editor"
  anda/tools/micro-default-editor/micro-default-editor.spec
Labels: sync-f41, sync-el10, sync-f42

#5843 fix(micro-default-editor): Only call DNF once for update script
  anda/tools/micro-default-editor/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#5637 add: spleen-fonts
  anda/fonts/spleen/anda.hcl
  anda/fonts/spleen/spleen-fonts.spec
  anda/fonts/spleen/update.rhai
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42

#5848 feat(netto): include assets
  anda/langs/nim/netto/netto.spec
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42

#5654 add: deadbeef-mpris2-plugin
  anda/multimedia/deadbeef-mpris2-plugin/anda.hcl
  anda/multimedia/deadbeef-mpris2-plugin/deadbeef-mpris2-plugin.spec
  anda/multimedia/deadbeef-mpris2-plugin/update.rhai
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42

#5873 fix: remove `espanso-path` from the list of crates of `espanso` app
  anda/tools/espanso-wayland/espanso-wayland.spec
  anda/tools/espanso-x11/espanso-x11.spec
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42

#5881 fix(zapret): update patches
  anda/misc/zapret/build-dont-strip.patch
  anda/misc/zapret/chore-move-to-different-dirs.patch
  anda/misc/zapret/zapret.spec
Labels: sync-f41, sync-el10, sync-f42

#5878 chore: Split Xone into stable and nightly packages
  anda/system/xone/akmod/update.rhai
  anda/system/xone/dkms/update.rhai
  anda/system/xone/nightly/akmod/anda.hcl
  anda/system/xone/nightly/akmod/update.rhai
  anda/system/xone/nightly/akmod/xone-nightly-kmod.spec
  anda/system/xone/nightly/dkms/anda.hcl
  anda/system/xone/nightly/dkms/dkms-xone-nightly.spec
  anda/system/xone/nightly/dkms/no-weak-modules.conf
  anda/system/xone/nightly/dkms/update.rhai
  anda/system/xone/nightly/kmod-common/anda.hcl
  anda/system/xone/nightly/kmod-common/modules.conf
  anda/system/xone/nightly/kmod-common/update.rhai
  anda/system/xone/nightly/kmod-common/xone-nightly.spec
  anda/system/xone/stable/akmod/anda.hcl
  anda/system/xone/stable/akmod/update.rhai
  anda/system/xone/stable/akmod/xone-kmod.spec
  anda/system/xone/stable/dkms/anda.hcl
  anda/system/xone/stable/dkms/dkms-xone.spec
  anda/system/xone/stable/dkms/no-weak-modules.conf
  anda/system/xone/stable/dkms/update.rhai
  anda/system/xone/stable/kmod-common/anda.hcl
  anda/system/xone/stable/kmod-common/modules.conf
  anda/system/xone/stable/kmod-common/update.rhai
  anda/system/xone/stable/kmod-common/xone.spec
Labels: sync-f41, sync-el10, sync-f42

#5880 add: neovim-default-editor
  anda/tools/neovim-default-editor/anda.hcl
  anda/tools/neovim-default-editor/neovim-default-editor.spec
  anda/tools/neovim-default-editor/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#5879 fix(lomiri-system-settings): Add remote patches locally
  anda/desktops/lomiri-unity/lomiri-system-settings/2002_use-Noto-font-instead-of-Ubuntu-font.patch
  anda/desktops/lomiri-unity/lomiri-system-settings/2011_build-without-trust-store.patch
  anda/desktops/lomiri-unity/lomiri-system-settings/2013_show-hotspot-on-desktop.patch
  anda/desktops/lomiri-unity/lomiri-system-settings/lomiri-system-settings.spec
Labels: sync-f41, sync-el10, sync-f42

#5895 chore(scx-scheds-nightly): Add new config file
  anda/system/scx-scheds/nightly/scx-scheds-nightly.spec
Labels: sync-f41, sync-el10, sync-f42

#5899 fix: Bulk fixes of nightly packages/update scripts
  anda/apps/goofcord/nightly/update.rhai
  anda/desktops/waylands/hyprland-protocols/update.rhai
  anda/multimedia/rtaudio/rtaudio-nightly.spec
  anda/multimedia/rtaudio/update.rhai
  anda/system/falcond-profiles/update.rhai
  anda/system/rtl8821cu/kmod-common/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#5904 feat(falcond): Track Gitea instead of GitHub mirror
  anda/system/falcond/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#5917 fix(vencord-desktop): Rename the package to vesktop inline with the name of the upstream project
  anda/apps/vencord-desktop/anda.hcl
  anda/apps/vesktop/.gitignore
  anda/apps/vesktop/anda.hcl
  anda/apps/vesktop/update.rhai
  anda/apps/vesktop/vesktop.spec
Labels: sync-f41, sync-el10, sync-f42

#5921 fix(heroic): Drop no longer used license file
  anda/games/heroic-games-launcher/heroic-games-launcher.spec
Labels: sync-f41, sync-el10, sync-f42

#5927 feat(chezmoi): Add shell completion subpackages
  anda/langs/go/chezmoi/chezmoi.spec
Labels: sync-f41, sync-el10, sync-f42

#5933 fix(ghostty-nightly): They dropped the service again
  anda/devs/ghostty/nightly/ghostty-nightly.spec
Labels: sync-f41, sync-el10, sync-f42

#5940 fix(scx-scheds-nightly): Drop no longer used config option
  anda/system/scx-scheds/nightly/scx-scheds-nightly.spec
Labels: sync-f41, sync-el10, sync-f42

#5937 chore: Switch downloads to Zig community mirrors
  anda/langs/zig/bootstrap/update.rhai
  anda/langs/zig/bootstrap/zig-master-bootstrap.spec
  anda/langs/zig/choose-mirror.sh
  anda/langs/zig/master/update.rhai
  anda/langs/zig/master/zig-master.spec
Labels: sync-f41, sync-el10, sync-f42

#4418 Update Flatpost spec based on upstreamed changes
  anda/apps/flatpost/flatpost-desktop-mimetype.patch
  anda/apps/flatpost/flatpost-mime.xml
  anda/apps/flatpost/flatpost.spec
Labels: sync-f41, sync-el10, sync-f42

#5960 fix(zig-master-bootstrap): Move mirror fetch script to bootstrap dir so commit messages work
  anda/langs/zig/bootstrap/choose-mirror.sh
  anda/langs/zig/bootstrap/update.rhai
  anda/langs/zig/master/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#5964 feat(zig-master,zig-master-bootstrap): Randomize mirrors inside spec
  anda/langs/zig/bootstrap/choose-mirror.sh
  anda/langs/zig/bootstrap/update.rhai
  anda/langs/zig/bootstrap/zig-master-bootstrap.spec
  anda/langs/zig/master/update.rhai
  anda/langs/zig/master/zig-master.spec
Labels: sync-f41, sync-el10, sync-f42

#5570 fix(zed, zed-nightly, zed-preview): Make compatible with ZFS
  anda/devs/zed/nightly/zed-nightly.spec
  anda/devs/zed/preview/zed-preview.spec
  anda/devs/zed/stable/zed.spec
Labels: sync-f41, sync-el10, sync-f42

#5968 add: copyparty file server
  anda/tools/copyparty/anda.hcl
  anda/tools/copyparty/copyparty.spec
  anda/tools/copyparty/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#5938 chore: New srpm-macros file
  anda/terra/srpm-macros/anda-srpm-macros.spec
Labels: sync-f41, sync-el10, sync-f42

#5982 fix(copyparty): Deps
  anda/tools/copyparty/copyparty.spec
Labels: sync-f41, sync-el10, sync-f42
