Repository terrapkg/packages, pull requests merged in 2025-03, with the labels that each got.

#3592 Fix: inputplumber
  anda/games/inputplumber/inputplumber.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3594 Fix: libayatana-common
  anda/lib/libayatana-common/libayatana-common.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3591 Fix (wl-kmod): Patches for kernels 6.13 and 6.14
  anda/system/wl-kmod/anda.hcl
  anda/system/wl-kmod/wl-kmod-029_kernel_6.13_adaptation.patch
  anda/system/wl-kmod/wl-kmod-030_kernel_6.14_adaptation.patch
  anda/system/wl-kmod/wl-kmod.spec
Labels: sync-f41, sync-el10, sync-f42

#3590 Fix (YouTube Music): Vendor PNPM again
  anda/apps/youtube-music/youtube-music.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#2898 add: devpod
  anda/langs/go/devpod/anda.hcl
  anda/langs/go/devpod/golang-github-loft-sh-devpod.spec
Labels: sync-f40, sync-f41, sync-el10

#3620 fix(xone-dkms,xone-akmod): not nightly
  anda/system/xone/akmod/anda.hcl
  anda/system/xone/dkms/anda.hcl
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3629 Change (openh264): Wildcard for sonames
  anda/lib/openh264/openh264.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3539 Feat: XPadNeo DKMS
  anda/system/xpadneo/akmod/anda.hcl
  anda/system/xpadneo/akmod/update.rhai
  anda/system/xpadneo/akmod/xpadneo-kmod.spec
  anda/system/xpadneo/dkms/anda.hcl
  anda/system/xpadneo/dkms/dkms-xpadneo.conf
  anda/system/xpadneo/dkms/dkms-xpadneo.spec
  anda/system/xpadneo/dkms/no-weak-modules.conf
  anda/system/xpadneo/dkms/update.rhai
  anda/system/xpadneo/kmod-common/anda.hcl
  anda/system/xpadneo/kmod-common/io.github.xpadneo.metainfo.xml
  anda/system/xpadneo/kmod-common/update.rhai
  anda/system/xpadneo/kmod-common/xpadneo-kmod-common.spec
  anda/system/xpadneo/modules-load-d-xpadneo.conf
  anda/system/xpadneo/update.rhai
  anda/system/xpadneo/xpadneo.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3557 fix(klassy): breeze6.3.1
  anda/themes/klassy/klassy.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3646 Chore: Bulk update my specs
  anda/devs/ghostty/nightly/ghostty-nightly.spec
  anda/devs/ghostty/stable/ghostty.spec
  anda/fonts/cleartype/cleartype-fonts.spec
  anda/fonts/ms-core-tahoma/ms-core-tahoma-fonts.spec
  anda/fonts/ms-core/ms-core-fonts.spec
  anda/games/heroic-games-launcher/heroic-games-launcher.spec
  anda/misc/krabby/krabby.spec
  anda/misc/pbcli/pbcli.spec
  anda/misc/pokemon-colorscripts/pokemon-colorscripts.spec
  anda/system/xone/akmod/xone-kmod.spec
  anda/system/xone/dkms/dkms-xone.spec
  anda/system/xone/kmod-common/xone-kmod-common.spec
  anda/system/xpadneo/akmod/xpadneo-kmod.spec
  anda/system/xpadneo/dkms/dkms-xpadneo.spec
  anda/system/xpadneo/kmod-common/xpadneo-kmod-common.spec
  anda/tools/java-binfmt/java-binfmt.spec
Labels: sync-f41, sync-el10, sync-f42

#3641 Fix: xpadneo and xone update scripts
  anda/system/xone/akmod/update.rhai
  anda/system/xone/akmod/xone-kmod.spec
  anda/system/xone/dkms/dkms-xone.spec
  anda/system/xone/dkms/update.rhai
  anda/system/xpadneo/akmod/update.rhai
  anda/system/xpadneo/akmod/xpadneo-kmod.spec
  anda/system/xpadneo/dkms/dkms-xpadneo.spec
  anda/system/xpadneo/dkms/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3655 fix: mise
  anda/tools/buildsys/mise/mise-fix-metadata-auto.diff
Labels: bug, sync-f40, sync-f41, sync-el10, sync-f42

#3663 add: xdvdfs
  anda/langs/rust/xdvdfs/anda.hcl
  anda/langs/rust/xdvdfs/rust-xdvdfs-cli.spec
  anda/langs/rust/xdvdfs/update.rhai
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10, sync-f42

#3678 fix(xpadneo): provides
  anda/system/xpadneo/kmod-common/xpadneo-kmod-common.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3679 chore(chezmoi): rename the spec file to the correct name
  anda/langs/go/chezmoi/anda.hcl
  anda/langs/go/chezmoi/chezmoi.spec
  anda/langs/go/chezmoi/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3694 Fix: libfreeaptx
  anda/lib/libfreeaptx/libfreeaptx.spec
  anda/lib/libfreeaptx/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#3685 Fix (heroic): Handle AutoReqProv Electron issues
  anda/games/heroic-games-launcher/heroic-games-launcher.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3695 Fix (seto-fonts): URL
  anda/fonts/seto/seto-fonts.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3689 Fix: Change corefonts URLs to HTTPS
  anda/fonts/cleartype/cleartype-fonts.spec
  anda/fonts/ms-core-tahoma/ms-core-tahoma-fonts.spec
  anda/fonts/ms-core/ms-core-fonts.spec
Labels: sync-f41, sync-el10, sync-f42

#3686 Fix (youtube-music): Handle AutoReqProv Electron issues
  anda/apps/youtube-music/youtube-music.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3656 feat(devpod): include the desktop app
  anda/devs/devpod/DevPod.desktop
  anda/devs/devpod/anda.hcl
  anda/devs/devpod/golang-github-loft-sh-devpod.spec
  anda/langs/go/devpod/golang-github-loft-sh-devpod.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3647 Add: pokeget-rs and pokeshell
  anda/misc/pokeget-rs/anda.hcl
  anda/misc/pokeget-rs/pokeget-rs.spec
  anda/misc/pokeget-rs/update.rhai
  anda/misc/pokeshell/HELPER_ALIASES
  anda/misc/pokeshell/anda.hcl
  anda/misc/pokeshell/pokeshell.spec
  anda/misc/pokeshell/update.rhai
Labels: sync-f40, sync-f41, sync-f42

#3593 Fix: voicevox
  anda/apps/voicevox/voicevox.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3723 Fix (extest): Versioning
  anda/misc/extest/rust-extest.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3734 Fix (extest): Don't build i686 debug packages on F41 due to bug
  anda/misc/extest/rust-extest.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3729 Fix (voicevox): Disable AutoReq
  anda/apps/voicevox/voicevox.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3721 Fix (pokeshell): Fix install issues
  anda/misc/pokeshell/pokeshell.spec
Labels: sync-f40, sync-f41, sync-f42

#3722 Feat (pokeget-rs): Make both names executable
  anda/misc/pokeget-rs/pokeget-rs.spec
Labels: sync-f40, sync-f41, sync-f42

#3756 Fix (pbcli): Missing `(` in licenses
  anda/misc/pbcli/pbcli.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3755 Fix (xpadneo-kmod-common): Obsoletes instead due to name change
  anda/system/xpadneo/kmod-common/xpadneo-kmod-common.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3767 bump opentabletdriver .net dependency
  anda/system/opentabletdriver/opentabletdriver.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3735 feat(steam): Better Extest weak dep
  anda/games/steam/steam.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3765 Fix (ghostty-nightly): Changes for localization support
  anda/devs/ghostty/nightly/ghostty-nightly.spec
Labels: sync-f40, sync-f41, sync-f42

#3772 Refactor (pokeget-rs): Bundled provides and use `%git_clone`
  anda/misc/pokeget-rs/pokeget-rs.spec
  anda/misc/pokeget-rs/update.rhai
Labels: sync-f40, sync-f41, sync-f42

#3766 Separate v4l2loopback kmod from userspace tools
  anda/system/v4l2loopback/akmod/anda.hcl
  anda/system/v4l2loopback/akmod/modprobe-d-98-v4l2loopback.conf
  anda/system/v4l2loopback/akmod/modules-load-d-v4l2loopback.conf
  anda/system/v4l2loopback/akmod/update.rhai
  anda/system/v4l2loopback/akmod/v4l2loopback-kmod.spec
  anda/system/v4l2loopback/v4l2loopback.spec
Labels: sync-f41, sync-el10, sync-f42

#3788 Add: Rio
  anda/devs/rio/anda.hcl
  anda/devs/rio/rio.spec
  anda/devs/rio/update.rhai
Labels: sync-f40, sync-f41, sync-f42

#3794 fix(rio): Rename package to Crate name due to a Fedora provides
  anda/devs/rio/rio.spec
Labels: sync-f40, sync-f41, sync-f42

#3799 fix(devpod): add current version and rename binary with spaces
  anda/devs/devpod/golang-github-loft-sh-devpod.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3789 fix(ghostty-nightly): Add gtk4-layer-shell build dependency
  anda/devs/ghostty/nightly/ghostty-nightly.spec
Labels: sync-f40, sync-f41, sync-f42

#3806 fix(pokeshell): Hard dep on chafa
  anda/misc/pokeshell/pokeshell.spec
Labels: sync-f40, sync-f41, sync-f42

#3807 fix(mesa): Deprecate libglapi
  anda/lib/mesa/mesa.spec
Labels: sync-f41, sync-el10, sync-f42

#3787 Add: xpad-noone
  anda/system/xpad-noone/akmod/0000.patch
  anda/system/xpad-noone/akmod/anda.hcl
  anda/system/xpad-noone/akmod/update.rhai
  anda/system/xpad-noone/akmod/xpad-noone-kmod.spec
  anda/system/xpad-noone/dkms/0000.patch
  anda/system/xpad-noone/dkms/anda.hcl
  anda/system/xpad-noone/dkms/dkms-xpad-noone.spec
  anda/system/xpad-noone/dkms/no-weak-modules.conf
  anda/system/xpad-noone/dkms/update.rhai
  anda/system/xpad-noone/kmod-common/anda.hcl
  anda/system/xpad-noone/kmod-common/update.rhai
  anda/system/xpad-noone/kmod-common/xpad-noone.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3785 refactor(xpadneo, xone): Fix potential installation issues and improve UX
  anda/system/xone/akmod/anda.hcl
  anda/system/xone/akmod/update.rhai
  anda/system/xone/akmod/xone-kmod.spec
  anda/system/xone/dkms/anda.hcl
  anda/system/xone/dkms/dkms-xone.spec
  anda/system/xone/dkms/no-weak-modules.conf
  anda/system/xone/dkms/update.rhai
  anda/system/xone/kmod-common/anda.hcl
  anda/system/xone/kmod-common/update.rhai
  anda/system/xone/kmod-common/xone.spec
  anda/system/xpadneo/akmod/anda.hcl
  anda/system/xpadneo/akmod/update.rhai
  anda/system/xpadneo/akmod/xpadneo-kmod.spec
  anda/system/xpadneo/dkms/anda.hcl
  anda/system/xpadneo/dkms/dkms-xpadneo.spec
  anda/system/xpadneo/dkms/update.rhai
  anda/system/xpadneo/kmod-common/anda.hcl
  anda/system/xpadneo/kmod-common/xpadneo-kmod-common.spec
  anda/system/xpadneo/kmod-common/xpadneo.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3824 fix(xpadneo, xone, xpad-noone): Update scripts
  anda/system/xone/akmod/anda.hcl
  anda/system/xone/akmod/update.rhai
  anda/system/xone/akmod/xone-kmod.spec
  anda/system/xone/dkms/anda.hcl
  anda/system/xone/dkms/dkms-xone.spec
  anda/system/xone/kmod-common/update.rhai
  anda/system/xone/kmod-common/xone.spec
  anda/system/xpad-noone/akmod/anda.hcl
  anda/system/xpad-noone/akmod/update.rhai
  anda/system/xpad-noone/akmod/xpad-noone-kmod.spec
  anda/system/xpad-noone/dkms/anda.hcl
  anda/system/xpad-noone/dkms/dkms-xpad-noone.spec
  anda/system/xpad-noone/dkms/update.rhai
  anda/system/xpad-noone/kmod-common/update.rhai
  anda/system/xpad-noone/kmod-common/xpad-noone.spec
  anda/system/xpadneo/akmod/anda.hcl
  anda/system/xpadneo/akmod/update.rhai
  anda/system/xpadneo/akmod/xpadneo-kmod.spec
  anda/system/xpadneo/dkms/anda.hcl
  anda/system/xpadneo/dkms/dkms-xpadneo.spec
  anda/system/xpadneo/dkms/update.rhai
  anda/system/xpadneo/kmod-common/update.rhai
  anda/system/xpadneo/kmod-common/xpadneo.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3827 fix(codium-marketplace): sed the json properly
  anda/devs/codium-marketplace/codium-marketplace.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3826 fix(pokeget-rs): Change update script to JSON array
  anda/misc/pokeget-rs/update.rhai
Labels: sync-f40, sync-f41, sync-f42

#3839 fix(backportrc): merge conflicts
  ..backportrc.json.kate-swp
  .backportrc.json
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10, sync-f42

#3845 fix(xpadneo, xone, xpad-noone): Actually fix update scripts
  anda/system/xone/akmod/update.rhai
  anda/system/xone/akmod/xone-kmod.spec
  anda/system/xone/dkms/dkms-xone.spec
  anda/system/xone/dkms/update.rhai
  anda/system/xpad-noone/akmod/update.rhai
  anda/system/xpad-noone/akmod/xpad-noone-kmod.spec
  anda/system/xpad-noone/dkms/dkms-xpad-noone.spec
  anda/system/xpad-noone/dkms/update.rhai
  anda/system/xpadneo/akmod/update.rhai
  anda/system/xpadneo/akmod/xpadneo-kmod.spec
  anda/system/xpadneo/dkms/dkms-xpadneo.spec
  anda/system/xpadneo/dkms/update.rhai
Labels: sync-f40, sync-f41, sync-f42

#3855 chore: Bump ghostty-nightly manually
  anda/devs/ghostty/nightly/ghostty-nightly.spec
Labels: sync-f40, sync-f41, sync-f42

#3849 fix(mesa): Remove libglapi entirely and change what obsoletes it
  anda/lib/mesa/mesa.spec
Labels: sync-f41, sync-el10, sync-f42

#3825 feat(mesa): patches: two commit backports for game fixes
  anda/lib/mesa/13a3f9a972324a72dd507e09ac975b969e6c88e0.patch
  anda/lib/mesa/237d8799be3afe9a1e7ca9156a5d44ffe0aae681.patch
  anda/lib/mesa/mesa.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3860 chore(ghostty-nightly): Bump on F41 and F40
  anda/devs/ghostty/nightly/ghostty-nightly.spec
Labels: sync-f40

#3880 f41: Add patch for vram issue in Mesa 25
  anda/lib/mesa/34005.patch
  anda/lib/mesa/mesa.spec
Labels: sync-frawhide, sync-el10, sync-f42

#3879 fix(ghostty-nightly): Add gtk4-layer-shell dep
  anda/devs/ghostty/nightly/ghostty-nightly.spec
Labels: sync-f40, sync-f41, sync-f42

#3889 fix(protobuf): Remove obsolete file
  anda/langs/python/protobuf/python3-protobuf.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3844 feat(pokeget-rs): pull from crates.io
  anda/misc/pokeget-rs/anda.hcl
  anda/misc/pokeget-rs/pokeget-rs.spec
  anda/misc/pokeget/anda.hcl
  anda/misc/pokeget/pokeget.spec
  anda/misc/pokeget/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3888 fix(devpod): rename binaries to match upstream
  anda/devs/devpod/DevPod.desktop
  anda/devs/devpod/golang-github-loft-sh-devpod.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3907 feat(mpv-nightly): Make shell completions subpackages
  anda/apps/mpv/mpv-nightly.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3805 revert(rio): Change name back to the correct name, rename binary to not conflict with python3-rasterio
  anda/devs/rio/rio.spec
Labels: sync-f40, sync-f41, sync-f42

#3876 add: sndio
  anda/multimedia/sndio/anda.hcl
  anda/multimedia/sndio/sndio.spec
  anda/multimedia/sndio/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3866 fix(xone, xpadneo, xpad-noone): Fix spec errors
  anda/system/xone/akmod/xone-kmod.spec
  anda/system/xone/dkms/dkms-xone.spec
  anda/system/xpad-noone/akmod/xpad-noone-kmod.spec
  anda/system/xpad-noone/dkms/dkms-xpad-noone.spec
  anda/system/xpadneo/akmod/xpadneo-kmod.spec
  anda/system/xpadneo/dkms/dkms-xpadneo.spec
Labels: sync-f40, sync-f41

#3920 feat(rio): Devel package
  anda/devs/rio/rio.spec
Labels: sync-f40, sync-f41, sync-f42

#3926 fix(mesa): Obsolete by Epoch
  anda/lib/mesa/mesa.spec
Labels: sync-f41, sync-el10, sync-f42

#3933 fix(audacity, extest, gcm-core, uwufetch): Update scripts
  anda/apps/audacity-freeworld/audacity-freeworld.spec
  anda/apps/audacity-freeworld/update.rhai
  anda/misc/extest/rust-extest.spec
  anda/misc/extest/update.rhai
  anda/misc/uwufetch/update.rhai
  anda/misc/uwufetch/uwufetch.spec
  anda/tools/gcm-core/gcm-core.spec
  anda/tools/gcm-core/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3927 fix(fluent-icon-theme): maybe conflicts itself?
  anda/themes/fluent-icon-theme/fluent-icon-theme.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3943 fix(mesa): backport AMD GPU artifact fix, cleanup and attribute patches
  anda/lib/mesa/12633.patch
  anda/lib/mesa/13a3f9a972324a72dd507e09ac975b969e6c88e0.patch
  anda/lib/mesa/237d8799be3afe9a1e7ca9156a5d44ffe0aae681.patch
  anda/lib/mesa/34005.patch
  anda/lib/mesa/bazzite.patch
  anda/lib/mesa/mesa.spec
  anda/lib/mesa/valve.patch
Labels: sync-f40, sync-frawhide, sync-f41, sync-f42

#3953 feat(pbcli): Enable uniffi support and package development files
  anda/misc/pbcli/pbcli.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3961 komikku: fix license path
  anda/apps/komikku/komikku.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3951 fix(uwufetch): Make Git based and fix Git cloning
  anda/misc/uwufetch/anda.hcl
  anda/misc/uwufetch/update.rhai
  anda/misc/uwufetch/uwufetch.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3966 add: subtitleedit
  anda/apps/subtitleedit/anda.hcl
  anda/apps/subtitleedit/subtitleedit.spec
  anda/apps/subtitleedit/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3980 fix(ghostty): Don't conflict with ncurses-term on F42 and Rawhide
  anda/devs/ghostty/nightly/ghostty-nightly.spec
  anda/devs/ghostty/stable/ghostty.spec
Labels: sync-f40, sync-f41, sync-f42

#3919 fix(kf6-kio): obsoletes the corr. pkgs
  anda/desktops/kde/kf6-kio/kf6-kio.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3988 fix(steam): Fedora packages steam-devices now
  anda/games/steam/steam.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3996 fix(peazip): Dep on p7zip
  anda/apps/peazip/peazip.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3987 refactor(heroic): Changes for aarch64 preparation, Git clone to install Git hooks
  anda/games/heroic-games-launcher/afterPack.diff
  anda/games/heroic-games-launcher/heroic-games-launcher.spec
  anda/games/heroic-games-launcher/update.rhai
Labels: sync-f40, sync-f41, sync-f42

#4006 chore/feat(heroic): Rename LICENSE to distinguish it as a bundled dependency license
  anda/games/heroic-games-launcher/heroic-games-launcher.spec
Labels: sync-f40, sync-f41, sync-f42

#4005 fix: limine
  anda/system/limine/limine.spec
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10, sync-f42

#4028 chore: bump bodhi rawhide ver
  andax/bump_extras.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4027 fix(umu-launcher): Remove Steam directory
  anda/games/umu/umu-launcher.spec
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10

#4021 fix(ghostty-nightly): New tarball extracted directory
  anda/devs/ghostty/nightly/ghostty-nightly.spec
Labels: sync-f40, sync-frawhide, sync-f41

#4053 add: android-udev-rules
  anda/misc/android-udev-rules/anda.hcl
  anda/misc/android-udev-rules/android-udev-rules.spec
  anda/misc/android-udev-rules/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4050 fix: gping
  anda/langs/rust/gping/rust-gping.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4052 rebuild: rust-jellyfin-rpc-cli
  anda/langs/rust/jellyfin-rpc/rust-jellyfin-rpc-cli.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3429 fix(files): apparmor
  anda/lib/apparmor/apparmor.spec
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10, sync-f42

#4045 fix(lightly-qt5): update.rhai
  anda/themes/lightly-qt5/update.rhai
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10, sync-f42

#4022 fix(heroic): Install icons to the correct directory and remove unused files
  anda/games/heroic-games-launcher/heroic-games-launcher.spec
Labels: sync-f40, sync-frawhide, sync-f41

#4044 fix(ffmpeg): update script
  anda/multimedia/ffmpeg/update.rhai
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10, sync-f42

#4087 fix(komikku): Fetch correct archive URL
  anda/apps/komikku/komikku.spec
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10

#4083 fix(uutils-coreutils-replace): Update patch
  anda/system/uutils-coreutils-replace/coreutils-fix-metadata.diff
Labels: sync-frawhide, sync-f41

#4103 [f41] Mesa: Update bazzite.patch
  anda/lib/mesa/bazzite.patch
  anda/lib/mesa/mesa.spec
Labels: sync-frawhide, sync-el10, sync-f42

#4098 fix(peazip): Install desktop file, icons, and file manager integration
  anda/apps/peazip/peazip.spec
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10

#4078 fix(akmod-v4l2loopback): Add missing prep step and fix build steps
  anda/system/v4l2loopback/akmod/v4l2loopback-kmod.spec
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10

#4115 fix(gcm-core): missing version…??
  anda/tools/gcm-core/gcm-core.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4120 Fix cros-keyboard-map um_commit
  anda/system/cros-keyboard-map/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4133 fix(open-huninn-fonts): Renamed license file
  anda/fonts/open-huninn/open-huninn-fonts.spec
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10

#4136 fix(extest): Remove redundant Mold linker argument
  anda/misc/extest/rust-extest.spec
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10

#4135 fix(mesa): remove broken intel fix
  anda/lib/mesa/bazzite.patch
  anda/lib/mesa/mesa.spec
Labels: sync-f41, sync-el10, sync-f42

#4131 refactor(ivsc-firmware): Specify exclusive arch in anda.hcl
  anda/system/ivsc-firmware/anda.hcl
Labels: sync-frawhide, sync-f41, sync-el10

#4132 refactor(intel-ipu6-kmod): Specify exclusive arch in anda.hcl
  anda/system/intel-ipu6-kmod/anda.hcl
Labels: sync-frawhide, sync-f41, sync-el10

#4158 fix(mesa): missmatched versions
  anda/lib/mesa/bazzite.patch
  anda/lib/mesa/mesa.spec
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10, sync-f42

#4162 feat(v4l2loopback): Compatibility with Nobara and CachyOS COPR kernel
  anda/system/v4l2loopback/kmod-common/v4l2loopback.spec
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10

#4174 add: steamtinkerlaunch and steamtinkerlaunch-git
  anda/games/steamtinkerlaunch/git/anda.hcl
  anda/games/steamtinkerlaunch/git/steamtinkerlaunch-git.spec
  anda/games/steamtinkerlaunch/git/update.rhai
  anda/games/steamtinkerlaunch/stable/anda.hcl
  anda/games/steamtinkerlaunch/stable/steamtinkerlaunch.spec
  anda/games/steamtinkerlaunch/stable/update.rhai
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10

#4089 Add: dwarfs
  anda/lib/dwarfs/anda.hcl
  anda/lib/dwarfs/dwarfs.spec
  anda/lib/dwarfs/update.rhai
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10

#4188 fix(komikku): Version format
  anda/apps/komikku/komikku.spec
  anda/apps/komikku/update.rhai
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10

#4193 fix(komikku): Explicitly list CMake as a build dep, fix update.rhai
  anda/apps/komikku/komikku.spec
  anda/apps/komikku/update.rhai
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10

#4199 fix(lomiri-system-settings): Update patches
  anda/desktops/lomiri-unity/lomiri-system-settings/lomiri-system-settings.spec
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10

#4184 add: git-biance, act, atac
  anda/devs/atac/anda.hcl
  anda/devs/atac/atac.spec
  anda/devs/atac/update.rhai
  anda/devs/git-biance/anda.hcl
  anda/devs/git-biance/git-biance.spec
  anda/devs/git-biance/update.rhai
  anda/langs/go/gh-act/anda.hcl
  anda/langs/go/gh-act/gh-act.spec
  anda/langs/go/gh-act/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4211 fix(kanata): Update patch
  anda/tools/kanata/kanata-fix-metadata-auto.diff
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10
