Repository terrapkg/packages, pull requests merged in 2025-08, with the labels that each got.

#5989 fix(gamescope-session): files
  anda/games/gamescope-session/gamescope-session.spec
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42

#5997 fix(LCEVdec): Drop patch, Git clone source, update files
  anda/multimedia/lcevcdec/LCEVCdec-soversion.patch
  anda/multimedia/lcevcdec/LCEVCdec.spec
Labels: sync-f41, sync-el10, sync-f42

#6003 chore: Bump LCEVdec on <= 42
  anda/multimedia/lcevcdec/LCEVCdec.spec
Labels: sync-f41, sync-el10

#6008 fix: Update bazzite.patch and mesa.spec for 25.2.0
  anda/lib/mesa/bazzite.patch
  anda/lib/mesa/mesa.spec
Labels: sync-frawhide, sync-f41, sync-el10

#6011 add: raindrop
  anda/tools/raindrop/anda.hcl
  anda/tools/raindrop/desktop-file-call-pkexec.patch
  anda/tools/raindrop/org.raspberrypi.raindrop.configure-display.policy
  anda/tools/raindrop/raindrop.spec
  anda/tools/raindrop/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#6025 add: rp-bookshelf
  anda/apps/rp-bookshelf/anda.hcl
  anda/apps/rp-bookshelf/rp-bookshelf.spec
  anda/apps/rp-bookshelf/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#6032 add: signal-desktop
  anda/apps/signal-desktop/anda.hcl
  anda/apps/signal-desktop/signal-desktop.spec
  anda/apps/signal-desktop/signal.desktop
  anda/apps/signal-desktop/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#6036 fix: Update bazzite.patch and mesa.spec for 25.2.0 (Reapplication)
  anda/lib/mesa/bazzite.patch
  anda/lib/mesa/mesa.spec
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42

#6041 feat: Add AMD Anti-lag backport to Mesa 25.2.0
  anda/lib/mesa/bazzite.patch
  anda/lib/mesa/mesa.spec
Labels: sync-frawhide, sync-f41, sync-el10

#6045 add: coreboot-utils
  anda/tools/abuild/abuild.spec
  anda/tools/abuild/anda.hcl
  anda/tools/abuild/update.rhai
  anda/tools/cbfstool/anda.hcl
  anda/tools/cbfstool/cbfstool.spec
  anda/tools/cbfstool/update.rhai
  anda/tools/cbmem/anda.hcl
  anda/tools/cbmem/cbmem.spec
  anda/tools/cbmem/update.rhai
  anda/tools/chromium-ectool/chromium-ectool.spec
  anda/tools/coreboot-utils/anda.hcl
  anda/tools/coreboot-utils/coreboot-utils.spec
  anda/tools/coreboot-utils/elf_segment_extractor-python3.patch
  anda/tools/coreboot-utils/spdtool-python3.patch
  anda/tools/coreboot-utils/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#6047 Backport: coreboot-utils
  anda/tools/abuild/abuild.spec
  anda/tools/abuild/anda.hcl
  anda/tools/abuild/update.rhai
  anda/tools/cbfstool/anda.hcl
  anda/tools/cbfstool/cbfstool.spec
  anda/tools/cbfstool/update.rhai
  anda/tools/cbmem/anda.hcl
  anda/tools/cbmem/cbmem.spec
  anda/tools/cbmem/update.rhai
  anda/tools/chromium-ectool/chromium-ectool.spec
  anda/tools/coreboot-utils/anda.hcl
  anda/tools/coreboot-utils/coreboot-utils.spec
  anda/tools/coreboot-utils/elf_segment_extractor-python3.patch
  anda/tools/coreboot-utils/spdtool-python3.patch
  anda/tools/coreboot-utils/update.rhai
Labels: sync-f41, sync-el10

#6057 fix: coreboot-utils
  anda/tools/coreboot-utils/coreboot-utils.spec
Labels: sync-f41, sync-el10, sync-f42

#6050 add: chess-tui
  anda/games/chess-tui/anda.hcl
  anda/games/chess-tui/rust-chess-tui.spec
  anda/games/chess-tui/update.rhai
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42

#6073 fix(signal-desktop): create symlink during %install, not %post
  anda/apps/signal-desktop/signal-desktop.spec
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42

#6078 fix: coreboot-utils
  anda/tools/coreboot-utils/coreboot-utils.spec
Labels: sync-f41, sync-el10, sync-f42

#6046 fix(dracut-strip-trigger): make trigger run later than dracut's one
  anda/system/dracut-strip-trigger/dracut-strip-trigger.spec
Labels: sync-f41, sync-el10, sync-f42

#6077 fix(zed*): exec correct binary from .desktop
  anda/devs/zed/nightly/zed-nightly.spec
  anda/devs/zed/preview/zed-preview.spec
  anda/devs/zed/stable/zed.spec
Labels: bug, sync-frawhide, sync-f41, sync-el10, sync-f42

#6105 fix: micro
  anda/devs/micro/micro-nightly.spec
Labels: sync-f41, sync-el10, sync-f42, sync-f43

#6051 add: television
  anda/langs/rust/television/anda.hcl
  anda/langs/rust/television/rust-television.spec
  anda/langs/rust/television/television-fix-metadata-auto.diff
  anda/langs/rust/television/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#6106 fix: fluent-icon-theme
  anda/themes/fluent-icon-theme/fluent-icon-theme.spec
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42, sync-f43

#6092 fix(signal-desktop): build sticker-creator
  anda/apps/signal-desktop/signal-desktop.spec
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42, sync-f43

#6087 add: flameshot.qt5
  anda/apps/flameshot.qt5/anda.hcl
  anda/apps/flameshot.qt5/flameshot.qt5.spec
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42, sync-f43

#6150 feat: Enable D3D12 for WSL in Mesa
  anda/lib/mesa/mesa.spec
Labels: sync-frawhide, sync-f41, sync-el10, sync-f43

#6156 chore: Split dxil into dxil and dxil-libs, allows both 32-bit and 64-bit support for spir-v to dxil
  anda/lib/mesa/mesa.spec
Labels: sync-frawhide, sync-f41, sync-el10, sync-f43

#6163 fix: stupid typo for large runners
  .github/workflows/json-build.yml
Labels: bug, sync-f41, sync-el10, sync-f42, sync-f43

#6157 Feat: Switch mesa to large runners
  anda/lib/mesa/anda.hcl
  anda/lib/mesa/mesa.spec
Labels: sync-frawhide, sync-f41, sync-el10, sync-f43

#6175 gamescope: rebase to 3.16.3
  anda/games/terra-gamescope/handheld.patch
  anda/games/terra-gamescope/terra-gamescope.spec
Labels: sync-frawhide, sync-f41, sync-f42, sync-f43

#6204 fix(astal-gtk): add commit
  anda/lib/astal/astal-gtk/astal-gtk.spec
  anda/lib/astal/astal-gtk/update.rhai
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42, sync-f43

#6205 fix(android-studio): exclude reqs/provs correctly
  anda/devs/android-studio/stable/android-studio.spec
Labels: bug, sync-frawhide, sync-f41, sync-el10, sync-f42, sync-f43
