Repository terrapkg/packages, pull requests merged in 2025-09, with the labels that each got.

#5543 chore(modern-colorthief): Disable docs for now so we can rebuild it for Python 3.14
  anda/tools/modern-colorthief/modern-colorthief.spec
Labels: sync-f41, sync-el10, sync-f42, sync-f43

#6214 fix: osu-lazer
  anda/games/osu-lazer/osu-lazer.spec
  anda/games/osu-lazer/update.rhai
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42, sync-f43

#6234 fix(flameshot-nightly): unpin
  anda/apps/flameshot/flameshot-nightly.spec
  anda/apps/flameshot/update.rhai
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42, sync-f43

#6257 fix(throne): desktop file
  anda/apps/throne/throne.desktop
  anda/apps/throne/throne.sh
  anda/apps/throne/throne.spec
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42, sync-f43

#6229 add: zoi
  anda/langs/rust/zoi/anda.hcl
  anda/langs/rust/zoi/rust-zoi-rs.spec
  anda/langs/rust/zoi/update.rhai
  anda/langs/rust/zoi/zoi-rs-fix-metadata-auto.diff
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42, sync-f43

#6082 fix: bottom
  anda/langs/rust/bottom/bottom-fix-metadata-auto.diff
  anda/langs/rust/bottom/rust-bottom.spec
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42

#6254 add: mdbook
  anda/tools/mdbook/anda.hcl
  anda/tools/mdbook/mdbook.spec
  anda/tools/mdbook/update.rhai
Labels: sync-f41, sync-el10, sync-f42, sync-f43

#6279 fix(throne): rename core
  anda/apps/throne/throne.spec
Labels: bug, sync-frawhide, sync-f41, sync-el10, sync-f42, sync-f43

#6293 chore: Rebuild FFmpeg without libnpp
  anda/multimedia/ffmpeg/ffmpeg.spec
Labels: sync-el10, sync-f42, sync-f43

#6292 chore: Sync FFmpeg
  anda/multimedia/ffmpeg/anda.hcl
Labels: nosync

#6291 chore(nvidia*): Update specs, reblacklist Nouveau
  anda/system/nvidia/nvidia-driver/70-nvidia-driver.preset
  anda/system/nvidia/nvidia-driver/nvidia-driver.spec
  anda/system/nvidia/nvidia-kmod-common/nvidia-kmod-common.spec
  anda/system/nvidia/nvidia-kmod-common/nvidia.conf
Labels: sync-f41, sync-el10, sync-f42, sync-f43

#6321 Bump commit date on gamescope-session packages
  anda/games/gamescope-session-steam/gamescope-session-steam.spec
  anda/games/gamescope-session/gamescope-session.spec
Labels: sync-frawhide, sync-f41, sync-f42, sync-f43

#6329 fix?: sbctl again
  anda/tools/sbctl/sbctl.spec
Labels: sync-f41, sync-el10, sync-f42, sync-f43

#6330 add: waybar-niri-taskbar
  anda/desktops/waylands/niri-taskbar/anda.hcl
  anda/desktops/waylands/niri-taskbar/niri-taskbar-fix-metadata-auto.diff
  anda/desktops/waylands/niri-taskbar/rust-niri-taskbar.spec
  anda/desktops/waylands/niri-taskbar/update.rhai
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42, sync-f43

#6344 fix(?????????): sbctl
  anda/tools/sbctl/sbctl.spec
Labels: sync-f41, sync-el10, sync-f42, sync-f43

#6382 Update ffmpeg to 8.0
  anda/multimedia/ffmpeg/ffmpeg-HandBrake.patch
  anda/multimedia/ffmpeg/ffmpeg-svt-vp9.patch
  anda/multimedia/ffmpeg/ffmpeg.spec
Labels: sync-frawhide, sync-f41, sync-el10, sync-f43

#6386 Revert "Update ffmpeg to 8.0 (#6382) (#6383)"
  anda/multimedia/ffmpeg/ffmpeg-HandBrake.patch
  anda/multimedia/ffmpeg/ffmpeg-svt-vp9.patch
  anda/multimedia/ffmpeg/ffmpeg.spec
  anda/multimedia/ffmpeg/update.rhai
Labels: sync-el10, sync-f42, sync-f43

#6389 fix(ffmpeg): Missing ) in update.rhai
  anda/multimedia/ffmpeg/update.rhai
Labels: sync-f42, sync-f43

#6404 fix(ghostty): Update for new release
  anda/devs/ghostty/stable/ghostty.spec
Labels: sync-frawhide, sync-f41, sync-el10, sync-f43

#6413 add: bup
  anda/misc/bup/anda.hcl
  anda/misc/bup/bup.spec
  anda/misc/bup/update.rhai
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42, sync-f43

#6147 add: ShivaVG
  anda/lib/ShivaVG/ShivaVG.spec
  anda/lib/ShivaVG/anda.hcl
  anda/lib/ShivaVG/update.rhai.bak
Labels: sync-f41, sync-el10, sync-f42, sync-f43

#6435 add: honkers-railway-launcher
  anda/games/launcher.moe/honkers-railway-launcher/anda.hcl
  anda/games/launcher.moe/honkers-railway-launcher/honkers-railway-launcher.spec
  anda/games/launcher.moe/honkers-railway-launcher/update.rhai
Labels: sync-frawhide, sync-f41, sync-f42, sync-f43

#6444 Update gamescope
  anda/games/terra-gamescope/handheld.patch
  anda/games/terra-gamescope/terra-gamescope.spec
Labels: sync-frawhide, sync-f41, sync-f42, sync-f43

#6376 chore(mesa): Bring in latest DXIL changes from Fedora PR discussions
  anda/lib/mesa/mesa.spec
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42, sync-f43

#6454 fix(mock-configs): add terra-rawhide.tpl
  anda/terra/mock-configs/terra-mock-configs.spec
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42, sync-f43

#6466 fix(scrcpy): specify OpenCL-ICD-Loader manually
  anda/apps/scrcpy/scrcpy.spec
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42, sync-f43

#6502 fix(ghostty-nightly): Package development files
  anda/devs/ghostty/nightly/ghostty-nightly.spec
Labels: sync-f41, sync-el10, sync-f42, sync-f43

#6507 fix(ghostty): KIO package dependency
  anda/devs/ghostty/nightly/ghostty-nightly.spec
  anda/devs/ghostty/stable/ghostty.spec
Labels: sync-f41, sync-el10, sync-f42, sync-f43

#6512 fix(signal-desktop): also exclude reqs
  anda/apps/signal-desktop/signal-desktop.spec
Labels: sync-f41, sync-el10, sync-f42, sync-f43

#6532 add: pyvcd
  anda/langs/python/pyvcd/anda.hcl
  anda/langs/python/pyvcd/pyvcd.spec
  anda/langs/python/pyvcd/update.rhai
Labels: sync-f41, sync-el10, sync-f42, sync-f43

#6531 fix(qmk_cli): remove duplicate build dep
  anda/tools/qmk_cli/qmk_cli.spec
Labels: sync-f41, sync-el10, sync-f42, sync-f43

#6541 add: fx2
  anda/langs/python/fx2/anda.hcl
  anda/langs/python/fx2/fx2.spec
  anda/langs/python/fx2/update.rhai
Labels: sync-f41, sync-el10, sync-f42, sync-f43

#6585 fix: minor stardust stuff
  anda/stardust/armillary/stardust-armillary.spec
  anda/stardust/atmosphere/stardust-atmosphere.spec
  anda/stardust/black-hole/stardust-black-hole.spec
  anda/stardust/comet/stardust-comet.spec
  anda/stardust/flatland/stardust-flatland.spec
  anda/stardust/gravity/stardust-gravity.spec
  anda/stardust/magnetar/stardust-magnetar.spec
  anda/stardust/non-spatial-input/stardust-non-spatial-input.spec
  anda/stardust/protostar/stardust-protostar.spec
  anda/stardust/server/stardust-server.spec
  anda/stardust/telescope/stardust-telescope.spec
Labels: sync-f41, sync-el10, sync-f42, sync-f43

#6584 fix: python packages
  anda/langs/python/fx2/fx2.spec
  anda/langs/python/jschon/jschon.spec
  anda/langs/python/pyvcd/pyvcd.spec
  anda/tools/qmk_cli/anda.hcl
  anda/tools/qmk_cli/qmk_cli.spec
Labels: sync-f41, sync-el10, sync-f42, sync-f43

#6573 fix(rio): bdep alsa
  anda/devs/rio/rio.spec
Labels: sync-f41, sync-el10, sync-f42, sync-f43
