Repository terrapkg/packages, pull requests merged in 2025-01, with the labels that each got.

#2834 ghostty package fixes
  anda/devs/ghostty/nightly/ghostty-nightly.spec
  anda/devs/ghostty/stable/ghostty.spec
Labels: bug, sync-f40, sync-f41, sync-el10

#2845 fix: gamescope (bazzite port)
  anda/games/gamescope/0001-cstdint.patch
  anda/games/gamescope/0001-limits.patch
  anda/games/gamescope/1483.patch
  anda/games/gamescope/anda.hcl
  anda/games/gamescope/chimeraos.patch
  anda/games/gamescope/disable-steam-touch-click-atom.patch
  anda/games/gamescope/gamescope-legacy.sh
  anda/games/gamescope/gamescope.spec
  anda/games/gamescope/handheld.patch
  anda/games/gamescope/revert-299bc34.patch
  anda/games/gamescope/stb.pc
  anda/games/gamescope/update-patch.sh
  anda/games/gamescope/update.rhai
  anda/games/gamescope/v2-0001-always-send-ctrl-1-2-to-steam-s-wayland-session.patch
Labels: sync-f40, sync-f41, sync-el10

#2841 [frawhide] Add: Patched switcherooctl-control
  anda/apps/switcheroo-control/0001-main-update-GPUs-comment-for-dbus-property.patch
  anda/apps/switcheroo-control/0002-main-add-Discrete-key.patch
  anda/apps/switcheroo-control/0003-tests-fix-integration-tests-without-UMockdev.patch
  anda/apps/switcheroo-control/0004-tests-add-tests-for-discrete-detection-with-mock-lib.patch
  anda/apps/switcheroo-control/0005-main-remove-leftover-and-fix-typo.patch
  anda/apps/switcheroo-control/0006-main-move-discrete-dependencies-out-of-main-deps.patch
  anda/apps/switcheroo-control/0007-main-use-glib-for-discrete-command-line-arguments.patch
  anda/apps/switcheroo-control/0008-main-add-udev-rule-for-i915.patch
  anda/apps/switcheroo-control/0009-main-use-Discrete-key-in-switcherooctl.patch
  anda/apps/switcheroo-control/0010-main-use-new-GPU-list-on-uevent.patch
  anda/apps/switcheroo-control/anda.hcl
  anda/apps/switcheroo-control/switcheroo-control.spec
Labels: sync-f40, sync-frawhide, sync-f41

#2843 [f41] feat: Add Valve's gamescope patch for Mesa
  anda/lib/mesa/mesa.spec
  anda/lib/mesa/valve.patch
Labels: sync-f40, sync-frawhide, sync-f41

#2842 [f41] Add: Patched switcheroo-control, kf6-kio and gnome-shell
  anda/desktops/gnome/gnome-shell/0001-gdm-Work-around-failing-fingerprint-auth.patch
  anda/desktops/gnome/gnome-shell/0001-status-keyboard-Add-a-catch-around-reload-call.patch
  anda/desktops/gnome/gnome-shell/0002-status-keyboard-Load-keyboard-from-system-settings-i.patch
  anda/desktops/gnome/gnome-shell/0003-status-keyboard-Use-gnome-desktop-API-for-getting-de.patch
  anda/desktops/gnome/gnome-shell/3193.patch
  anda/desktops/gnome/gnome-shell/anda.hcl
  anda/desktops/gnome/gnome-shell/changelog
  anda/desktops/gnome/gnome-shell/gitignore
  anda/desktops/gnome/gnome-shell/gnome-shell-favourite-apps-firefox.patch
  anda/desktops/gnome/gnome-shell/gnome-shell.spec
  anda/desktops/kde/kf6-kio/0001-Give-the-kuriikwsfiltereng_private-a-VERSION-and-SOV.patch
  anda/desktops/kde/kf6-kio/1556.patch
  anda/desktops/kde/kf6-kio/6e7775d315f389df0a440ed62b842ce83dc9a27e.patch
  anda/desktops/kde/kf6-kio/anda.hcl
  anda/desktops/kde/kf6-kio/kf6-kio.spec
Labels: sync-f40, sync-frawhide, sync-f41

#2838 Fix: Ghostty internal version
  anda/devs/ghostty/nightly/ghostty-nightly.spec
  anda/devs/ghostty/stable/ghostty.spec
Labels: sync-f40, sync-f41, sync-el10

#2856 Add: Audacity
  anda/apps/audacity-freeworld/anda.hcl
  anda/apps/audacity-freeworld/audacity-freeworld.spec
  anda/apps/audacity-freeworld/update.rhai
Labels: sync-f40, sync-f41, sync-el10

#2869 Fix: Drop patch and add new -Dstrip=false flag
  anda/devs/ghostty/nightly/ghostty-nightly.spec
  anda/devs/ghostty/nightly/no-strip.diff
Labels: sync-f40, sync-f41, sync-el10

#2849 add: topgrade
  anda/tools/topgrade/anda.hcl
  anda/tools/topgrade/topgrade-fix-metadata-auto.diff
  anda/tools/topgrade/topgrade.spec
  anda/tools/topgrade/update.rhai
Labels: sync-f40, sync-f41, sync-el10

#2893 add subrepo label
  .github/workflows/autobuild.yml
  anda/apps/switcheroo-control/anda.hcl
  anda/desktops/gnome/gnome-shell/anda.hcl
  anda/desktops/kde/kf6-kio/anda.hcl
  anda/games/gamescope/anda.hcl
  anda/lib/mesa/anda.hcl
  anda/lib/openh264/anda.hcl
  anda/multimedia/carla/anda.hcl
  anda/multimedia/rtaudio/anda.hcl
  anda/multimedia/zrythm/anda.hcl
Labels: sync-f41, sync-el10

#2757 fix: rgbds
  anda/devs/rgbds/terra-rgbds.spec
Labels: sync-f40, sync-f41, sync-el10

#2836 fix(ci): switch to ubuntu-22.04
  .github/workflows/autobuild.yml
  .github/workflows/bootstrap.yml
  .github/workflows/build.yml
  .github/workflows/json-build.yml
  .github/workflows/sync.yml
  .github/workflows/update-branch.yml
  .github/workflows/update-comps.yml
  .github/workflows/update-nightly.yml
  .github/workflows/update-weekly.yml
  .github/workflows/update.yml
Labels: sync-f40, sync-f41, sync-el10

#2905 fix: swww
  anda/desktops/waylands/swww/swww.spec
Labels: sync-f40, sync-f41, sync-el10

#2904 Add: v4l2-relayd
  anda/fusion/v4l2-relayd/0000-set-new-offset.patch
  anda/fusion/v4l2-relayd/anda.hcl
  anda/fusion/v4l2-relayd/update.rhai
  anda/fusion/v4l2-relayd/v4l2-relayd.preset
  anda/fusion/v4l2-relayd/v4l2-relayd.spec
Labels: sync-f40, sync-f41, sync-el10

#2897 add: sheldon
  anda/tools/sheldon/anda.hcl
  anda/tools/sheldon/sheldon.spec
  anda/tools/sheldon/update.rhai
Labels: sync-f40, sync-f41, sync-el10

#2894 fix(ci): subrepo labels
  .github/workflows/autobuild.yml
  .github/workflows/json-build.yml
Labels: sync-f41, sync-el10

#2912 Add: v4l2loopback (not kmod), move v4l2loopback out of Fusion tree
  anda/system/kmod-v4l2loopback/anda.hcl
  anda/system/kmod-v4l2loopback/kmod-v4l2loopback.spec
  anda/system/kmod-v4l2loopback/update.rhai
  anda/system/kmod-v4l2loopback/v4l2loopback-kmod.spec
  anda/system/v4l2-relayd/0000-set-new-offset.patch
  anda/system/v4l2-relayd/anda.hcl
  anda/system/v4l2-relayd/update.rhai
  anda/system/v4l2-relayd/v4l2-relayd.preset
  anda/system/v4l2-relayd/v4l2-relayd.spec
  anda/system/v4l2loopback/anda.hcl
  anda/system/v4l2loopback/modprobe-d-98-v4l2loopback.conf
  anda/system/v4l2loopback/modules-load-d-v4l2loopback.conf
  anda/system/v4l2loopback/update.rhai
  anda/system/v4l2loopback/v4l2loopback.spec
Labels: sync-f40, sync-frawhide, sync-f41

#2932 Add Terra Mesa and NVIDIA to release-extras package (disabled by default)
  anda/terra/release/terra-mesa.repo
  anda/terra/release/terra-nvidia.repo
  anda/terra/release/terra-release.spec
Labels: sync-frawhide, sync-f41

#2941 Force all multilib packages to build inside a mock chroot
  anda/games/gamescope-legacy/anda.hcl
  anda/games/gamescope/anda.hcl
  anda/lib/mesa/anda.hcl
  anda/lib/nvidia/cuda-profiler/anda.hcl
  anda/lib/nvidia/cuda-sanitizer/anda.hcl
  anda/misc/extest/anda.hcl
  anda/system/nvidia/libva-nvidia-driver/anda.hcl
Labels: sync-f40, sync-frawhide, sync-f41

#2940 fix: nvidia-driver
  anda/system/nvidia/nvidia-driver/anda.hcl
Labels: sync-f40, sync-frawhide, sync-f41

#2935 fix(yt-dlp): try using mock instead
  anda/tools/yt-dlp/anda.hcl
Labels: sync-f40, sync-f41, sync-el10

#2949 fix: mkfstab
  anda/langs/nim/mkfstab/mkfstab.spec
Labels: bug, sync-f40, sync-f41, sync-el10

#2955 fix(nim): do not symlink the dist directory
  anda/langs/nim/nim-nightly/nim-nightly.spec
  anda/langs/nim/nim/nim.spec
Labels: bug

#2954 Add: libnvidia-container
  anda/lib/nvidia/libnvidia-container/anda.hcl
  anda/lib/nvidia/libnvidia-container/fix-debug-packages.patch
  anda/lib/nvidia/libnvidia-container/fix-makefile.patch
  anda/lib/nvidia/libnvidia-container/fix-revision.patch
  anda/lib/nvidia/libnvidia-container/libnvidia-container.spec
  anda/lib/nvidia/libnvidia-container/update.rhai
Labels: sync-frawhide, sync-f41

#2963 Add: AAC
  anda/lib/fdk-aac/anda.hcl
  anda/lib/fdk-aac/fdk-aac.spec
  anda/lib/fdk-aac/update.rhai
  anda/lib/vo-aacenc/anda.hcl
  anda/lib/vo-aacenc/update.rhai
  anda/lib/vo-aacenc/vo-aacenc.spec
Labels: sync-frawhide, sync-f41

#2964 Add: NVIDIA Container Toolkit
  anda/system/nvidia/nvidia-container-toolkit/anda.hcl
  anda/system/nvidia/nvidia-container-toolkit/nvidia-container-toolkit.spec
  anda/system/nvidia/nvidia-container-toolkit/update.rhai
Labels: sync-frawhide, sync-f41

#2962 Add: libfreeaptx
  anda/lib/libfreeaptx/anda.hcl
  anda/lib/libfreeaptx/libfreeaptx.spec
  anda/lib/libfreeaptx/update.rhai
Labels: sync-frawhide, sync-f41

#2924 [IPU6 Part 2] Add: ipu6-camera-hal
  anda/system/ipu6-camera-hal/0000-lib-path.patch
  anda/system/ipu6-camera-hal/0001-CMakeLists-fixes.patch
  anda/system/ipu6-camera-hal/0002-set-mainline.patch
  anda/system/ipu6-camera-hal/60-intel-ipu6.rules
  anda/system/ipu6-camera-hal/anda.hcl
  anda/system/ipu6-camera-hal/icamera_ipu6_isys.conf
  anda/system/ipu6-camera-hal/ipu6-camera-hal.spec
  anda/system/ipu6-camera-hal/ipu6-driver-select.sh
  anda/system/ipu6-camera-hal/v4l2-relayd-adl
  anda/system/ipu6-camera-hal/v4l2-relayd-tgl
Labels: sync-frawhide, sync-f41

#2971 Fix (nvidia-container-toolkit): Remove JSON file, add post scriptlet
  anda/system/nvidia/nvidia-container-toolkit/nvidia-container-toolkit.spec
Labels: sync-frawhide, sync-f41

#2969 fix: keyd
  anda/tools/keyd/keyd.spec
Labels: sync-f40, sync-f41, sync-el10

#2977 Add: rtmpdump
  anda/lib/rtmpdump/anda.hcl
  anda/lib/rtmpdump/rtmpdump.spec
Labels: sync-frawhide, sync-f41

#2953 Fix: v4l2-relayd and ipu6-camera-bins builds
  anda/lib/ipu6-camera-bins/anda.hcl
  anda/lib/ipu6-camera-bins/ipu6-camera-bins.spec
  anda/system/v4l2-relayd/0000-set-new-offset.patch
  anda/system/v4l2-relayd/update.rhai
  anda/system/v4l2-relayd/v4l2-relayd.spec
Labels: sync-frawhide, sync-f41

#2982 Fix (wl-kmod): kmodtool repo
  anda/system/wl-kmod/wl-kmod.spec
Labels: bug, sync-f40, sync-f41, sync-el10

#2984 fix: v4l2loopback
  anda/system/kmod-v4l2loopback/anda.hcl
  anda/system/kmod-v4l2loopback/kmod-v4l2loopback.spec
  anda/system/kmod-v4l2loopback/update.rhai
  anda/system/v4l2loopback/v4l2loopback.spec
Labels: sync-frawhide, sync-f41

#2986 fix: dive
  anda/langs/nim/dive/umdive.spec
Labels: bug, sync-f40, sync-f41, sync-el10

#2017 bump: choosenim
  anda/langs/nim/choosenim/choosenim.spec
  anda/langs/nim/choosenim/update.rhai
Labels: update, sync-f40, sync-f41, sync-el10

#3006 fix(cuda-cudnn): update.rhai
  anda/lib/nvidia/cuda-cudnn/update.rhai
Labels: bug, update, sync-f40, sync-f41, sync-el10

#3012 add: sticky
  anda/apps/sticky/anda.hcl
  anda/apps/sticky/point-executable-to-sitepackages-directory.patch
  anda/apps/sticky/remove-meson-postinstall-script.patch
  anda/apps/sticky/sticky.spec
Labels: new

#3013 Fix (protobuf): Move to Extras
  anda/langs/python/protobuf/anda.hcl
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10

#2890 Fix (Ghostty): Additional licenses, new upstream files
  anda/devs/ghostty/nightly/ghostty-nightly.spec
  anda/devs/ghostty/stable/ghostty.spec
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10

#3021 feat(ghostty): adhere closer to packaging guidelines for tip
  anda/devs/ghostty/nightly/ghostty-nightly.spec
Labels: sync-frawhide, sync-f41

#3027 Add some dependencies for FFmpeg
  anda/lib/davs2/anda.hcl
  anda/lib/davs2/davs2.spec
  anda/lib/davs2/update.rhai
  anda/lib/nvidia/libnpp/anda.hcl
  anda/lib/nvidia/libnpp/libnpp.spec
  anda/lib/nvidia/libnpp/nppc.pc
  anda/lib/nvidia/libnpp/nppi.pc
  anda/lib/nvidia/libnpp/nppial.pc
  anda/lib/nvidia/libnpp/nppicc.pc
  anda/lib/nvidia/libnpp/nppicom.pc
  anda/lib/nvidia/libnpp/nppidei.pc
  anda/lib/nvidia/libnpp/nppif.pc
  anda/lib/nvidia/libnpp/nppig.pc
  anda/lib/nvidia/libnpp/nppim.pc
  anda/lib/nvidia/libnpp/nppist.pc
  anda/lib/nvidia/libnpp/nppisu.pc
  anda/lib/nvidia/libnpp/nppitc.pc
  anda/lib/nvidia/libnpp/npps.pc
  anda/lib/nvidia/libnpp/update.rhai
  anda/lib/xavs/anda.hcl
  anda/lib/xavs/xavs-cflags.patch
  anda/lib/xavs/xavs.spec
  anda/multimedia/kvazaar/anda.hcl
  anda/multimedia/kvazaar/kvazaar.spec
  anda/multimedia/uavs3d/anda.hcl
  anda/multimedia/uavs3d/uavs3d-soname.patch
  anda/multimedia/uavs3d/uavs3d.spec
  anda/multimedia/vvenc/anda.hcl
  anda/multimedia/vvenc/vvenc.spec
  anda/system/decklink/anda.hcl
  anda/system/decklink/decklink-devel.spec
Labels: sync-frawhide, sync-f41

#2991 add: mjpegtools
  anda/multimedia/mjpegtools/anda.hcl
  anda/multimedia/mjpegtools/mjpegtools.spec
Labels: sync-frawhide, sync-f41

#2993 Fix: Multimedia Arches
  anda/lib/libfreeaptx/anda.hcl
  anda/lib/rtmpdump/anda.hcl
  anda/lib/vo-aacenc/anda.hcl
  anda/multimedia/faad2/anda.hcl
  anda/multimedia/ffmpeg/anda.hcl
  anda/multimedia/x264-bootstrap/anda.hcl
  anda/multimedia/x264/anda.hcl
  anda/multimedia/x265/anda.hcl
  anda/multimedia/x265/x265-high-bit-depth-soname.patch
  anda/multimedia/x265/x265-pic.patch
  anda/multimedia/x265/x265-pkgconfig_path_fix.patch
  anda/multimedia/x265/x265-sei-length-crash-fix.patch
  anda/multimedia/x265/x265.spec
Labels: sync-frawhide, sync-f41

#3033 add: kmonad
  anda/tools/kmonad/anda.hcl
  anda/tools/kmonad/kmonad.spec
  anda/tools/kmonad/update.rhai
Labels: new

#3043 Fix (conflict/other issues): Switch Steam to the correct arch
  anda/games/steam/anda.hcl
  anda/games/steam/steam.spec
Labels: sync-frawhide, sync-f41

#3051 Fix (walker): Remove gtk4-layer-shell dependency
  anda/desktops/waylands/walker/golang-github-abenz1267-walker.spec
Labels: sync-f40, sync-frawhide, sync-f41

#3059 Fix: gamescope-session
  anda/games/gamescope-session/gamescope-session.spec
Labels: sync-f40, sync-f41, sync-el10

#3037 Feat (multimedia arches): i686 builds for FFMPEG deps
  anda/lib/davs2/anda.hcl
  anda/lib/davs2/davs2.spec
  anda/lib/xavs/anda.hcl
  anda/lib/xavs/xavs.spec
  anda/multimedia/kvazaar/anda.hcl
  anda/multimedia/uavs3d/anda.hcl
  anda/multimedia/uavs3d/i686-build-fix.patch
  anda/multimedia/uavs3d/uavs3d.spec
  anda/multimedia/vvenc/anda.hcl
Labels: sync-frawhide

#3048 Remove: terra-sddm and terra-wl-clipboard
  anda/desktops/sddm/0001-Delay-for-logind-and-fallback-to-seat0.patch
  anda/desktops/sddm/README.scripts
  anda/desktops/sddm/anda.hcl
  anda/desktops/sddm/sddm-0.18.0-environment_file.patch
  anda/desktops/sddm/sddm-0.20.0-fedora_config.patch
  anda/desktops/sddm/sddm-0.21.0-qt6greeter.patch
  anda/desktops/sddm/sddm-PR1876.patch
  anda/desktops/sddm/sddm-autologin.pam
  anda/desktops/sddm/sddm-greeter.pam
  anda/desktops/sddm/sddm-rpmostree-tmpfiles-hack.patch
  anda/desktops/sddm/sddm-systemd-sysusers.conf
  anda/desktops/sddm/sddm-x11.conf
  anda/desktops/sddm/sddm.conf
  anda/desktops/sddm/sddm.pam
  anda/desktops/sddm/sddm.sysconfig
  anda/desktops/sddm/terra-sddm.spec
  anda/desktops/sddm/update.rhai
  anda/tools/wl-clipboard/anda.hcl
  anda/tools/wl-clipboard/terra-wl-clipboard.spec
  anda/tools/wl-clipboard/update.rhai
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10

#3045 Change (Anki): Move to Extras, minor dep changes
  anda/apps/anki-bin/anda.hcl
  anda/apps/anki-bin/anki-bin.spec
  anda/apps/anki/anda.hcl
  anda/apps/anki/anki.spec
Labels: sync-f40, sync-f41, sync-el10

#3042 fix(yt-dlp): follow upstream versioning + rename package to -git
  anda/tools/yt-dlp/anda.hcl
  anda/tools/yt-dlp/update.rhai
  anda/tools/yt-dlp/yt-dlp-git.spec
Labels: sync-f41

#3071 bump: blackbox-terminal
  anda/apps/blackbox-terminal/blackbox-terminal.spec
  anda/apps/blackbox-terminal/update.rhai
Labels: sync-f40, sync-f41

#3078 Fix (opentabletdriver): Add missing file
  anda/system/opentabletdriver-nightly/opentabletdriver-nightly.spec
  anda/system/opentabletdriver/opentabletdriver.spec
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10

#3075 Fix (walker): Revert #3051, follow upstream build guidelines, enable debug packages
  anda/desktops/waylands/walker/golang-github-abenz1267-walker.spec
Labels: sync-f40, sync-frawhide, sync-f41

#3031 feat(ci): use github arm64 runners
  .github/workflows/autobuild.yml
  .github/workflows/json-build.yml
Labels: sync-f40, sync-f41, sync-el10

#3086 Revert "feat(ci): use github arm64 runners (#3031)"
  .github/workflows/autobuild.yml
  .github/workflows/json-build.yml
Labels: sync-f40, sync-f41

#3085 Fix: NVIDIA Container Toolkit Post-script, add Podman
  anda/system/nvidia/nvidia-container-toolkit/nvidia-container-toolkit.spec
Labels: sync-frawhide, sync-f41

#3076 fix(yt-dlp): obsoletes for shell completion subpackages
  anda/tools/yt-dlp/yt-dlp-git.spec
Labels: sync-f41

#3090 fix: SIPA fonts licensing, Deprecate `TH Sarabun` (#2482)
  anda/fonts/sipa/15-supercede-sarabun.conf
  anda/fonts/sipa/sipa-fonts.spec
Labels: sync-f40, sync-frawhide, sync-f41

#3050 Remove duplicate packages from Fedora
  anda/docker/containerd/.gitignore
  anda/docker/containerd/0001-Add-reaper-StartLocked.patch
  anda/docker/containerd/0001-Revert-commit-for-Windows-metrics.patch
  anda/docker/containerd/0001-Use-typeurl.Any-instead-of-github.com-gogo-protobuf-.patch
  anda/docker/containerd/0001-opencontainers-image-spec-v1.1.0-rc3.patch
  anda/docker/containerd/0002-Remove-windows-only-dep.patch
  anda/docker/containerd/anda.hcl
  anda/docker/containerd/changelog
  anda/docker/containerd/containerd.spec
  anda/docker/containerd/containerd.toml
  anda/docker/containerd/update.rhai
  anda/docker/moby-buildx/anda.hcl
  anda/docker/moby-buildx/moby-buildx.spec
  anda/docker/moby-buildx/update.rhai
  anda/docker/moby-compose/anda.hcl
  anda/docker/moby-compose/moby-compose.spec
  anda/docker/moby-compose/update.rhai
  anda/games/gamescope-legacy/0001-cstdint.patch
  anda/games/gamescope-legacy/anda.hcl
  anda/games/gamescope-legacy/gamescope-legacy.spec
  anda/games/gamescope-legacy/legacy-720p.patch
  anda/games/gamescope-legacy/stb.pc
  anda/games/gamescope-legacy/v2-0001-always-send-ctrl-1-2-to-steam-s-wayland-session.patch
  anda/lib/dbus-test-runner/anda.hcl
  anda/lib/dbus-test-runner/dbus-test-runner.spec
  anda/lib/dbus-test-runner/update.rhai
  anda/lib/gtk4-layer-shell/anda.hcl
  anda/lib/gtk4-layer-shell/gtk4-layer-shell.spec
  anda/lib/gtk4-layer-shell/update.rhai
  anda/lib/marble-gtk/anda.hcl
  anda/lib/marble-gtk/marble-gtk.spec
  anda/lib/marble-gtk/update.rhai
  anda/lib/pqmarble/anda.hcl
  anda/lib/pqmarble/pqmarble.spec
  anda/lib/pqmarble/update.rhai
  anda/misc/uxplay/anda.hcl
  anda/misc/uxplay/update.rhai
  anda/misc/uxplay/uxplay.spec
  anda/system/mesa-freeworld/Mesa-MLAA-License-Clarification-Email.txt
  anda/system/mesa-freeworld/anda.hcl
  anda/system/mesa-freeworld/mesa-freeworld.spec
  anda/system/mesa-freeworld/org.mesa3d.vaapi.freeworld.metainfo.xml
  anda/system/mesa-freeworld/org.mesa3d.vdpau.freeworld.metainfo.xml
  anda/system/mesa-freeworld/update.rhai
Labels: sync-f41

#3099 add: matugen
  anda/desktops/waylands/matugen/anda.hcl
  anda/desktops/waylands/matugen/rust-matugen.spec
  anda/desktops/waylands/matugen/update.rhai
Labels: sync-f40, sync-f41, sync-el10

#3100 chore: remove ruff maturin libindicator
  anda/langs/python/ruff/anda.hcl
  anda/langs/python/ruff/python3-ruff.spec
  anda/langs/python/ruff/update.rhai
  anda/langs/rust/maturin/anda.hcl
  anda/langs/rust/maturin/rust-terra-maturin.spec
  anda/langs/rust/maturin/update.rhai
  anda/lib/libindicator/anda.hcl
  anda/lib/libindicator/terra-libindicator.spec
Labels: sync-f41

#3106 fix(blackbox-terminal): move to terra-extras
  anda/apps/blackbox-terminal/anda.hcl
Labels: sync-f41

#3070 fix: bat-extras
  anda/devs/bat-extras/anda.hcl
  anda/devs/bat-extras/bat-extras.spec
  anda/devs/bat-extras/update.rhai
Labels: sync-f40, sync-f41

#3028 Fix (ipu6-camera-hal): Redo spec for upstream changes/fix GStreamer builds
  anda/system/ipu6-camera-hal/0000-lib-path.patch
  anda/system/ipu6-camera-hal/60-intel-ipu6.rules
  anda/system/ipu6-camera-hal/ipu6-camera-hal.spec
  anda/system/ipu6-camera-hal/ipu6-driver-select.sh
Labels: sync-frawhide

#3111 Change (Steam): Added libei(s) weak deps, fixed ISA flags, some other small changes from gaming distros
  anda/games/steam/steam.spec
  anda/games/steam/steamrestart.sh
Labels: sync-f40, sync-frawhide, sync-f41

#3113 fix(nushell): conflict with fedora package
  anda/langs/rust/nushell/nushell.spec
Labels: sync-f40, sync-f41, sync-el10

#3116 chore: remove oxipng
  anda/langs/rust/oxipng/anda.hcl
  anda/langs/rust/oxipng/oxipng-fix-metadata-auto.diff
  anda/langs/rust/oxipng/rust-oxipng.spec
  anda/langs/rust/oxipng/update.rhai
Labels: sync-f41

#3127 remove: blackbox-terminal
  anda/apps/blackbox-terminal/anda.hcl
  anda/apps/blackbox-terminal/blackbox-terminal.spec
  anda/apps/blackbox-terminal/update.rhai
Labels: sync-f41

#3120 Change: Make `steam-devices` noarch
  anda/games/steam/steam.spec
Labels: sync-f40, sync-frawhide, sync-f41

#3126 chore: remove remaining terra-* packages
  anda/devs/blueprint-compiler/anda.hcl
  anda/devs/blueprint-compiler/terra-blueprint-compiler.spec
  anda/devs/blueprint-compiler/update.rhai
  anda/devs/rgbds/anda.hcl
  anda/devs/rgbds/terra-rgbds.spec
  anda/devs/rgbds/update.rhai
  anda/langs/rust/nushell/anda.hcl
  anda/langs/rust/nushell/nushell.spec
  anda/langs/rust/nushell/update.rhai
  anda/lib/placebo/anda.hcl
  anda/lib/placebo/terra-libplacebo.spec
  anda/lib/placebo/update.rhai
Labels: sync-f41

#3121 Fix (Espanso): Drop migrate
  anda/tools/espanso-wayland/espanso-wayland.spec
  anda/tools/espanso-x11/espanso-x11.spec
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10

#3110 Fix (libde265): Label Mock correctly
  anda/lib/libde265/anda.hcl
  anda/lib/libde265/libde265.spec
Labels: sync-frawhide

#3143 fix: youtube-music
  anda/apps/youtube-music/anda.hcl
  anda/apps/youtube-music/youtube-music.spec
Labels: sync-f40, sync-frawhide, sync-f41

#3140 update: minecraft-java
  anda/games/minecraft-java/minecraft-java.spec
Labels: sync-f40, sync-frawhide, sync-f41

#3148 fix: maple-fonts
  anda/fonts/maple/maple-fonts.spec
Labels: sync-f40, sync-f41

#3142 chore: remove pop-launcher
  anda/langs/rust/pop-launcher/.gitignore
  anda/langs/rust/pop-launcher/0001-Copy-instead-of-symlink.patch
  anda/langs/rust/pop-launcher/anda.hcl
  anda/langs/rust/pop-launcher/pop-launcher.spec
  anda/langs/rust/pop-launcher/prepare.sh
  anda/langs/rust/pop-launcher/umpkg.cfg
  anda/langs/rust/pop-launcher/umpkg.toml
  anda/langs/rust/pop-launcher/update.rhai
Labels: sync-f41

#3136 Change (Steam): Obsoletes/Provides
  anda/games/steam/steam.spec
Labels: sync-f40, sync-frawhide, sync-f41

#3122 Fix (Ghostty): New build flags for `.terminfo` and `.termcap`
  anda/devs/ghostty/nightly/ghostty-nightly.spec
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10

#3158 fix(maple-fonts): rpm < 4.20 limitation
  anda/fonts/maple/maple-fonts.spec
  anda/fonts/maple/update.rhai
Labels: sync-f40, sync-f41

#3170 add: owl
  anda/desktops/owl/anda.hcl
  anda/desktops/owl/owl.spec
  anda/desktops/owl/update.rhai
Labels: sync-f40, sync-f41

#3168 fix(maple-fonts): fix string manipulation of upstream version string
  anda/fonts/maple/maple-fonts.spec
Labels: nosync
