Repository terrapkg/packages, pull requests merged in 2025-02, with the labels that each got.

#3174 Add: geteltorito
  anda/tools/geteltorito/anda.hcl
  anda/tools/geteltorito/geteltorito.spec
  anda/tools/geteltorito/update.rhai
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10

#3175 Add: abuild
  anda/tools/abuild/abuild.spec
  anda/tools/abuild/anda.hcl
  anda/tools/abuild/update.rhai
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10

#3182 Cleanup: nvidia-container-toolkit
  anda/system/nvidia/nvidia-container-toolkit/nvidia-container-toolkit.spec
Labels: sync-f41

#3167 Add: java-binfmt
  anda/tools/java-binfmt/anda.hcl
  anda/tools/java-binfmt/java-binfmt.spec
  anda/tools/java-binfmt/update.rhai
Labels: sync-f40, sync-f41

#3173 feat(ghostty): Changes, fixes, and more
  anda/devs/ghostty/nightly/ghostty-nightly.spec
  anda/devs/ghostty/nightly/update.rhai
  anda/devs/ghostty/stable/ghostty.spec
  anda/devs/ghostty/stable/no-strip.diff
Labels: sync-f40, sync-f41, sync-el10

#3193 add: swaylock-effects
  anda/desktops/waylands/swaylock-effects/anda.hcl
  anda/desktops/waylands/swaylock-effects/swaylock-effects.spec
Labels: sync-f40, sync-f41

#3198 Fix Issues with KF6-KIO
  anda/desktops/kde/kf6-kio/kf6-kio.spec
Labels: sync-f41

#3156 feat(ci): use github arm64 runners
  .github/workflows/autobuild.yml
  .github/workflows/json-build.yml
Labels: sync-f40, sync-f41, sync-el10

#3202 feat(kf6-kio): per branch update scripts
  anda/desktops/kde/kf6-kio/anda.hcl
  anda/desktops/kde/kf6-kio/update.rhai
  andax/bump_extras.rhai
Labels: sync-f40, sync-f41, sync-el10

#3208 Fix (java-binfmt): Dependency typo I can't believe I made
  anda/tools/java-binfmt/java-binfmt.spec
Labels: sync-f40, sync-f41

#3204 feat(gnome-shell): update scripts
  anda/desktops/gnome/gnome-shell/anda.hcl
  anda/desktops/gnome/gnome-shell/gnome-shell.spec
  anda/desktops/gnome/gnome-shell/update.rhai
Labels: sync-f41

#3124 fix(tdlib): Remove `rm` step for RPMBuild
  anda/lib/tdlib/tdlib-nightly.spec
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10

#3207 add: fluent-kde-theme
  anda/themes/fluent-kde-theme/anda.hcl
  anda/themes/fluent-kde-theme/fluent-kde-theme.spec
  anda/themes/fluent-kde-theme/update.rhai
Labels: sync-f40, sync-f41, sync-el10

#3221 Fix (Walker): Workaround for F40 Go not producing debug packages
  anda/desktops/waylands/walker/golang-github-abenz1267-walker.spec
Labels: sync-f40, sync-f41, sync-el10

#3215 Fix: obsoletes and bump release to surface-dtx-daemon
  anda/system/surface-dtx-daemon/surface-dtx-daemon.spec
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10

#3251 Fix: Move CUDA to NVIDIA subrepo
  anda/lib/nvidia/compat-nvidia-repo/anda.hcl
  anda/lib/nvidia/cuda-cccl/anda.hcl
  anda/lib/nvidia/cuda-cudart/anda.hcl
  anda/lib/nvidia/cuda-cudnn/anda.hcl
  anda/lib/nvidia/cuda-cuobjdump/anda.hcl
  anda/lib/nvidia/cuda-cupti/anda.hcl
  anda/lib/nvidia/cuda-cuxxfilt/anda.hcl
  anda/lib/nvidia/cuda-gcc/anda.hcl
  anda/lib/nvidia/cuda-gdb/anda.hcl
  anda/lib/nvidia/cuda-nvdisasm/anda.hcl
  anda/lib/nvidia/cuda-nvml/anda.hcl
  anda/lib/nvidia/cuda-nvprof/anda.hcl
  anda/lib/nvidia/cuda-nvprune/anda.hcl
  anda/lib/nvidia/cuda-nvrtc/anda.hcl
  anda/lib/nvidia/cuda-nvtx/anda.hcl
  anda/lib/nvidia/cuda-profiler/anda.hcl
  anda/lib/nvidia/cuda-sanitizer/anda.hcl
  anda/lib/nvidia/cuda/anda.hcl
  anda/lib/nvidia/libcublas/anda.hcl
  anda/lib/nvidia/libcudla/anda.hcl
  anda/lib/nvidia/libcufft/anda.hcl
  anda/lib/nvidia/libcurand/anda.hcl
  anda/lib/nvidia/libcusparse/anda.hcl
  anda/lib/nvidia/libcusparselt/anda.hcl
  anda/lib/nvidia/libnpp/anda.hcl
  anda/lib/nvidia/libnvfatbin/anda.hcl
  anda/lib/nvidia/libnvjpeg/anda.hcl
Labels: sync-f41

#3242 add: EmulationStation-DE
  anda/games/emulationstation-de/anda.hcl
  anda/games/emulationstation-de/emulationstation-de.spec
  anda/games/emulationstation-de/update.rhai
Labels: sync-f40, sync-f41, sync-el10

#3256 fix: ruffle
  anda/apps/ruffle/desktop_file_patch.diff
  anda/apps/ruffle/ruffle-nightly.spec
Labels: bug, sync-f40, sync-f41, sync-el10

#3254 add: golang-github-dhth-prs
  anda/langs/go/prs/anda.hcl
  anda/langs/go/prs/golang-github-dhth-prs.spec
  anda/langs/go/prs/update.rhai
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10

#3253 add: bun-bin
  anda/devs/bun/anda.hcl
  anda/devs/bun/bun-bin.spec
  anda/devs/bun/update.rhai
Labels: sync-f40, sync-f41, sync-el10

#3255 fix: mise
  anda/tools/buildsys/mise/mise-fix-metadata-auto.diff
  anda/tools/buildsys/mise/rust-mise.spec
Labels: bug, sync-f40, sync-f41, sync-el10

#3271 fix(budgie-extras): remove patch (fixed in upstream)
  anda/desktops/budgie/budgie-extras/0001-fix-weathershow-desktop-widget-icon-path.patch
  anda/desktops/budgie/budgie-extras/budgie-extras.spec
Labels: bug, sync-f40, sync-f41, sync-el10

#3275 Fix (scenefx): Add missing build dependencies
  anda/lib/scenefx/scenefx.spec
Labels: sync-f40, sync-f41, sync-el10

#3277 Fix (anki-bin): New files
  anda/apps/anki-bin/anki-bin.spec
Labels: sync-f40, sync-f41, sync-el10

#3286 fix(cuda-gcc): update.rhai
  anda/lib/nvidia/cuda-gcc/update.rhai
Labels: bug, update, sync-f40, sync-frawhide, sync-f41, sync-el10

#3288 fix(openh264): soname bump
  anda/lib/openh264/openh264.spec
Labels: sync-f40, sync-f41

#3294 feat(gstreamer1-plugins-bad): update.rhai
  anda/multimedia/gstreamer1/gstreamer1-plugins-bad/OPENCV_VERSION.txt
  anda/multimedia/gstreamer1/gstreamer1-plugins-bad/gstreamer1-plugins-bad.spec
  anda/multimedia/gstreamer1/gstreamer1-plugins-bad/update.rhai
  andax/bump_extras.rhai
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10

#3056 Feat: uutils-coreutils-replace
  anda/system/uutils-coreutils-replace/.gitignore
  anda/system/uutils-coreutils-replace/anda.hcl
  anda/system/uutils-coreutils-replace/coreutils-colorls.csh
  anda/system/uutils-coreutils-replace/coreutils-colorls.sh
  anda/system/uutils-coreutils-replace/coreutils-fix-metadata.diff
  anda/system/uutils-coreutils-replace/coreutils-fix-seq-neg-num-tests.diff
  anda/system/uutils-coreutils-replace/update.rhai
  anda/system/uutils-coreutils-replace/uutils-coreutils-replace.spec
  anda/system/uutils-coreutils/anda.hcl
  anda/system/uutils-coreutils/uutils-coreutils.spec
Labels: sync-frawhide

#3300 flow: temporarily stop building from latest commit
  anda/devs/flow/update.rhai
Labels: nosync

#3287 fix(ffmpeg): update.rhai
  anda/multimedia/ffmpeg/ffmpeg.spec
  anda/multimedia/ffmpeg/update.rhai
Labels: sync-f40, sync-f41, sync-el10

#3307 feat(gstreamer1*): update.rhai
  anda/multimedia/gstreamer1/gstreamer1-plugin-libav/anda.hcl
  anda/multimedia/gstreamer1/gstreamer1-plugin-libav/update.rhai
  anda/multimedia/gstreamer1/gstreamer1-plugins-bad/anda.hcl
  anda/multimedia/gstreamer1/gstreamer1-plugins-ugly/anda.hcl
  anda/multimedia/gstreamer1/gstreamer1-plugins-ugly/update.rhai
Labels: bug, sync-f40, sync-frawhide, sync-f41, sync-el10

#3312 fix: legcord
  anda/apps/legcord-bin/anda.hcl
  anda/apps/legcord-bin/legcord-bin.spec
  anda/apps/legcord-bin/legcord.png
  anda/apps/legcord-bin/update.rhai
  anda/apps/legcord/legcord-bin/legcord-bin.spec
  anda/apps/legcord/nightly/legcord-nightly.spec
  anda/apps/legcord/stable/legcord.spec
Labels: sync-f40, sync-f41, sync-f42

#3301 Fix: Update script for Mesa, bump Mesa back down
  anda/lib/mesa/mesa.spec
  anda/lib/mesa/update.rhai
Labels: sync-f41

#3324 youtube-music: fix WMClass
  anda/apps/youtube-music/youtube-music.desktop
  anda/apps/youtube-music/youtube-music.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3322 Feat (Steam): Changes for F42+
  anda/games/steam/steam.spec
Labels: sync-f42

#3341 fix: fluent-icon-theme
  anda/themes/fluent-icon-theme/fluent-icon-theme.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3339 chore(comps): remove pantheon
  comps.xml
Labels: sync-el10, sync-f42

#3357 add: lowfi
  anda/devs/lowfi/anda.hcl
  anda/devs/lowfi/rust-lowfi.spec
  anda/devs/lowfi/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3352 fix(chromebook-usbc-fix): specify x86_64 arch in spec
  anda/system/chromebook-usbc-fix/anda.hcl
  anda/system/chromebook-usbc-fix/chromebook-usbc-fix.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3355 fix(umu-launcher): builddep python3-hatch-vcs
  anda/games/umu/umu-launcher.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3354 fix: fuc
  anda/tools/fuc/fuc.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3375 remove: latte-dock-nightly
  anda/desktops/kde/latte-dock-nightly/anda.hcl
  anda/desktops/kde/latte-dock-nightly/latte-dock-nightly.spec
  anda/desktops/kde/latte-dock-nightly/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3369 add: xplr
  anda/langs/rust/xplr/anda.hcl
  anda/langs/rust/xplr/rust-xplr.spec
  anda/langs/rust/xplr/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3380 fix(umu-launcher): urllib3 dependency issues on <= 41
  anda/games/umu/anda.hcl
  anda/games/umu/umu-launcher.spec
Labels: sync-f40, sync-f41, sync-f42

#3368 Add: NeoHtop
  anda/apps/neohtop/NeoHtop.desktop
  anda/apps/neohtop/anda.hcl
  anda/apps/neohtop/neohtop.spec
  anda/apps/neohtop/update.rhai
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10, sync-f42

#3396 chore(ci): rename arm64-lg
  .github/workflows/autobuild.yml
  .github/workflows/bootstrap.yml
  .github/workflows/build.yml
  .github/workflows/json-build.yml
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3395 fix(neovide): get source from crate and add dependencies
  anda/devs/neovide/neovide.spec
  anda/devs/neovide/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3407 fix: scenefx
  anda/lib/scenefx/scenefx.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3401 fix(carla): version string
  anda/multimedia/carla/Carla-nightly.spec
Labels: sync-f41, sync-f42

#3420 fix: Add patch for Intel Battlemage + Valve Gamescope
  anda/lib/mesa/12633.patch
  anda/lib/mesa/mesa.spec
Labels: sync-frawhide, sync-f41, sync-el10, sync-f42

#3423 add: lazygit
  anda/langs/go/lazygit/anda.hcl
  anda/langs/go/lazygit/golang-github-jesseduffield-lazygit.spec
  anda/langs/go/lazygit/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3430 fix(lightly-qt*): make update.rhai scripts actually function
  anda/themes/lightly-qt5/anda.hcl
  anda/themes/lightly-qt5/update.rhai
  anda/themes/lightly-qt6/anda.hcl
  anda/themes/lightly-qt6/update.rhai
Labels: bug, update, sync-f40, sync-frawhide, sync-f41, sync-el10, sync-f42

#3432 Change xavs URL to https from http
  anda/lib/xavs/xavs.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3433 Update vo-aacenc URL and source links to HTTPS
  anda/lib/vo-aacenc/vo-aacenc.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3351 fix(audacity-freeworld): update.rhai function
  anda/apps/audacity-freeworld/audacity-freeworld.spec
  anda/apps/audacity-freeworld/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3452 fix: audacity-freeworld
  anda/apps/audacity-freeworld/audacity-freeworld.spec
  anda/apps/audacity-freeworld/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3306 Fix (Ghostty Nightly): File name change and conditional epoch
  anda/devs/ghostty/nightly/ghostty-nightly.spec
  anda/devs/ghostty/nightly/update.rhai
  anda/devs/ghostty/stable/ghostty.spec
Labels: sync-f40, sync-f41, sync-f42

#3431 fix(feishin): try newer nodejs20-npm
  anda/apps/feishin/feishin.spec
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10, sync-f42

#3465 chore: remove authy
  anda/apps/authy/anda.hcl
  anda/apps/authy/authy.spec
  anda/apps/authy/update.rhai.bak
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3471 add: dotherside
  anda/lib/dotherside/DOtherSide.spec
  anda/lib/dotherside/anda.hcl
  anda/lib/dotherside/update.rhai
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10, sync-f42

#3477 Fix: Steam for F41 and below (REAL)
  anda/games/steam/steam.spec
Labels: sync-f40, sync-el10

#3476 fix(dotherside): dep on cmake(Qt6XcbQpaPrivate)
  anda/lib/dotherside/DOtherSide.spec
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10, sync-f42

#3490 add: astal
  anda/lib/astal/astal/anda.hcl
  anda/lib/astal/astal/astal.spec
  anda/lib/astal/astal/update.rhai
  andax/bump_extras.rhai
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10, sync-f42

#3493 add: astal-gtk
  anda/lib/astal/astal-gtk/anda.hcl
  anda/lib/astal/astal-gtk/astal-gtk.spec
  anda/lib/astal/astal-gtk/update.rhai
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10, sync-f42

#3508 Change (ghostty-nightly): Use actual Tip version
  anda/devs/ghostty/nightly/ghostty-nightly.spec
  anda/devs/ghostty/nightly/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3509 Fix: v4l2loopback
  anda/system/v4l2loopback/v4l2loopback.spec
Labels: sync-f41, sync-el10, sync-f42

#3523 Fix (ghostty-nightly): New build dependency
  anda/devs/ghostty/nightly/ghostty-nightly.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3524 add: micro-nightly
  anda/devs/micro/anda.hcl
  anda/devs/micro/micro-nightly.spec
  anda/devs/micro/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#3532 fix(andax/bump_extras): funny error
  andax/bump_extras.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3541 feat(nerd-fonts): add missing patched fonts
  anda/fonts/nerd-fonts/nerd-fonts.spec
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10, sync-f42

#3540 Add: MS-Core Fonts
  anda/fonts/cleartype/61-cleartype-calibri.conf
  anda/fonts/cleartype/61-cleartype-cambria.conf
  anda/fonts/cleartype/61-cleartype-candara.conf
  anda/fonts/cleartype/61-cleartype-consolas.conf
  anda/fonts/cleartype/61-cleartype-constantia.conf
  anda/fonts/cleartype/61-cleartype-corbel.conf
  anda/fonts/cleartype/anda.hcl
  anda/fonts/cleartype/cleartype-fonts.spec
  anda/fonts/ms-core-tahoma/61-ms-core-tahoma.conf
  anda/fonts/ms-core-tahoma/anda.hcl
  anda/fonts/ms-core-tahoma/ms-core-tahoma-fonts.spec
  anda/fonts/ms-core-tahoma/post.rhai
  anda/fonts/ms-core/61-ms-core-andale.conf
  anda/fonts/ms-core/61-ms-core-arial.conf
  anda/fonts/ms-core/61-ms-core-comic.conf
  anda/fonts/ms-core/61-ms-core-courier.conf
  anda/fonts/ms-core/61-ms-core-georgia.conf
  anda/fonts/ms-core/61-ms-core-impact.conf
  anda/fonts/ms-core/61-ms-core-times.conf
  anda/fonts/ms-core/61-ms-core-trebuchet.conf
  anda/fonts/ms-core/61-ms-core-verdana.conf
  anda/fonts/ms-core/61-ms-core-webdings.conf
  anda/fonts/ms-core/anda.hcl
  anda/fonts/ms-core/ms-core-fonts.spec
Labels: sync-f41, sync-el10, sync-f42

#3533 feat(kf6-kio,gnome-shell): comply with new tag policies
  anda/desktops/gnome/gnome-shell/gnome-shell.spec
  anda/desktops/kde/kf6-kio/kf6-kio.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3534 add: kanata
  anda/tools/kanata/anda.hcl
  anda/tools/kanata/kanata-fix-metadata-auto.diff
  anda/tools/kanata/rust-kanata.spec
  anda/tools/kanata/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3564 fix: owl/mwc
  anda/desktops/mwc/anda.hcl
  anda/desktops/mwc/mwc.spec
  anda/desktops/mwc/update.rhai
  anda/desktops/owl/update.rhai
Labels: sync-f40, sync-f41, sync-f42

#3566 fix(astal-gtk): use %git_clone instead
  anda/lib/astal/astal-gtk/astal-gtk.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#3510 Add: XONE
  anda/system/xone/akmod/anda.hcl
  anda/system/xone/akmod/update.rhai
  anda/system/xone/akmod/xone-kmod.spec
  anda/system/xone/dkms/anda.hcl
  anda/system/xone/dkms/dkms-no-weak-modules.conf
  anda/system/xone/dkms/dkms-xone.spec
  anda/system/xone/dkms/update.rhai
  anda/system/xone/kmod-common/anda.hcl
  anda/system/xone/kmod-common/modules.conf
  anda/system/xone/kmod-common/update.rhai
  anda/system/xone/kmod-common/xone-kmod-common.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42
