Repository terrapkg/packages, pull requests merged in 2025-04, with the labels that each got.

#4212 fix(ivsc-firmware): Macro and date
  anda/system/ivsc-firmware/anda.hcl
  anda/system/ivsc-firmware/ivsc-firmware.spec
  anda/system/ivsc-firmware/update.rhai
Labels: sync-frawhide, sync-f41, sync-el10

#4221 feat(ivsc-firmware): Include the doc files and a changelog
  anda/system/ivsc-firmware/ivsc-firmware.spec
Labels: sync-f41, sync-el10, sync-f42

#4217 fix(ipu6-camera-bins): Setup and install steps
  anda/lib/ipu6-camera-bins/anda.hcl
  anda/lib/ipu6-camera-bins/ipu6-camera-bins.spec
  anda/lib/ipu6-camera-bins/update.rhai
Labels: sync-frawhide, sync-f41, sync-el10

#4231 Fix: cbfstool
  anda/tools/cbfstool/cbfstool.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4237 Fix: cbfstool again
  anda/tools/cbfstool/cbfstool.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4230 chore: Bump Electron on <= 42
  anda/tools/electron/electron.spec
Labels: sync-f40, sync-f41, sync-el10

#4229 fix(lomiri-ui-toolkit): Update patches and Python subpackage build/install steps
  anda/desktops/lomiri-unity/lomiri-ui-toolkit/lomiri-ui-toolkit.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4228 fix(ipu6-camera-bins): Sed command
  anda/lib/ipu6-camera-bins/ipu6-camera-bins.spec
Labels: sync-f41, sync-el10, sync-f42

#4246 chore(zenpower3): Bump commit to fix on kernel 6.14
  anda/system/zenpower3/zenpower3.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4260 fix(ipu6-camera-bins): Version provides for devel
  anda/lib/ipu6-camera-bins/ipu6-camera-bins.spec
Labels: sync-f41, sync-el10, sync-f42

#4264 fix?(ipu6*, ivsc*): Add an epoch
  anda/lib/ipu6-camera-bins/ipu6-camera-bins.spec
  anda/system/ivsc-firmware/ivsc-firmware.spec
Labels: sync-f41, sync-el10, sync-f42

#4268 fix(ipu6-camera-bins): Epoch in requirement
  anda/lib/ipu6-camera-bins/ipu6-camera-bins.spec
Labels: sync-f41, sync-el10, sync-f42

#4273 chore(ipu6-camera-bins): Resolve dependency hell
  anda/lib/ipu6-camera-bins/ipu6-camera-bins.spec
Labels: sync-f41, sync-el10, sync-f42

#4281 bump: envision
  anda/apps/envision/envision.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4285 fix(prismlauncher): use mock
  anda/games/prismlauncher-nightly/anda.hcl
  anda/games/prismlauncher/anda.hcl
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4286 Fix: abuild - use git clone macro
  anda/tools/abuild/abuild.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4295 add: readymade
  anda/system/readymade/anda.hcl
  anda/system/readymade/readymade.spec
  anda/system/readymade/update.rhai
Labels: sync-f42

#4310 fix(xpadneo): Hardcode obsolete version
  anda/system/xpadneo/kmod-common/xpadneo.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4317 fix(gnome-shell): rename back without .switcheroo tag suffix
  anda/desktops/gnome/gnome-shell/gnome-shell.spec
Labels: sync-el10, sync-f42

#4324 bump: readymade
  anda/system/readymade/readymade.spec
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10, sync-f42

#4325 add: eza
  anda/langs/rust/eza/anda.hcl
  anda/langs/rust/eza/eza-fix-metadata-auto.diff
  anda/langs/rust/eza/rust-eza.spec
  anda/langs/rust/eza/update.rhai
Labels: sync-el10, sync-f42

#4331 fix(nvidia-driver): Update spec for 575.51.02
  anda/system/nvidia/nvidia-driver/nvidia-driver.spec
Labels: sync-f41, sync-el10, sync-f42

#4272 fix(lomiri-app-launch): Patch to use the correct standard for atomic builtins
  anda/desktops/lomiri-unity/lomiri-app-launch/2004-std-workaround.patch
  anda/desktops/lomiri-unity/lomiri-app-launch/lomiri-app-launch.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4335 feat(xone): Additional firmware needed for the pairing button of some controllers
  anda/system/xone/kmod-common/xone.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4344 feat(xone): Remove custom version for firmware package as it now contains multiple sources
  anda/system/xone/kmod-common/xone.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4349 fix(subtitleedit): dejavu mono dep
  anda/apps/subtitleedit/subtitleedit.spec
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10, sync-f42

#4354 Add: readymade nightly
  anda/system/readymade/nightly/anda.hcl
  anda/system/readymade/nightly/readymade-nightly.spec
  anda/system/readymade/nightly/update.rhai
  anda/system/readymade/stable/anda.hcl
  anda/system/readymade/stable/readymade.spec
  anda/system/readymade/stable/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#4362 fix(subtitleedit): wrong path to exe
  anda/apps/subtitleedit/subtitleedit.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4361 fix: ouch
  anda/langs/rust/ouch/ouch-fix-metadata-auto.diff
  anda/langs/rust/ouch/rust-ouch.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4355 fix(xone): The weird version scheme funny
  anda/system/xone/kmod-common/xone.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4376 add: flatpost
  anda/apps/flatpost/anda.hcl
  anda/apps/flatpost/flatpost-desktop-mimetype.patch
  anda/apps/flatpost/flatpost-mime.xml
  anda/apps/flatpost/flatpost.spec
  anda/apps/flatpost/update.rhai
Labels: new, sync-f40, sync-f41, sync-el10, sync-f42

#4374 Add nekoray (rebase)
  anda/apps/nekoray/Sagernet.SingBox.Version.txt
  anda/apps/nekoray/anda.hcl
  anda/apps/nekoray/nekoray.desktop
  anda/apps/nekoray/nekoray.sh
  anda/apps/nekoray/nekoray.spec
  anda/apps/nekoray/pre.rhai
  anda/apps/nekoray/pre.sh
  anda/apps/nekoray/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4388 fix(flatpost): update.rhai (#4381)
  anda/apps/flatpost/flatpost.spec
  anda/apps/flatpost/update.rhai
Labels: sync-f40, sync-f41

#4394 add: Zig master builds
  anda/langs/zig/0000-increase-upper-bounds-of-main-zig-executable-to-9G.patch
  anda/langs/zig/anda.hcl
  anda/langs/zig/update.rhai
  anda/langs/zig/zig-master.spec
Labels: sync-f42

#4395 feat/fix(ipu6-drivers): Refactor and add DKMS package
  anda/lib/ipu6-camera-bins/ipu6-camera-bins.spec
  anda/system/intel-ipu6-kmod/0000-probe-improvements.patch
  anda/system/intel-ipu6-kmod/0002-fix-compilation-6.10.patch
  anda/system/intel-ipu6-kmod/0003-prefix-modules.patch
  anda/system/intel-ipu6-kmod/0004-fix-compilation-6.11.patch
  anda/system/intel-ipu6-kmod/0005-fix-compilation-6.12.patch
  anda/system/intel-ipu6-kmod/0006-fix-compilation-6.12-no-no_llseek.patch
  anda/system/intel-ipu6-kmod/0007-modules-per-kernel.patch
  anda/system/intel-ipu6-kmod/intel-ipu6-kmod.spec
  anda/system/ipu6-drivers/akmod/0001-Makefile-Switch-sensor-driver-symbols-from-CONFIG_VI.patch
  anda/system/ipu6-drivers/akmod/0002-Makefile-Re-enable-gc5035-compilation-with-kernels-6.patch
  anda/system/ipu6-drivers/akmod/0003-Makefile-Do-not-build-hi556-driver-with-kernels-6.10.patch
  anda/system/ipu6-drivers/akmod/0004-Makefile-Do-not-build-ov01a10-driver-with-kernels-6..patch
  anda/system/ipu6-drivers/akmod/0005-media-ipu6-Fix-out-of-tree-builds.patch
  anda/system/ipu6-drivers/akmod/0006-media-ipu6-Fix-building-with-kernel-6.13.patch
  anda/system/ipu6-drivers/akmod/0007-Modify-0001-v6.10-IPU6-headers-used-by-PSYS.patch-fo.patch
  anda/system/ipu6-drivers/akmod/0008-ipu6-psys-Adjust-DMA-code-for-ipu6-bus-DMA-changes-i.patch
  anda/system/ipu6-drivers/akmod/0009-Add-ipu6-dma.h-to-0001-v6.10-IPU6-headers-used-by-PS.patch
  anda/system/ipu6-drivers/akmod/0010-psys-Do-not-skipping-registering-ipu_psys_bus-for-ke.patch
  anda/system/ipu6-drivers/akmod/0010-usbio-Fix-GPIO-and-I2C-driver-modaliases.patch
  anda/system/ipu6-drivers/akmod/0011-psys-Use-cdev_device_add-for-dev-ipu-psys0.patch
  anda/system/ipu6-drivers/akmod/0011-usbio-Fix-I2C-max-transfer-size.patch
  anda/system/ipu6-drivers/akmod/0012-usbio-Use-MAX_PAYLOAD_BSIZE-in-usbio_bulk_write.patch
  anda/system/ipu6-drivers/akmod/0101-Fedora-local-mod-integrate-usbio-drivers-within-ipu6.patch
  anda/system/ipu6-drivers/akmod/anda.hcl
  anda/system/ipu6-drivers/akmod/intel-ipu6-kmod.spec
  anda/system/ipu6-drivers/akmod/update.rhai
  anda/system/ipu6-drivers/dkms/0001-Makefile-Switch-sensor-driver-symbols-from-CONFIG_VI.patch
  anda/system/ipu6-drivers/dkms/0002-Makefile-Re-enable-gc5035-compilation-with-kernels-6.patch
  anda/system/ipu6-drivers/dkms/0003-Makefile-Do-not-build-hi556-driver-with-kernels-6.10.patch
  anda/system/ipu6-drivers/dkms/0004-Makefile-Do-not-build-ov01a10-driver-with-kernels-6..patch
  anda/system/ipu6-drivers/dkms/0005-media-ipu6-Fix-out-of-tree-builds.patch
  anda/system/ipu6-drivers/dkms/0006-media-ipu6-Fix-building-with-kernel-6.13.patch
  anda/system/ipu6-drivers/dkms/0007-Modify-0001-v6.10-IPU6-headers-used-by-PSYS.patch-fo.patch
  anda/system/ipu6-drivers/dkms/0008-ipu6-psys-Adjust-DMA-code-for-ipu6-bus-DMA-changes-i.patch
  anda/system/ipu6-drivers/dkms/0009-Add-ipu6-dma.h-to-0001-v6.10-IPU6-headers-used-by-PS.patch
  anda/system/ipu6-drivers/dkms/0010-psys-Do-not-skipping-registering-ipu_psys_bus-for-ke.patch
  anda/system/ipu6-drivers/dkms/0010-usbio-Fix-GPIO-and-I2C-driver-modaliases.patch
  anda/system/ipu6-drivers/dkms/0011-psys-Use-cdev_device_add-for-dev-ipu-psys0.patch
  anda/system/ipu6-drivers/dkms/0011-usbio-Fix-I2C-max-transfer-size.patch
  anda/system/ipu6-drivers/dkms/0012-usbio-Use-MAX_PAYLOAD_BSIZE-in-usbio_bulk_write.patch
  anda/system/ipu6-drivers/dkms/0101-Fedora-local-mod-integrate-usbio-drivers-within-ipu6.patch
  anda/system/ipu6-drivers/dkms/anda.hcl
  anda/system/ipu6-drivers/dkms/dkms-intel-ipu6.spec
  anda/system/ipu6-drivers/dkms/no-weak-modules.conf
  anda/system/ipu6-drivers/dkms/update.rhai
  anda/system/ipu6-drivers/kmod-common/anda.hcl
  anda/system/ipu6-drivers/kmod-common/intel-ipu6-drivers.spec
  anda/system/ipu6-drivers/kmod-common/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#4393 fix({akmod-,dkms-}xone): Dropoff epoch and Conflicts/Obsoletes old versions
  anda/system/xone/akmod/xone-kmod.spec
  anda/system/xone/dkms/dkms-xone.spec
  anda/system/xone/kmod-common/xone.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4404 refactor(ipu6-drivers): Nightly
  anda/system/ipu6-drivers/kmod-common/anda.hcl
Labels: sync-f41, sync-el10, sync-f42

#4396 fix(nvidia*): Update and fix various spec parts
  anda/system/nvidia/dkms-nvidia/dkms-nvidia.spec
  anda/system/nvidia/dkms-nvidia/nvidia-kernel-ccflags-y.patch
  anda/system/nvidia/kmod-nvidia/anda.hcl
  anda/system/nvidia/kmod-nvidia/kmod-nvidia-ldflags.patch
  anda/system/nvidia/kmod-nvidia/kmod-nvidia-no-hostname-whoami.patch
  anda/system/nvidia/kmod-nvidia/kmod-nvidia.spec
  anda/system/nvidia/kmod-nvidia/nvidia-kernel-ccflags-y.patch
  anda/system/nvidia/kmod-nvidia/update.rhai
  anda/system/nvidia/nvidia-driver/nvidia-driver.spec
  anda/system/nvidia/nvidia-kmod-common/99-nvidia.conf
  anda/system/nvidia/nvidia-kmod-common/nvidia-boot-update
  anda/system/nvidia/nvidia-kmod-common/nvidia-kmod-common.spec
  anda/system/nvidia/nvidia-kmod/nvidia-kernel-ccflags-y.patch
  anda/system/nvidia/nvidia-kmod/nvidia-kmod.spec
Labels: sync-f41, sync-el10, sync-f42

#4413 feat(zig-master): Make internal version more plain
  anda/langs/zig/zig-master.spec
Labels: sync-f42

#4411 add: egl{-wayland,-x11}
  anda/lib/nvidia/egl-wayland/anda.hcl
  anda/lib/nvidia/egl-wayland/egl-wayland-linux-drm-syncobj.patch
  anda/lib/nvidia/egl-wayland/egl-wayland.spec
  anda/lib/nvidia/egl-wayland/update.rhai
  anda/lib/nvidia/egl-x11/anda.hcl
  anda/lib/nvidia/egl-x11/egl-x11-meson-0.58.patch
  anda/lib/nvidia/egl-x11/egl-x11.spec
  anda/lib/nvidia/egl-x11/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#4422 fix(umu-launcher): update dependencies
  anda/games/umu/umu-launcher.spec
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10, sync-f42

#4248 fix(ipu6-camera-hal): Update patches, update build, add update script because apparently I forgot to do that
  anda/system/ipu6-camera-hal/0000-lib-path.patch
  anda/system/ipu6-camera-hal/0001-CMakeLists-fixes.patch
  anda/system/ipu6-camera-hal/0001-Drop-Werror.patch
  anda/system/ipu6-camera-hal/0002-set-mainline.patch
  anda/system/ipu6-camera-hal/60-intel-ipu6.rules
  anda/system/ipu6-camera-hal/anda.hcl
  anda/system/ipu6-camera-hal/icamera_ipu6_isys.conf
  anda/system/ipu6-camera-hal/ipu6-camera-hal.spec
  anda/system/ipu6-camera-hal/ipu6-driver-select.sh
  anda/system/ipu6-camera-hal/update.rhai
Labels: sync-frawhide, sync-f41, sync-el10

#4427 feat(zig-master): Fix build commands for future bootstrapping, port Fedora patches
  anda/langs/zig/0000-remove-native-lib-directories-from-rpath.patch
  anda/langs/zig/0001-increase-upper-bounds-of-main-zig-executable-to-9G.patch
  anda/langs/zig/0002-build-pass-zig-lib-dir-as-directory-instead-of-as-st.patch
  anda/langs/zig/zig-master.spec
Labels: sync-f42

#4198 fix(zed, zed-nightly, zed-preview): Build and licenses
  anda/devs/zed/nightly/anda.hcl
  anda/devs/zed/nightly/zed-nightly.spec
  anda/devs/zed/preview/anda.hcl
  anda/devs/zed/preview/zed-preview.spec
  anda/devs/zed/stable/anda.hcl
  anda/devs/zed/stable/zed.spec
Labels: sync-f40, sync-frawhide, sync-f41, sync-el10

#4429 fix({dkms-}v4l2loopback{-kmod}): Requires help2man
  anda/system/v4l2loopback/akmod/v4l2loopback-kmod.spec
  anda/system/v4l2loopback/dkms/dkms-v4l2loopback.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4428 fix(andax/nvidia.rhai): Track stable NVIDIA drivers
  andax/nvidia.rhai
Labels: sync-f41, sync-el10, sync-f42

#4444 fix(nvidia-driver): Disable comment note stripping
  anda/system/nvidia/nvidia-driver/nvidia-driver.spec
Labels: sync-f41, sync-el10, sync-f42

#4456 feat(zig-master): Self bootstrap builds take two
  anda/langs/zig/zig-master.spec
Labels: sync-f42

#4458 chore: Update cuda-gcc
  anda/lib/nvidia/cuda-gcc/cuda-gcc.spec
  anda/lib/nvidia/cuda-gcc/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#4445 fix(zed): License fetching
  anda/devs/zed/nightly/zed-nightly.spec
  anda/devs/zed/preview/zed-preview.spec
  anda/devs/zed/stable/zed.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4464 fix: Zig transitve failure failsafe
  anda/langs/zig/zig-master.spec
Labels: sync-f42

#4476 make rdm build on commit
  anda/system/readymade/nightly/anda.hcl
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4471 chore(cuda-gcc): Remove from NVIDIA subrepo to use with packages that need CUDA compatible compilers
  anda/lib/nvidia/cuda-gcc/anda.hcl
Labels: sync-f41, sync-el10, sync-f42

#4472 fix(starship): Update patches
  anda/langs/rust/starship/0001-gix-0.61.1-0.61.0.patch
  anda/langs/rust/starship/rust-starship.spec
  anda/langs/rust/starship/starship-fix-metadata-auto.diff
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4473 fix(egl-wayland,egl-x11): Needs an i686 build, remove the update script
  anda/lib/nvidia/egl-wayland/anda.hcl
  anda/lib/nvidia/egl-wayland/update.rhai
  anda/lib/nvidia/egl-x11/anda.hcl
  anda/lib/nvidia/egl-x11/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#4492 chore: Bump Zed Preview on <= F41
  anda/devs/zed/preview/zed-preview.spec
Labels: sync-f40, sync-el10

#4491 fix(cuda-gcc): Ifcond for GCC version tracking
  anda/tools/cuda-gcc/anda.hcl
  anda/tools/cuda-gcc/cuda-gcc.spec
  anda/tools/cuda-gcc/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#4490 fix(egl): Bump release back up
  anda/lib/nvidia/egl-wayland/egl-wayland.spec
  anda/lib/nvidia/egl-x11/egl-x11.spec
Labels: sync-f41, sync-el10, sync-f42

#4501 fix(egl-x11): Bump release to 6
  anda/lib/nvidia/egl-x11/egl-x11.spec
Labels: sync-f41, sync-el10, sync-f42

#4507 chore: Bump yt-dlp on <= 41
  anda/tools/yt-dlp/yt-dlp-git.spec
Labels: sync-f40, sync-el10

#4503 chore(andax/nvidia.rhai): Bump CUDA component version
  andax/nvidia.rhai
Labels: sync-f41, sync-el10, sync-f42

#4502 chore: Update cuda-nvcc
  anda/tools/cuda-nvcc/cuda-nvcc.spec
Labels: sync-f41, sync-el10, sync-f42

#4514 feat(andax/nvidia.rhai): Automatically fetch new CUDA versions
  andax/nvidia.rhai
Labels: sync-f41, sync-el10, sync-f42

#4529 fix(nekoray): update.rhai
  anda/apps/nekoray/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4535 fix(lightly-qt5): Import andax/bump_extras.rhai for update.rhai
  anda/themes/lightly-qt5/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4546 chore: Mass CUDA update
  anda/lib/nvidia/cuda-cccl/cuda-cccl.spec
  anda/lib/nvidia/cuda-cudart/cuda-cudart.spec
  anda/lib/nvidia/cuda-cudnn/cuda-cudnn.spec
  anda/lib/nvidia/cuda-cuobjdump/cuda-cuobjdump.spec
  anda/lib/nvidia/cuda-cupti/cuda-cupti.spec
  anda/lib/nvidia/cuda-cuxxfilt/cuda-cuxxfilt.spec
  anda/lib/nvidia/cuda-gdb/cuda-gdb.spec
  anda/lib/nvidia/cuda-nvdisasm/cuda-nvdisasm.spec
  anda/lib/nvidia/cuda-nvml/cuda-nvml.spec
  anda/lib/nvidia/cuda-nvprof/cuda-nvprof.spec
  anda/lib/nvidia/cuda-nvprune/cuda-nvprune.spec
  anda/lib/nvidia/cuda-nvrtc/cuda-nvrtc.spec
  anda/lib/nvidia/cuda-nvtx/cuda-nvtx.spec
  anda/lib/nvidia/cuda-profiler/cuda-profiler.spec
  anda/lib/nvidia/cuda-sandbox/anda.hcl
  anda/lib/nvidia/cuda-sandbox/cuda-sandbox.spec
  anda/lib/nvidia/cuda-sandbox/update.rhai
  anda/lib/nvidia/cuda-sanitizer/cuda-sanitizer.spec
  anda/lib/nvidia/cuda/cuda.spec
  anda/lib/nvidia/libcublas/libcublas.spec
  anda/lib/nvidia/libcudla/libcudla.spec
  anda/lib/nvidia/libcufft/libcufft.spec
  anda/lib/nvidia/libcurand/libcurand.spec
  anda/lib/nvidia/libcusparse/libcusparse.spec
  anda/lib/nvidia/libcusparselt/libcusparselt.spec
  anda/lib/nvidia/libnpp/libnpp.spec
  anda/lib/nvidia/libnvfatbin/libnvfatbin.spec
  anda/lib/nvidia/libnvjpeg/libnvjpeg.spec
Labels: sync-f41, sync-el10, sync-f42

#4557 fix(lightly-qt6): Import andax/bump_extras.rhai for update.rhai
  anda/themes/lightly-qt6/update.rhai
Labels: sync-f40, sync-f41, sync-el10, sync-f42

#4554 chore: Bump packages on <= F41
  anda/apps/discord-canary-openasar/discord-canary-openasar.spec
  anda/apps/discord-canary/discord-canary.spec
  anda/apps/ruffle/ruffle-nightly.spec
  anda/tools/yt-dlp/yt-dlp-git.spec
Labels: sync-f40, sync-el10

#4552 feat(nvidia-patch): Change requirement to allow use with DKMS package
  anda/system/nvidia-patch/nvidia-patch.spec
Labels: sync-f41, sync-el10, sync-f42

#4553 add: Some more NVIDIA stuff
  anda/lib/nvidia/libnvjitlink/anda.hcl
  anda/lib/nvidia/libnvjitlink/libnvjitlink.spec
  anda/lib/nvidia/libnvjitlink/nvjitlink.pc
  anda/lib/nvidia/libnvjitlink/update.rhai
  anda/lib/nvidia/libnvjpeg2k/anda.hcl
  anda/lib/nvidia/libnvjpeg2k/libnvjpeg2k.spec
  anda/lib/nvidia/libnvjpeg2k/nvjpeg2k.pc
  anda/lib/nvidia/libnvjpeg2k/update.rhai
  anda/lib/nvidia/nv-codec-headers/anda.hcl
  anda/lib/nvidia/nv-codec-headers/nv-codec-headers.spec
  anda/lib/nvidia/nv-codec-headers/update.rhai
Labels: sync-f41, sync-el10, sync-f42

#4567 fix(steam): Remove broken .desktop file flags
  anda/games/steam/steam.spec
Labels: sync-f40, sync-f41, sync-el10, sync-f42
